### ISSUE TITLE
Enhancement: add action-bar slot to center-row

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#1007]
### Description
Add a slot to ShellCenterRow that plays nice with ActionBar.

### Acceptance Criteria 
* compatible with CalcitePosition and RTL.

### Relevant Info 
![Screen Shot 2020-06-03 at 1 14 00 PM (1)](https://user-images.githubusercontent.com/12503298/83686306-d5497b80-a59e-11ea-80cb-29254d21eaf5.png)
See the action-bar in the right side of center-row in this mockup.

#### Which Component
* CenterRow

#### Example Use Case
See above.

**Comment by driskull** [comment]
I don't see an issue with this.

**Comment by asangma** [comment]
Updated issue based on discussion in regular sync.

**Comment by asangma** [comment]
@kat10140 VERF!

**Comment by jcfranco** [comment]
Per ☝, closing as verified.
