### ISSUE TITLE
A11y: tweak calcite-panel focus order

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#1008]
### Summary

For an improved keyboard experience, the focus order should follow: close button > fab > content (when applicable).

### Actual Behavior

The content is focused before the FAB.

### Expected Behavior

Focus order should follow: close button > FAB > content

### Reproduction Steps

Use the following markup and tab through:

```html
<calcite-panel dismissible>
  <div slot="header-content">panel header</div>
  <calcite-fab label="Add" slot="fab"></calcite-fab>
  <p>Slotted content</p>
</calcite-panel>
```

**Comment by driskull** [comment]
Sounds like a duplicate of #868. You want to close this one or that one?

**Comment by jcfranco** [comment]
Closing in favor of the broader issue. Thanks!
