### ISSUE TITLE
Enhancement: Support dragging items between Calcite Value Lists

### ISSUE THREAD

**Issue by Csmith246** [Esri/calcite-app-components#1016]
### Description
Support the ability to drag a Calcite Value List Item from one Calcite Value List to a different Calcite Value List.

### Acceptance Criteria 

- List Item can be dragged between different lists. 
- Make that cross list movement accessible.
- Expose helpful event hooks for the move operation.

### Relevant Info 
We have already implemented this by using private properties on the Calcite Value List. This implementation can be viewed [here](https://devext.arcgis.com/apps/configure-template/position-manager-config.html). The way to implement the cross list dragging is to give two Calcite Value Lists the same [group name](https://sortablejs.github.io/Sortable/#shared-lists). So maybe it would be helpful to expose that group name as an input property on the Calcite Value List? The SortableJS events that were used in our implementation were [onAdd and onRemove](https://github.com/SortableJS/Sortable#options). So, I would say, consider exposing these (and maybe other) events, so that developers can have hooks to use to support any in app behavior that happens from a cross list drag. 

#### Which Component
Calcite Value List, and Calcite Value List Item

#### Example Use Case
We are using the Calcite Value List to create a widget that allows users to position and order map widgets on the mapView ui. Our implementation can be viewed [here](https://devext.arcgis.com/apps/configure-template/position-manager-config.html)

**Comment by driskull** [comment]
I can help with this as need be. We probably don't want to expose the Sortable instance at all incase we change libraries in the future.

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-app-components/issues/1006 may have an impact on this.

**Comment by jcfranco** [comment]
Addressed via #1059.
