### ISSUE TITLE
Enhancement: Reusable border style

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#1017]
**[calcite-app-border]**- let's make reusable standard border style

Should we make css or sass var?
or a mixin?

Related PR: https://github.com/Esri/calcite-app-components/pull/1015

Let's discuss @jcfranco @asangma 

CC ISSUE https://github.com/Esri/calcite-components/issues/971

**Comment by jcfranco** [comment]
Moved to Esri/calcite-components#971
