### ISSUE TITLE
Bug: Action icon scale should be medium unless Action scale is L

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#1020]
### Summary
Update icon scale in Action to be better.

### Actual Behavior
Icon scale is `s` unless Action scale is `l`. Then it is `m`

### Expected Behavior
Icon scale should be `m` unless Action scale is `l`. Then it should be `l`.

### Reproduction Steps

1. Use the `icon` slot in Action.

**Comment by asangma** [comment]
Seeing issues here: https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1549

**Comment by asangma** [comment]
Sorry...I meant to add a table that made this more clear.

Intended result is

| Action scale | Icon scale |
|:---:|:----:|
| L | M |
| M | S |
| S | S |

**Comment by kat10140** [comment]
lewks gewd

**Comment by asangma** [comment]
Yew!
