### ISSUE TITLE
Bug: action-bar does not synchronize expanded state with new children

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-app-components#1023]
### Summary
If a new child is added to an action-bar and the action-bar is expanded, the new action will not be expanded like the rest. 

### Reproduction Steps

1. See [codesandbox](https://codesandbox.io/s/calcite-app-components-actionbar-expanded-issue-hfxit?file=/src/index.ts)

**Comment by driskull** [comment]
Installed. needs verification. 👍

**Comment by kat10140** [comment]
looks good!
