### ISSUE TITLE
calcite-value-list: calciteListItemChange event

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#1024]
I have been using the event "calciteListItemChange".

It has been working fine for a long time, but I noticed today that the event is being called twice when I click on the row once. I would think that this has not always been like this. The first call returns `selected:true` and the second `selected:false`.

**Comment by driskull** [comment]
@jcfranco can you take this one?

**Comment by jcfranco** [comment]
I could only reproduce this by not using the `multiple` attribute on `pick-list`/`value-list`. Based based on the [event's doc](https://github.com/Esri/calcite-app-components/blob/master/src/components/calcite-pick-list-item/calcite-pick-list-item.tsx#L134), this is working as expected (one event is emitted per item being toggled). 

@AdelheidF Can you confirm this is what you're seeing?

**Comment by driskull** [comment]
That sounds correct since one is turned off and one is turned on.

**Comment by AdelheidF** [comment]
OK, but this is weird if I just want a clickable list. I guess I'm going to check the selected state before I proceed with my 'click' handler.

<img src=https://user-images.githubusercontent.com/44481292/86152526-291f8580-bab5-11ea-9742-7ac2517f6051.png width=200/>

Would it make sense to have a `calciteListItemClick` event if multiple is set to false (no `selected` state) and `calciteListItemChange` only if multiple is set to true?

**Comment by AdelheidF** [comment]
never mind what I said, closing...
