### ISSUE TITLE
Bug: calcite-pick-list group items remain when filtering

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#1026]
### Summary
The blend layer ux in in the map viewer uses a calcite popover combined with a panel and picklist. It works well except when attempting to filter out the picklist values.
 
After applying a filter, all of the pick list group options continue to show. Is it possible for the groups to be hidden if it doesn’t contain one of the filtered pick list values?
 
 
![pick-list](https://user-images.githubusercontent.com/11093161/86031560-d7122d80-b9ea-11ea-8246-d7a773e68ec0.jpg)

### Expected Behavior

Hide the calcite-pick-list-group items when filtering

### Reproduction Steps

1.

**Comment by jcfranco** [comment]
Found the issue. The code that handles filtering doesn't account for non-nested groups (using `slot=parent-item`), so those groups always stay visible when there are no matches.

**Comment by jcfranco** [comment]
Installed.

**Comment by AdelheidF** [comment]
Looks like there was no calcite-app-release for this one, correct? 
I assume there would be a lot of other changes in a new release. Not sure if we should go for it so close to beta 7...

**Comment by AdelheidF** [comment]
Should this be part of "@esri/calcite-app-components@6.1.0-beta.9" ? I tried this locally and don't see a change.

<img src=https://user-images.githubusercontent.com/44481292/86635584-1bbc3c80-bf88-11ea-9de3-c39b00015017.png width=200/>


@cwwhitmore

**Comment by cwwhitmore** [comment]
Thanks @AdelheidF for looking into this. Think at this point, it can just wait until the next beta.

**Comment by kat10140** [comment]
looks good! closing
