### ISSUE TITLE
Bug: calcite-block-section toggle button spacing

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#1027]
### Summary
if enabled spacing looks good
<img src=https://user-images.githubusercontent.com/44481292/86072684-f8990680-ba36-11ea-8ba9-47915ba639ab.png width=200/>

if disabled spacing is not good
<img src=https://user-images.githubusercontent.com/44481292/86072695-051d5f00-ba37-11ea-8eee-11e0aee95175.png width=200/>

CC ISSUE https://github.com/Esri/calcite-components/issues/972

**Comment by jcfranco** [comment]
@asangma I think this is caused by `calcite-scrim`'s content node layout.

**Comment by jcfranco** [comment]
Moved to Esri/calcite-components#972
