### ISSUE TITLE
Enhancement: ActionBar & ActionPad. Add scale property that its Actions inherit.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#1033]
### Description
Add a `scale` property to ActionBar and ActionPad.
The main issue is that we set the scale on the expand action inside ActionBar, so if a user wants to set all their Actions to `scale="s"`, the expand Action is still `scale="m"`.

### Acceptance Criteria 
* Actions inherit the scale property (including expand Action)

#### Which Component
* Action
* ActionBar
* ActionPad

#### Example Use Case
Setting all Actions in an ActionBar to `scale="s"`.

**Comment by kat10140** [comment]
https://github.com/Esri/calcite-components/issues/962
