### ISSUE TITLE
Bug: Action. Icon size update.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#1034]
### Description
Currently designs call for small scale icons in medium scale Actions. 
Action in medium scale currently sets medium scale icons. So our users are not able to use the `icon` prop.

Should be like this.
| Action scale | Icon Scale |
|:-----------:|:----------:|
| L | M |
| M | S |
| S | S |

#### Which Component
Action

**Comment by kat10140** [comment]
lewks gewd
