### ISSUE TITLE
Fix axe issues on demo page

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#104]
[axe](https://www.deque.com/axe/) finds the following issues on the demo page (Home tab):

* `<html>` element must have a lang attribute
* Document must have one main landmark
* All page content must be contained by landmarks
* Elements must have sufficient color contrast

Stems from https://github.com/ArcGIS/calcite-app-components/pull/99#pullrequestreview-268697869

cc @driskull

**Comment by jcfranco** [comment]
As of today, axe reports the following:

`calcite-flow`

<img width="777" alt="Screen Shot 2019-08-19 at 10 22 40 AM" src="https://user-images.githubusercontent.com/197440/63286235-6cda1980-c26c-11e9-8e9e-6cc76c0b7f44.png">

`calcite-shell`

<img width="1379" alt="Screen Shot 2019-08-19 at 10 22 03 AM" src="https://user-images.githubusercontent.com/197440/63286223-6350b180-c26c-11e9-8df9-d3699152923d.png">

There are other issues found by axe, but they're either related to the test page content, or already have an existing issue.

**Comment by driskull** [comment]
The first one is remedied by putting an anchor inside the content. So not really an aXe issue.

I'm not sure where the SVGs are coming from in the second example. They are not in the HTML.

**Comment by driskull** [comment]
@jcfranco the svg's are coming from the two arcgis maps.

![image](https://user-images.githubusercontent.com/1231455/63287788-140c8000-c270-11e9-9632-32036e5e2a6c.png)

I'm not sure why these empty SVG's exist, do you?

**Comment by driskull** [comment]
Created issue: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/new?assignees=&labels=bug%2C+4.x&template=bug-4.x.md&title=Bug+-+

**Comment by jcfranco** [comment]
@driskull Thanks for looking into this. Closing as verified!
