### ISSUE TITLE
Bug: calcite-block-section calciteBlockSectionToggle is not fired anymore

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#1040]
### Summary
calcite-block-section calciteBlockSectionToggle is not fired anymore, everywhere we use these and bind to that event, we dont see it ever triggered

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
Seems to need need an update to calcite components beta 33.

**Comment by jcfranco** [comment]
@AdelheidF @kevindoshier This should be fixed in the latest release (6.1.1). Can you retest?

**Comment by AdelheidF** [comment]
Seems to be fixed, tested locally.
