### ISSUE TITLE
Bug: calcite-pick-list-item is always using the circleF icon even when not selected

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#1042]
### Summary
calcite-pick-list-item is always using the circleF icon even when not selected

![image](https://user-images.githubusercontent.com/11093161/88111231-68943b80-cb62-11ea-96b0-e5c1b52c85f8.png)

If I construct a calcite-pick-list-item, and set "selected" to false, then this is reproduceable, this was working before, but I installed a change in the app to not set that attribute to false, only set it when its true.

cc: @AdelheidF 

### Reproduction Steps

1.

**Comment by kevindoshier** [comment]
Also, I create these programatically using `document.createElement("calcite-pick-list-item")`  which might have exposed this issue

**Comment by jcfranco** [comment]
@kevindoshier Is it also displaying the icon? The list item will hide it via CSS. If it **is** visible, can you share a snippet showing how you're using list items programmatically?

**Comment by jcfranco** [comment]
This is working as expected: setting the property to `true`/`false` or adding/removing the `selected` attribute works properly.
