### ISSUE TITLE
slot-container height of 0

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#1044]
### Summary

Not sure what component this goes to. The table no longer shows in the center.
Happens with 6.1.1, did not happen with 6.1.0.

http://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
Click 'Show table' from layer menu.

<img src=https://user-images.githubusercontent.com/44481292/88345479-dc694c00-ccfa-11ea-9601-ccb147c9a101.png width=300/>

The div with class slot-container has a height of 0.
<img src=https://user-images.githubusercontent.com/44481292/88345334-9dd39180-ccfa-11ea-967e-137c1c934fae.png width=400/>

If I use the debugging tools and add a height of 100% it looks fine.
<img src=https://user-images.githubusercontent.com/44481292/88345407-be9be700-ccfa-11ea-9338-f7a38741985b.png width=400/>

<img src=https://user-images.githubusercontent.com/44481292/88345436-cb203f80-ccfa-11ea-857d-d25509e4ff14.png width=300/>

cc @zaramatheson

### Reproduction Steps

1.

**Comment by asangma** [comment]
Cool cool. I got it.

**Comment by asangma** [comment]
@AdelheidF Lemme know if you can verify.

**Comment by AdelheidF** [comment]
Verified locally using beta.0. Waiting for a release for devext.

**Comment by asangma** [comment]
Thanks @AdelheidF !
