### ISSUE TITLE
Enhancement: Ability to drag and drop items between different lists

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-app-components#1056]
### Description
Currently, can move the list-items within the list. Need ability to move them between different lists.

![list](https://user-images.githubusercontent.com/14285436/90272103-bb83aa80-de11-11ea-9356-16fc0470a28a.png)

**Comment by jcfranco** [comment]
Installed!

**Comment by kat10140** [comment]
leaving this in this repo since installed. @dhrumil83 can you verify?

**Comment by dhrumil83** [comment]
Looks good.
