### ISSUE TITLE
Bug: calcite-block-section and intlExpand/intlCollapse

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#1062]
### Summary

The documentation has these `intlExpand` and `intlCollapse` properties for `calcite-block-section`, but the labels don't seem to appear.
https://github.com/Esri/calcite-app-components/tree/master/src/components/calcite-block-section

You can see this in the story book as well.
https://esri.github.io/calcite-app-components/?path=/story/components-calcite-block--basic

### Reproduction Steps

1.

**Comment by jcfranco** [comment]
Issue moved to [Esri/calcite-components #1074](https://github.com/Esri/calcite-components/issues/1074) via [**ZenHub**](https://www.zenhub.com/)
