### ISSUE TITLE
Enhancement: Make Calcite-Value-List-Item fully draggable

### ISSUE THREAD

**Issue by Csmith246** [Esri/calcite-app-components#1064]
### Description

In configurable apps, we are using the Calcite Value List in a component in our configuration experience. We have received feedback through holistic testing that many users find the drag and drop functionality with the Value List Items confusing. They don't like that the Value List Items can only be moved by using the 6 dots icon on the left side of the element. They have instead expressed a desire for the entire Value List Item to be draggable. So no matter where you "click and hold" on the Value List Item, it starts the dragging behavior.

For context, here is what it looks like now. We think it would be best if the entire value list item were draggable.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22039422/94075657-6f346e80-fdb0-11ea-96a7-6a978af0ce6b.png)

### Acceptance Criteria 
The entire Value List Item is made to be draggable, instead of just using the 6 dots.

#### Which Component
Calcite Value List, and Calcite Value List Item

**Comment by jcfranco** [comment]
Issue moved to [Esri/calcite-components #1073](https://github.com/Esri/calcite-components/issues/1073) via [**ZenHub**](https://www.zenhub.com/)
