### ISSUE TITLE
Enhancement: Add dark-theme toggle to demos

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#115]
### Description
Add a quick way to switch demo into dark theme. Or add a dark theme section to each demo.

### Acceptance Criteria 
Join the dark side.

#### Desired New Behavior
It's dark.

#### Desired Change to Look and Feel
Darkness.

#### Out of Scope
Going to the light.

### Relevant Info 
It's less light.

### Helpful Details
Dark is darker than light.

**Which Component:**
All the components.

@jcfranco Assigning to you because fun.

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-app-components/issues/401 should help with this. Moving milestone to align with the Storybooks work. cc @kat10140

**Comment by jcfranco** [comment]
Toggling the theme will be possible once https://github.com/Esri/calcite-app-components/pull/631 is merged. @asangma @kat10140 Will this suffice or do we still need this for the demo pages?

**Comment by jcfranco** [comment]
Closing since storybook will allow us to toggle the theme.
