### ISSUE TITLE
Enhancement: TipManager - Arrow key navigation support

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#126]
### Description

TipManager arrow key navigation support

Using the arrow keys while a tip is the active element should allow for pagination.

### Acceptance Criteria 

- Right/Up arrow moves to next tip
- Left/Down arrow moves to previous tip

### Helpful Details

**Which Component:** TipManager
**Example Use Case:** User clicks on a tip or a tip is within focus and can use the arrow keys to paginate.

**Comment by pr3tori4n** [comment]
@driskull  please verify.

**Comment by driskull** [comment]
👍
