### ISSUE TITLE
Enhancement: Tip - add generic slot to allow custom content

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#127]
### Description
The structure of the Tip is nice. It would also be good to let users do something like put a big image in the info area.

### Acceptance Criteria 
- user can add their own html into the content/info area
- user can add an image and not have to use the thumbnail attribute
- still work in Tip Manager

#### Desired New Behavior
User (developer) should be able to utilize the Tip to house whatever custom content they like while still having the functionality of the header section and still have it work in Tip Manager.

#### Desired Change to Look and Feel
No real change.

#### Out of Scope
Life.

### Helpful Details

**Which Component:**
Tip

**Example Use Cases:**
Developer needs the tip to be just an illustration.
Developer needs to add a small table.
Developer has a custom component to add to the Tip.

**Comment by pr3tori4n** [comment]
@asangma this is already possible using the info slot. The slot will accept any valid html, including an img tag, table tag or another custom component.

**Comment by pr3tori4n** [comment]
@asangma Please verify
