### ISSUE TITLE
Question: Hotkey integration?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#131]
### Question
Should we do it?

### Helpful Details
https://github.com/github/hotkey

**Topic:**
Hotkeys.

**Context:**
Erthang.

**Comment by jcfranco** [comment]
@kat10140 Can you triage this one and determine whether this is something we should handle or leave it to app dev?

**Comment by kat10140** [comment]
I think we should leave this to the app. If we decide to add some shortcut support for shell, I'll make another issue.
