### ISSUE TITLE
Enhancement: Homepage demo needs a description and more content

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#134]
### Description

Homepage demo needs a description and more content

### Acceptance Criteria 

There is content about what these components are and their purpose. Could be content reused from readme.

### Helpful Details

https://arcgis.github.io/calcite-app-components/

**Comment by kat10140** [comment]
@driskull should i just do this manually or are yall still looking into a script?

**Comment by driskull** [comment]
I think this should be done manually.

**Comment by kat10140** [comment]
@driskull sry this was referencing https://github.com/Esri/calcite-app-components/issues/137 😆 i'll go ahead and do that one manually as well

**Comment by driskull** [comment]
Oh, for #137 we can probably just link to the readme files for now. Demos shoud link to readme and readme should link to demos.
