### ISSUE TITLE
Bug: background color vars not working in edge

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#136]
### Summary

background color vars not working in edge

### Actual Behavior

In Edge, some color vars are not working. I'm not sure if the variables arent being loaded correctly from Sass or if the issue is with the CSS variables.

### Expected Behavior

The `calcite-action` should have a background color by default in Edge.

### Reproduction Steps

1. Open the following URL in edge. https://arcgis.github.io/calcite-app-components/demos/calcite-action.html
2. Notice how the background color styles are missing

### Relevant Info 

Edge

![image](https://user-images.githubusercontent.com/1231455/62483872-9e7fba80-b76d-11e9-8084-471dad24144b.png)

**Comment by jcfranco** [comment]
Verified on https://esri.github.io/calcite-app-components/demos/calcite-action.html.
