### ISSUE TITLE
Enhancement: Improve demo pages 

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#137]
### Description

Demos need
 - example code to go along with examples
 - descriptions at top of file
 - links to documentation file or some way to inject the markdown file into the HTML
 - Codepen links to samples?

### Acceptance Criteria 

Demos contain a description of the component, its purpose and how to use it. Code samples should be shown and the documentation for the component should be available by link or embedded into the page

#### Desired New Behavior

Pages have more information for users to see how they are used and code snippets are provided

#### Desired Change to Look and Feel

N/A

#### Out of Scope

Design

### Helpful Details

**Which Component:** All
**Example Use Case:**

User stumbles on gh pages and sees component demos but doesn't know how to use them or what the correct purpose for a component is.

**Comment by kat10140** [comment]
@driskull can this one be closed? or do we want to keep it open for later when we add code snippets/codepen links

**Comment by driskull** [comment]
We can close it if we create a separate issue for the snippets/codepen links. Otherwise we can leave it open.
