### ISSUE TITLE
Bug: Shell footer not honoring theme

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#139]
### Summary

See cyan box in screenshot below:

<img width="1563" alt="Screen Shot 2019-08-06 at 10 12 12 AM" src="https://user-images.githubusercontent.com/197440/62560978-064c0900-b833-11e9-954d-4296fdf3cf2d.png">

### Actual Behavior

Dark theme font color not being honored.

### Expected Behavior

Footer text color to contrast and fit theme.

### Reproduction Steps

See Dark theme example from https://esri.github.io/calcite-app-components/demos/calcite-shell.html 

### Relevant Info 

Seen on Chrome.

**Comment by driskull** [comment]
@asangma I think this is the last issue for V1.

**Comment by asangma** [comment]
So, if you put a component in there, the theme is honored. Do we want generic styles inside our components? Seems overly prescriptive...?

**Comment by driskull** [comment]
@asangma if the background color variable is being set, it seems like the color one should be too.

"child" components probably shouldn't set the `background-color` or `color`. Only parent ones should.

**Comment by asangma** [comment]
Installed.

**Comment by jcfranco** [comment]
Verified locally.
