### ISSUE TITLE
Doc: Named slots

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#140]
Stems from https://github.com/ArcGIS/calcite-app-components/pull/110#issuecomment-518772688:

- `calcite-action-bar`
  - `bottom-actions`: A slot for adding `calcite-action`s that are to be placed at the bottom of the action bar above the collapse/expand button.
- `calcite-block` has a `control` slot for inlining a single HTML control (a type of input element) in a header. See https://arcgis.github.io/calcite-app-components/demos/calcite-block.html (Header + control) for an example.
- `calcite-flow-item`
  - `menu-actions`: A slot for adding `calcite-action`s to a menu under the `...` in the header of a `calcite-flow-item`. These are displayed when the `calcite-flow-item`'s menu is open.
  - `footer-actions`: A slot for adding `calcite-action`s to the footer of a `calcite-flow-item`. 
- `calcite-shell-panel`
  - `action-bar`: A slot for adding an action bar to the panel.
  - `floating-panel`: A slot for adding a `calcite-floating-panel` to the `calcite-shell-panel`. The floating panel will be positioned relative to the panel when displayed.
  - `acton-pad`: A slot for adding a `calcite-action-pad` to the `calcite-shell-panel`. The action pad will be positioned relative to the panel when displayed.
- `calcite-shell`
  - `shell-header`:  A slot for adding header content to the `calcite-shell`. The slot content will be positioned at the top of the shell. Can be anything.
  - `shell-footer`:  A slot for adding footer content to the `calcite-shell`. The slot content will be positioned at the bottom of the shell.  Can be anything.
  - `primary-panel`: A slot for adding the leading `calcite-shell-panel`.
  - `secondary-panel`: A slot for adding the trailing `calcite-shell-panel`.
  - `tip-manager`:  A slot for adding a `calcite-tip-manager` component which will be absolutely positioned. (@asangma I think we need to add this to shell demo and experiment with it)
- `calcite-tip`
  - `info`: todo @pr3tori4n 
  - `link`: todo @pr3tori4n 

@asangma can you elaborate on the purpose/difference between footer and menu actions?

cc @driskull @pr3tori4n

**Comment by kat10140** [comment]
Can you verify please @jcfranco ?

**Comment by kat10140** [comment]
(do we need to go through the same process here like we do for sdk stuff?)

**Comment by jcfranco** [comment]
@kat10140 I'm not familiar with the SDK process. 😄

**Comment by jcfranco** [comment]
Verified.
