### ISSUE TITLE
Research: Travis CI Integration

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#152]
### Background

Having tests run automatically on the repo would help catch regressions earlier.

### Desired Outcome

Use [Travis CI](https://travis-ci.com/) to take care of this.

**Comment by jcfranco** [comment]
@kat10140 Can you help verify?

**Comment by kat10140** [comment]
Badge is on master readme 👍 build is unknown 😅

**Comment by jcfranco** [comment]
Ah, I think it's because branch builds aren't enabled. I'll submit a follow-up PR.

**Comment by kat10140** [comment]
I just opened Travis and the build is passing

**Comment by kat10140** [comment]
yay build is passing! Closing
