### ISSUE TITLE
Research: Manual Testing of components

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#153]
### Background

Research: Manual Testing of components once in beta

### Desired Outcome

Components work on all supported browsers and mobile devices

## Components

- [ ] "calcite-action"
- [ ] "calcite-action-group"
- [ ] "calcite-action-bar"
- [ ] "calcite-action-pad"
- [ ] "calcite-block"
- [ ] "calcite-block-section"
- [ ] "calcite-demo-nav"
- [ ] "calcite-example"
- [ ] "calcite-flow"
- [ ] "calcite-flow-item"
- [ ] "calcite-shell"
- [ ] "calcite-shell-panel"
- [ ] "calcite-floating-panel"
- [ ] "calcite-tip"
- [ ] "calcite-tip-group"
- [ ] "calcite-tip-manager"

### Windows

- [ ] Edge
- [ ] Chrome
- [ ] Firefox

### OSX

- [ ] Safari
- [ ] Chrome
- [ ] Firefox

## Devices

- [ ] iPad: safari
- [ ] iPad: chrome
- [ ] iPhone: safari
- [ ] iPhone: chrome
- [ ] Android phone: chrome
- [ ] Android phone: firefox
- [ ] Android tablet: chrome
- [ ] Android tablet: firefox

**Comment by driskull** [comment]
- Am I missing any devices/browsers we want to test?
- How do we want to split up testing

**Comment by driskull** [comment]
Issue with action bar text in mobile: 
![image](https://user-images.githubusercontent.com/1231455/63470053-7a380500-c420-11e9-95b9-63255f0a4069.png)

**Comment by asangma** [comment]
Icons in Action sometimes aligned wrong.
See the ellipses here:
![IMG_194B5D4C1A27-1](https://user-images.githubusercontent.com/12503298/63470247-fe8a8800-c420-11e9-8730-5ecb92c836c1.jpeg)

**Comment by kat10140** [comment]
Bug: Flow on chrome/windows
When clicking example link in 2nd flow item RTL- takes user back to top and removes first LTR flow.

**Comment by kat10140** [comment]
Styling issue: ALAN PLEASE STYLE!!! padding on Shell - shell floating panels 
TY :D

**Comment by driskull** [comment]
removing all tips should handle gracefully and not show anylonger.

Talk about empty state on tip manager. If tipmanager doesn't have a tip, Needs a developer empty state. So it should empty but be min-height

If not more than 1 tip, do not show pagination


TipManager should have a min-height

**Comment by driskull** [comment]
nav bar doesn't span full width on mobile

**Comment by jcfranco** [comment]
#### General

* Add note to mention shell only supports tablet as smallest size

#### IOS (Safari)

**`calcite-action`**

* Tapping text actions does not change color, white ones do

Tapped white action

![IMG_2151](https://user-images.githubusercontent.com/197440/63472307-8030e480-c426-11e9-80e6-140bbdc9189a.jpeg)

Tapped blue action

![IMG_2152](https://user-images.githubusercontent.com/197440/63472309-8030e480-c426-11e9-872a-37216832162f.jpeg)

**`calcite-shell`**

* Padding on floating panel a bit skinny

![IMG_2153](https://user-images.githubusercontent.com/197440/63472250-60012580-c426-11e9-8ac8-658752beb42c.jpeg)

* Auto-close floating panels when tapping outside of container (same for action menus)
* Padding on 'sectionless' block content 

![IMG_2154](https://user-images.githubusercontent.com/197440/63472208-44961a80-c426-11e9-9a72-b341b6d1754b.jpeg)

**`calcite-shell-panel`**

* Primary content padding looks 😭 

![IMG_2155](https://user-images.githubusercontent.com/197440/63472173-27f9e280-c426-11e9-986d-b76904be979e.jpeg)

☝️Same on IOS + Chrome & IOS Firefox

#### VM Win 10 + Edge (18)

**`calcite-tip-manager`**

* Spacing looks different

Chrome 👇 

<img width="1669" alt="Screen Shot 2019-08-21 at 2 42 36 PM" src="https://user-images.githubusercontent.com/197440/63472058-d3566780-c425-11e9-930d-e955b0351b04.png">

Edge 👇 

<img width="1317" alt="Screen Shot 2019-08-21 at 2 43 47 PM" src="https://user-images.githubusercontent.com/197440/63472059-d3566780-c425-11e9-9ec4-7e63b5f6a053.png">

#### VM Win 10 + FF (68)

* No focus outlines

**`calcite-tip-manager`**

* Same spacing issue mentioned above.

#### VM Win 10 + Chrome

**`calcite-tip-manager`**

* Same spacing issue mentioned above.

**Comment by kat10140** [comment]
> Issue with action bar text in mobile:
> ![image](https://user-images.githubusercontent.com/1231455/63470053-7a380500-c420-11e9-95b9-63255f0a4069.png)
> 
> @asangma this is because of the `max-width: 15vw;` in the `calcite-action-bar.scss`

Matt, what browsers?

**Comment by driskull** [comment]
all browsers, even desktop if resized

**Comment by kat10140** [comment]
disregarding `shell-panel` primary content padding bc alan said it's not an issue. all other issues have been made and assigned.
