### ISSUE TITLE
Bug: Block control slot example is broken

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#157]
### Summary

The label wrapping the Block's control messes up slot distribution.

### Actual Behavior

Control isn't rendered in the header as expected.

### Expected Behavior

The control slot is meant to be visible at all times as part of the Block header.

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-block.html
2. Notice the *Header + control* example is not displaying a control.

**Comment by jcfranco** [comment]
Installed. @driskull Could you verify on the GH pages?

**Comment by driskull** [comment]
I see the input control now.
