### ISSUE TITLE
Enhancement: disabled property on `calcite-action`

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#162]
### Description
Can there be a disabled property on calcite-action to grey the action out?
### Helpful Details

**Which Component:**
**Example Use Case:**
For instance the `Edit` action in map maker should be disabled if there are no editable layers

cc: @driskull @jcfranco @asangma

**Comment by driskull** [comment]
@asangma ready for styling

**Comment by asangma** [comment]
@driskull Can I close this since we have #170?

**Comment by driskull** [comment]
sure

**Comment by asangma** [comment]
cool
