### ISSUE TITLE
Doc: Add project guidelines

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#172]
### Description

In order to help promote best practices and conventions, we need to centralize information in a document. The `calcite-example` has been indirectly used as a way to keep track of some of these conventions, but having a dedicated document would be more adequate.

The doc should cover things that we currently have no automated way of calling out/fixing. Anything else should be left to the linters/formatters.

The doc can start off as a wiki and could be eventually moved to the main `README.md`. 

### Relevant Info

https://github.com/ionic-team/stencil/blob/master/STYLE_GUIDE.md
https://github.com/Esri/calcite-components/blob/master/conventions/README.md

**Comment by jcfranco** [comment]
@kat10140 No. 😄

**Comment by kat10140** [comment]
dis done
