### ISSUE TITLE
Enhancement: Centralize foreground and background style

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#175]
### Description
Refactor Sass so that we set the foreground and background colors in one place.
Could be a mixin or styles set on `:host` in **_base.scss**.

**Which Component:**
All.

Follow up from #174 #139

**Comment by asangma** [comment]
@kat10140 Would you mind verfeeing this? I'm not allowed to do that with my own issues. 😆

**Comment by kat10140** [comment]
Verifeed closing
