### ISSUE TITLE
Enhancement: Make it super easy to toggle panels

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#176]
### Description
Make it easy to toggle panels off...maybe also add a "preview" thing that 

1. sees what panels are open
1. closes all panels
1. reopens what panels were open

### Acceptance Criteria 
Kevin and Adelheid can do it easily.

#### Desired New Behavior
Easy way to wire up panel/panel content toggling.

### Relevant Info
Getting a fair bit of feedback expressing desires to hide panels or go into "preview mode".

**Which Component:**
* Shell
* ShellPanel

**Comment by asangma** [comment]
@kat10140 Would you mind assigning this?

**Comment by driskull** [comment]
I think the `calcite-panel` that is `dismissible` helps with this. They could easily checked which are dismissed

**Comment by asangma** [comment]
So a panel can get a `dismissed` earmark and be hidden.
To bring them back, app just removes the dismissed earmark.
?

**Comment by driskull** [comment]
yep... if by earmark you mean attribute 👂

**Comment by asangma** [comment]
lol yeah

**Comment by asangma** [comment]
@kevindoshier does that work for you?
I should also say that in "preview mode" the primary action-bar should not be hidden.

**Comment by kevindoshier** [comment]
Im not understanding what its trying to solve, is it to hide the entire panel including the actionbar?

**Comment by asangma** [comment]
it's to be able toggle all open panels on/off. E.g. map preview.
but it'd be geed to keep at least the primary action-bar visible when the panels are hidden.

it's also to be able to toggle visibility of a panel w/o destroying its contents.

**Comment by kevindoshier** [comment]
I think it would be easier to have a "preview" earmark on the shell then

**Comment by asangma** [comment]
ah. @driskull wut say u?

**Comment by kevindoshier** [comment]
How would this handle the header/footer, or if panels have floating windows, action pads, etc open, will it hide those as well?

**Comment by driskull** [comment]
I'm not sure I understand the issue completely. Maybe we can meet about it?

**Comment by asangma** [comment]
k

**Comment by kevindoshier** [comment]
Im pretty swamped today, lets try to meet tomorrow

**Comment by asangma** [comment]
Per our discussion, I think we can close this.
