### ISSUE TITLE
Enhancement: Add event for when a component is closed

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#179]
### Description

Add event for when a component is closed

cc @AdelheidF 

### Acceptance Criteria 

Add a consistent event for the component being closed/hidden

#### Out of Scope

Anything other than the event

### Helpful Details

**Which Component:**

Applies to:

- [x] `calcite-floating-panel`
- [x] `calcite-tip-manager`
- [x] `calcite-tip`

**Example Use Case:**

A user wants to know when the component has been closed. They cant listen to the `hidden` or `dismissed` properties.

**Comment by jcfranco** [comment]
Verified locally.
