### ISSUE TITLE
Enhancement: rename `calcite-floating-panel`

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#183]
### Description

rename `calcite-floating-panel` to indicate that it is tied to a `calcite-shell-panel`.

### Acceptance Criteria 

`calcite-floating-panel` is renamed to indicate that it is positioned to a `calcite-shell-panel`

### Relevant Info 

Adelheid was confused about the `calcite-floating-panel` and how it is positioned.

I think it would help if the name indicated that it belongs to a `calcite-shell-panel`.

### Helpful Details

Rename candidates:

- `calcite-shell-floating-panel`
- `calcite-shell-panel-floating-panel`

@asangma ideas?

**Comment by kat10140** [comment]
i vote `calcite-shell-floating-panel`

**Comment by driskull** [comment]
Sounds good. Can we proceed with that name @kat10140 ?

**Comment by kat10140** [comment]
@driskull yap im on it

**Comment by kat10140** [comment]
![Screen Shot 2019-08-20 at 2 27 58 PM](https://user-images.githubusercontent.com/48069902/63385949-c880d180-c356-11e9-921c-da9ed97cc399.png)
do you want me to go ahead and change the slot names and the headers for the demo and everything associated with floating panel?

**Comment by driskull** [comment]
yeah
