### ISSUE TITLE
Bug: calcite-floating-panel appears on wrong side

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#185]
### Summary
```
     <calcite-shell-panel slot="contextual-panel" layout="leading">
          <calcite-floating-panel slot="floating-panel" position-type="side" hidden></calcite-floating-panel>
          <calcite-flow id="flow">
      </calcite-shell-panel>
```

As positionElement I use the content of a flow item.

### Actual Behavior
floating panel appears on right side of contextual panel

### Expected Behavior
floating panel appears on left side of contextual panel

**Comment by AdelheidF** [comment]
I made sure that my built code has the latest changes. 
E.g. I checked that
...\arcgis-components\node_modules\@esri\calcite-app-components\dist\collection\components\calcite-action-pad\calcite-action-pad.css contains this
```
:host([hidden]) {
  display: none;
}
```

and when I switch my panel to be contextual I still see the floating panel open on the right side.

![image](https://user-images.githubusercontent.com/44481292/63469892-1d3c4f00-c420-11e9-8d07-49200f9c7910.png)

**Comment by driskull** [comment]
@AdelheidF can you change the `calcite-shell-panel` layout to `trailing`?

**Comment by driskull** [comment]
It should be trailing since the panel is on the right side.

**Comment by AdelheidF** [comment]
![image](https://user-images.githubusercontent.com/44481292/63471281-8bcedc00-c423-11e9-91d4-faea724fb10d.png)

Same effect. the floating panel opens on the right side.

**Comment by driskull** [comment]
removing all tips should handle gracefully and not show anylonger.

**Comment by driskull** [comment]
Talk about empty state on tip manager.

**Comment by driskull** [comment]
If not more than 1 tip, do not show pagination

**Comment by driskull** [comment]
TipManager should have a min-height

**Comment by driskull** [comment]
hmm that should work. I'll stop by or create a demo to reproduce.

**Comment by driskull** [comment]
@jcfranco do I need to update the release number to get it to Adelheid?

**Comment by jcfranco** [comment]
You need to use the release scripts, otherwise there's no distributable to ship.

**Comment by AdelheidF** [comment]
Seems to work OK.

**Comment by AdelheidF** [comment]
But I have to use position-type, not placement as the doc says. Same for action-pad.
