### ISSUE TITLE
Enhancement: Implied clickable areas aren't always clickable

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-app-components#186]
🚨 Nitpicky design issue alert

### Description
There are a lot of "dead areas" between and around buttons, caused by spacing and border radius. Because buttons are "clear", I think this will lead to a lot of rage clicking around the edges of buttons as users try to figure out just where they can click. 

![Screen Shot 2019-08-20 at 12 34 43 PM](https://user-images.githubusercontent.com/4733155/63378828-e4c94200-c347-11e9-835f-6754b158383a.png)
![Screen Shot 2019-08-20 at 12 33 56 PM](https://user-images.githubusercontent.com/4733155/63379007-412c6180-c348-11e9-8bc4-a12acd29c0ee.png)

#### Desired Change to Look and Feel

It would be nice if there were no "dead areas" around buttons, especially when a button is the only thing presented in an ActionPad (single "add" button example) - I'd expect to be able to click anywhere in that area to perform the action.... 

![Screen Shot 2019-08-20 at 12 45 09 PM](https://user-images.githubusercontent.com/4733155/63379084-6a4cf200-c348-11e9-9638-037d319bfd6e.png)

Obviously adding a bg is a nonstarter since it's really good looking as presented, but maybe extending the clickable area to take up the entirety of the implied clickable area could help?

**Comment by driskull** [comment]
👍 clickable area should be considered

**Comment by mitc7862** [comment]
@asangma I think this issue covers what we talked about updating for the actions.

**Comment by asangma** [comment]
See #489

**Comment by asangma** [comment]
@macandcheese Please verify.

**Comment by kat10140** [comment]
closing! reopen if there are any issues @macandcheese
