### ISSUE TITLE
Bug: <calcite-action> indicator is positioned differently if it has text

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#187]
### Summary

<img width="460" alt="Screen Shot 2019-08-20 at 1 10 41 PM" src="https://user-images.githubusercontent.com/197440/63380919-658a3d00-c34c-11e9-931d-867d92e7a8f2.png">

Notice how the indicator goes below the vertical center for actions without text (dashed dark red).

### Actual Behavior

☝️ 

### Expected Behavior

All indicators to be vertically aligned.

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-action.html
2. Remove `text-enabled` on any `<calcite-action>`

**Comment by asangma** [comment]
By design. Problem?

**Comment by jcfranco** [comment]
@asangma Not problem at all. Just seeking clarification.

Verified with the demo page.
