### ISSUE TITLE
Use JSDoc to have Stencil generate slot doc

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#192]
Doc for slots was manually added in #140, but there is a way to use JSDoc and have the compiler generate the doc (see https://github.com/ionic-team/ionic/blob/master/core/src/components/toolbar/toolbar.tsx#L10-L14). 

The doc should be rewritten to leverage this capability.

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
Verified
