### ISSUE TITLE
Bug: RTL calcite-tip-manager pagination icons point wrong direction

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#197]
### Summary

RTL calcite-tip-manager pagination icons point wrong direction

### Actual Behavior

Buttons should not point towards each other.

### Expected Behavior

Buttons point outward

### Reproduction Steps

1. View sample app and change html dir to rtl

![Screen Shot 2019-08-21 at 1 24 03 PM](https://user-images.githubusercontent.com/1231455/63465964-2117a380-c417-11e9-9965-8ae2ebac6c6a.png)

**Comment by pr3tori4n** [comment]
@driskull In a rtl environment, should the right-side button be `previous tip` and the left-side button be `next-tip`?

**Comment by driskull** [comment]
yep. that sounds right.

**Comment by pr3tori4n** [comment]
@driskull please verify.
