### ISSUE TITLE
Bug: Calcite-Flow Too Wide on Mobile Device

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#199]
### Summary
Flow Container bleeds off the edge of the screen. This is in portrait mode.

### Expected Behavior
Container doesn't extend off the edge of the screen.
### Reproduction Steps

1. On a mobile device, Go to: https://esri.github.io/calcite-app-components/demos/calcite-flow-item.html

### Relevant Info 
Browser: Chrome
Mobile OS: Android
Viewport: 360px by 512px

**Comment by pr3tori4n** [comment]
![image](https://user-images.githubusercontent.com/12614215/63473318-e0755580-c429-11e9-90f5-525fb5ed1b88.png)

**Comment by asangma** [comment]
I don't know if this is an issue.
The width is being set by the demo app.
```
.flow-container {
    width: 350px;
    height: 800px;
}
```

@pr3tori4n Please try removing the width rule and see if the issue persists.

**Comment by asangma** [comment]
![flow-item](https://user-images.githubusercontent.com/12503298/64570205-b9b58b00-d314-11e9-9e96-eafaf33519ec.gif)

**Comment by pr3tori4n** [comment]
@kat10140 Please verify.

**Comment by kat10140** [comment]
Verified! Closing
