### ISSUE TITLE
Bug: Scrolling in Flow Manager on Mobile is bad UX

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#200]
### Summary
Scrolling on mobile involves swiping up or down on the screen. When trying to vertically scroll the page, if the flow container takes up most of the screen, you're only able to scroll the internal container. You have to get to the very top or bottom of that inner window before you can continue to scroll up/down the page itself.
### Actual Behavior
Flow Container hijacks the vertical scroll
### Expected Behavior
There should be a safe area where a user can scroll either within the flow or on the page.
The Flow container will need to be prevented from taking up too much screen size.
### Reproduction Steps

1. On a mobile device, Go to: https://esri.github.io/calcite-app-components/demos/calcite-flow-item.html

### Relevant Info 
Browser: Chrome
Mobile OS: Android
Viewport: 360px by 512px

**Comment by kat10140** [comment]
@asangma would this be you or matt?

**Comment by driskull** [comment]
This is a non issue since there will be no scrolling when the shell takes 100% width and height.
