### ISSUE TITLE
Enhancement: Refactor Heading properties to use slotted content

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#201]
### Description
In some components, we're currently baking in heading levels in the shadow dom. The heading levels chosen are guesswork, as the location of the component in a consuming application may lead to different desired heading levels used within.

### Acceptance Criteria 
1. Developers can pass in the heading level appropriate for their content, along with the heading text via a default or named slot.

#### Out of Scope
Any non-heading elements/data.

### Helpful Details
The assumption is that headings inside a shadow dom are the same as headings outside the shadow dom when it comes to SEO and Accessibility. Any research that suggests a shadowRoot is a brand new context regarding headings would invalidate this ticket.

**Which Component:** Tip, Block
**Example Use Case:** A user wants to add a <calcite-tip> nested inside a container that has an h3 heading. They want to tip headers to be h4 tags.

**Comment by asangma** [comment]
Spoke with @mitc7862 and @jimmieego about heading in PickerItem, and we may not need it to be a heading.

**Comment by asangma** [comment]
I think we can close this?

**Comment by pr3tori4n** [comment]
Closing.
