### ISSUE TITLE
Enhancement: Switch mode for BlockSection

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#205]
### Description
Switch mode for BlockSection would result in the same expand/collapse behavior but would remove the triangle on the flex-start side and add a switch to the flex-end side.

**Which Component:**
BlockSection

### Mockups

![image-1](https://user-images.githubusercontent.com/197440/64465426-744d4f80-d0c1-11e9-8e4c-86f35f78fae8.png)

![image](https://user-images.githubusercontent.com/197440/64465425-744d4f80-d0c1-11e9-9f3b-40ed8b358774.png)

**Comment by jcfranco** [comment]
@kat10140 Can you triage this one?

**Comment by jcfranco** [comment]
@asangma Do you have an updated mockup for this?

**Comment by kat10140** [comment]
@asangma

**Comment by asangma** [comment]
Whoop! Let this one slip by.
I'll get you something more explicit than the above.

**Comment by asangma** [comment]
Image on the left shows the section on/open. Image on the right shows the section off/closed.
![Screen Shot 2019-09-18 at 9 50 23 AM](https://user-images.githubusercontent.com/12503298/65168787-1b9f8000-d9fa-11e9-9952-e3b56320e58f.png)

**Comment by asangma** [comment]
Basically it's the same as a normal section except that 
* the graphic is a switchhopefully from calcite-components

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
Verified! Closing (sorry I forgot to triage @jcfranco 🙃)
