### ISSUE TITLE
Research: floating-panel and action-pad positioning

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#206]
### Background

Currently floating-panel and action-pad have to be children for a shell-panel to be placed inside their correct slots. But if components contained inside shell-panels want to manage these themselves this is not possible.

e-mail:

I’m thinking we need to keep the slots at root level of the `calcite-shell-panel` unless we want to decouple these from the panel and rely on another positioning method.
 
That would mean that any child components of a panel would need to notify the app to update/set the `calcite-action-pad` or `calcite-shell-panel`.
 
My original thinking was that these two components would be anchored to a `calcite-shell-panel` in order to simplify positioning logic for an app developer. Maybe we can meet and brainstorm a different way if this isn’t going to work?
 
-Matt

---

Another option:  we could create a floating-panel/action-pad outside of the shadow DOM in a hidden or just empty state for each panel.

### Desired Outcome

floating-panel and action-pad can get created by any component and placed accordingly.

### Questions

- Is the `placement` of `side | over | anchor` useful for easily positioning relative to an element and panel or do we need more fine tuned placement?
- Should these two components be decoupled from the `calcite-shell-panel` and positioned relative to the `body` and another element?
- Should these two components stay coupled to the `calcite-shell-panel` but created by default outside shadowDOM.

**Comment by driskull** [comment]
Another option:  we could create a floating-panel/action-pad outside of the shadow DOM in a hidden state for each panel.

**Comment by driskull** [comment]
@asangma @jcfranco please chime in here

**Comment by jcfranco** [comment]
Would a utility similar to [`dijit/popup`](https://dojotoolkit.org/reference-guide/1.10/dijit/popup.html) fix this? That’s the only thing I can think of to reliably position elements without having to worry about their placement.

**Comment by driskull** [comment]
From meeting:

- Positioning will be more like a tooltip
- Remove slots for `action-bar` and `floating-panel` from `calcite-shell-panel`
- An app author will create the action-bar or floating panel and place it in the shell or body of the document.
- Child components will need to emit an event to notify the app to change the content of a floating panel/action pad and close other open panels/action pads as necessary
- Position logic will need to calculate and take into account scrolling or overflow positioning

I'm thinking we could have a component that just handles positioning and either the action-pad or floating panel content could be put into it.

```ts
interface CalcitePosition { // better name?
  placement: "leading" | "trailing" | "anchor";
  positionElement: HTMLElement;
  xOffset: number;
  yOffset: number;
}
```

This component could house anything so we wouldn't have to engineer positioning settings into individual components.

@jcfranco did I miss anything?

@AdelheidF @kevindoshier any concerns?

**Comment by driskull** [comment]
@asangma is the calcite team considering a tooltip component? If so, this may be able to handle what we need.

**Comment by AdelheidF** [comment]
> Child components will need to emit an event to notify the app to change the content of a floating panel/action pad and close other open panels/action pads as necessary

I thought we agreed that we don't want to do this. Didn't we say it's not so bad if two actionPads or floatingPanels are open at the same time? The user can close them. 
Could the child component create that actionPad or floatingPanel anywhere in the document and remove it when it gets destroyed? Tooltips don't need to be created by the app either.

**Comment by kevindoshier** [comment]
I agree with @AdelheidF is there a technical reason why the app needs to create and manage the floating panel/action pad for the component instead of the component doing this?  How would scene viewer consume the popup config which in the current design uses a floating window?

**Comment by AdelheidF** [comment]
Looks good. Using it now for floating panel and action pad.
