### ISSUE TITLE
Bug: Action-bar text in mobile

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#210]
### Summary
When expanded, `action-bar` text in all mobile ios browswers is showing up vertical rather than horizontal.  

Matt says:  this is because of the `max-width: 15vw;` in the `calcite-action-bar.scss`

### Actual Behavior
![actonbar ](https://user-images.githubusercontent.com/48069902/63614310-8c887f00-c597-11e9-8399-8571e67092ae.png)

### Expected Behavior
horizontal expanded text

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-action-bar.html on your mobile device and expand the action bar.

**Comment by kat10140** [comment]
This is also happening similarly in desktop when the browser is resized. 
![Screen Shot 2019-08-23 at 11 23 01 AM](https://user-images.githubusercontent.com/48069902/63614682-82b34b80-c598-11e9-8590-1b222fb0b327.png)

**Comment by asangma** [comment]
@kat10140 Might need this to be Abracadaniel.

**Comment by asangma** [comment]
FYI. I think this might also be an issue Action.

**Comment by kat10140** [comment]
> FYI. I think this might also be an issue Action.

wut
