### ISSUE TITLE
Bug: Ellipses action icon aligned wrong in flow iOS

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#211]
### Summary
Alignment is wrong on click of action icon for flow in iOS Safari. 

### Actual Behavior
![63470247-fe8a8800-c420-11e9-8730-5ecb92c836c1](https://user-images.githubusercontent.com/48069902/63615260-c2c6fe00-c599-11e9-90f3-924d20dee190.jpeg)

### Expected Behavior
symmetry 

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-flow.html on Safari iOS device and click the ellipses.

**Comment by pr3tori4n** [comment]
Closing since no longer needed.
