### ISSUE TITLE
Bug: Nav bar doesn't span full width on iOS

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#213]
### Summary
Nav bar doesn't span full width on iOS

### Actual Behavior
![Image from iOS](https://user-images.githubusercontent.com/48069902/63622019-602a2e00-c5aa-11e9-8670-cfadbe98f08d.png)

### Expected Behavior
spaaaaan

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/ on mobile device. Look at nav.

**Comment by asangma** [comment]
@kat10140 I dunno if I'm the one to fix this one.

**Comment by driskull** [comment]
Gonna assign to harry since its his nav design.

**Comment by pr3tori4n** [comment]
@kat10140 Please verify.

**Comment by kat10140** [comment]
@pr3tori4n this doesn't seem to be working in landscape mode, and in portrait, the nav doesn't show up at all

**Comment by pr3tori4n** [comment]
@kat10140 can you let me know what the screen width is in landscape mode? I have the desktop nav beginning once the screen size is 600px. We may need to increase that.

Can you take a screenshot and show me what you're seeing in portrait mode?

**Comment by kat10140** [comment]
@pr3tori4n- iPhone 6s res is 750 x 1334
Here are screenshots of both right now:
![Image from iOS (2)](https://user-images.githubusercontent.com/48069902/65186557-b316ca00-da1e-11e9-8223-6e3f3c42b4d8.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/48069902/65186558-b5792400-da1e-11e9-9837-c542c5d7ece4.png)

**Comment by kat10140** [comment]
@asangma can you comment on this for landscape?  you do have to scroll on landscape. should we just have a hamburger menu for landscape mode as well?

**Comment by driskull** [comment]
Yeah, we need to redesign the nav. We're running out of room :)

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified. Looks great!

**Comment by kat10140** [comment]
it wont let me change labels??
