### ISSUE TITLE
Bug: removing all tips tip-manager

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#214]
### Summary
Removing all tips should handle gracefully.

If tip-manager doesn't have a tip, it needs a developer empty state. So it should empty but be min-height. (it should have a min height)

If not more than 1 tip, do not show pagination.

### Actual Behavior
![Screen Shot 2019-08-23 at 1 36 42 PM](https://user-images.githubusercontent.com/48069902/63622271-10983200-c5ab-11e9-9635-844c3565618b.png)

### Expected Behavior
No line across- empty with min height and buttons removed from dom.

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html. Click 'remove last tip' until all are gone. 

### Relevant Info 
all browsers.

**Comment by pr3tori4n** [comment]
@kat10140 @asangma If I put a min-height, and nothing else, then it's just an empty-white box when there are no tips in there. It looks broken still. 
![image](https://user-images.githubusercontent.com/12614215/63625006-27428700-c5b3-11e9-848f-b4bc493a3f1e.png)

I have 2 competing suggestions.
1. We could add a message like "No tips available".
2. We hide the tip manager completely.

Does one of these sounds good, or is there something else you'd like me to do?

**Comment by pr3tori4n** [comment]
Branch: `hrobbins/bug-tip-manager-no-tips-214`

**Comment by kat10140** [comment]
@driskull @asangma Matt- I think you said to keep it min height with just an empty white box if I'm remembering correctly. I like Harry's suggestion of adding a 'no tips' message

**Comment by driskull** [comment]
I'm not sure we need a no tips message because then we have to add a prop to take in that text.

@asangma said that having no tips isn't a valid use case anyway so we can just leave it empty.

**Comment by kat10140** [comment]
that's right

**Comment by pr3tori4n** [comment]
> @asangma said that having no tips isn't a valid use case anyway so we can just leave it empty.

In that case would it be better to just hide it completely? I'm having trouble seeing the benefit of keeping it around with a min-height.

**Comment by asangma** [comment]
No empty state. Retain the TipManager if it's set to be visible.

UX shouldn't have a TipManager with no tips, but the dev may be in the middle of building an app and could benefit from know where/how the TipManager will work without having to have tips in there.

**Comment by pr3tori4n** [comment]
Ok. PR opened for review.
https://github.com/Esri/calcite-app-components/pull/241

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified
