### ISSUE TITLE
Bug: calcite-action tapping behavior

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#216]
### Summary
Tapping text actions does not change color, white ones do.

(note: on hover on mac/chrome the white changes to off white, though not when clicked- not sure if this behavior is supposed to happen or not)

### Actual Behavior
Tapped blue action
![63472309-8030e480-c426-11e9-872a-37216832162f](https://user-images.githubusercontent.com/48069902/63623927-d2e9d800-c5af-11e9-94e6-8ed62c270abb.jpeg)

Tapping white action 
![63472307-8030e480-c426-11e9-80e6-140bbdc9189a (1)](https://user-images.githubusercontent.com/48069902/63623937-d67d5f00-c5af-11e9-8198-acf2a65e9a7a.jpeg)

### Expected Behavior
No changey color

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-action.html on your mobile device. Click white action.

**Comment by asangma** [comment]
@kat10140 Assigning to you to try and reproduce.

**Comment by jcfranco** [comment]
Issue moved to [Esri/calcite-components #1082](https://github.com/Esri/calcite-components/issues/1082) via [**ZenHub**](https://www.zenhub.com/)
