### ISSUE TITLE
Bug: Block content styling

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#217]
### Summary
- Padding on 'sectionless' block content.

### Actual Behavior
![63472250-60012580-c426-11e9-8ac8-658752beb42c](https://user-images.githubusercontent.com/48069902/63624260-b8fcc500-c5b0-11e9-890d-f758f680fb73.jpeg)
![63472208-44961a80-c426-11e9-9a72-b341b6d1754b](https://user-images.githubusercontent.com/48069902/63624266-bac68880-c5b0-11e9-9f0e-b41760976416.jpeg)

### Expected Behavior
to be sexy

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-shell.html. Click on floating panel.  Click on any block heading.

**Comment by asangma** [comment]
@kat10140 INSTARLED!

**Comment by kat10140** [comment]
Lewkin gewd!
