### ISSUE TITLE
Bug: tip-manager spacing weird 

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#218]
### Summary
Spacing looks different:

Chrome 👇
<img width="1669" alt="63472058-d3566780-c425-11e9-930d-e955b0351b04" src="https://user-images.githubusercontent.com/48069902/63624443-2f012c00-c5b1-11e9-879d-c0b1e83c58e0.png">

Edge 👇
<img width="1317" alt="63472059-d3566780-c425-11e9-9ec4-7e63b5f6a053" src="https://user-images.githubusercontent.com/48069902/63624454-3b858480-c5b1-11e9-9d0c-a5d7110766c6.png">

**VM Win 10 + FF (68)**
- No focus outlines
`calcite-tip-manager`
- Same spacing issue mentioned above.

**VM Win 10 + Chrome**
`calcite-tip-manager`
- Same spacing issue mentioned above.

### Reproduction Steps

1. go to https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html

**Comment by kat10140** [comment]
@asangma made any progress on this?

**Comment by asangma** [comment]
I need help understanding the issue.

**Comment by kat10140** [comment]
actually the spacing seems to be fine/consistent on my windows machine on all browsers. @jcfranco i believe you found this bug at the testing party, any comment?

**Comment by jcfranco** [comment]
Note the text alignment is off in Edge. There is a different font-family being used there, so I'm not sure if that's the culprit.

**FF/Chrome/Safari**

<img width="1659" alt="Screen Shot 2019-10-02 at 1 07 14 PM" src="https://user-images.githubusercontent.com/197440/66077957-ea54a300-e515-11e9-8eaa-9fcf562f6ee7.png">

**Edge**

<img width="1653" alt="Screen Shot 2019-10-02 at 1 07 31 PM" src="https://user-images.githubusercontent.com/197440/66078014-05271780-e516-11e9-893c-5401c9ad0abb.png">

**Comment by kat10140** [comment]
OH i see what you mean now. I don't think it's a font thing bc Chrome/FF/Edge are all the same arial looking font on Windows, but Edge does have that different alignment.

**Comment by asangma** [comment]
Looks like Edge *is* getting the wrong font tho.

**Comment by kat10140** [comment]
Ok, all windows browsers look like they're getting that same font as Edge is all i'm sayin, so we'll have to think about those as well

**Comment by jcfranco** [comment]
Issue moved to [Esri/calcite-components #1081](https://github.com/Esri/calcite-components/issues/1081) via [**ZenHub**](https://www.zenhub.com/)
