### ISSUE TITLE
Enhancement: Add events to notify app when panel size has changed

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#223]
### Description

Add events to notify app when panel size has changed

### Acceptance Criteria 

There are events to notify an app when these properties change

#### Desired New Behavior

There are events to notify an app when these properties change

### Relevant Info 

The application knows when the size of a shell panel has changed. Things that can effect its width are:

- collapsed
- action bar text showing

**Comment by kat10140** [comment]
@driskull how do i verify this?

**Comment by driskull** [comment]
@kat10140 you can test the `calciteActionBarToggle` event on the `calcite-action-bar` and the `calciteShellPanelToggle` on the `calcite-shell-panel`.

**Comment by kat10140** [comment]
Verified
