### ISSUE TITLE
Bug: shell display on iPad

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#231]
### Summary
Shell demo on iPad is just slightly off with padding on the right side. 

![IMG_0028](https://user-images.githubusercontent.com/48069902/63723565-9cf46000-c80a-11e9-841f-29b82da55b68.PNG)

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-shell.html on iPad, notice the demo is slightly offcenter & user has to scroll

### Relevant Info 
iPad chrome

**Comment by driskull** [comment]
resolved with full width demo example.
