### ISSUE TITLE
Add loading prop to all components

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#237]
Add a loading property to all calcite app components. 

Alan can then add styling as needed for da ~ lOaDiNG StAtE ~

**Comment by jcfranco** [comment]
Are we sure we don't want to introduce a utility or component that handles this instead of adding a loading property/state to all components?

Similar examples:

https://ionicframework.com/docs/api/loading
https://jscore.esri.com/javascript/3/jsapi/esri.dijit.util.busyindicator-amd.html

**Comment by asangma** [comment]
@jcfranco I'm cool with that. Can I assign it to you for that? I would just need to know how to style stuff.

**Comment by driskull** [comment]
Shouldn't each component that needs it have a `loading` property that a user can toggle loading on? 

Internally, it should use the `calcite-loader` or `calcite-progress` in some way.

**Comment by driskull** [comment]
duplicate of #248. closing
