### ISSUE TITLE
Bug: In firefox, using the itemBrowser in a calcite-panel doesnt show overflow correctly

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#239]
### Summary
In firefox, using the itemBrowser in a calcite-panel doesnt show overflow correctly

if i set a style of min-height:0 on this element in the calcite-app-components it seems to fix it

https://github.com/Esri/calcite-app-components/blob/a027414e148a37361e40a9d970f2dea19e4681ea/src/components/calcite-shell/calcite-shell.tsx#L64

### Reproduction Steps

1. Using firefox, Go to https://devext.arcgis.com/apps/mapviewer and signin with devext account
2. Click add layer

**Comment by driskull** [comment]
Seems to be functioning now.
