### ISSUE TITLE
Research: Improve version update and publishing process

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#244]
### Background

The current process for creating a release still requires a bit of manual work (running NPM scripts to prepare the distributable and pushing to GH, and then releasing on GH with proper labels and change notes). This is going to be more notable if we start updating the version more frequently.

### Desired Outcome

Introduce a simpler/automated way to create releases.

cc @kat10140 @pr3tori4n 

### Additional Info

Related work: #82 #255

**Comment by jcfranco** [comment]
@pr3tori4n Can you verify on the next release?

**Comment by pr3tori4n** [comment]
@jcfranco sure np.

**Comment by pr3tori4n** [comment]
Verified
