### ISSUE TITLE
Question: Should we use a custom attribute for direction related CSS selectors?

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#245]
### Question
We have a utility class we're using. Would it be better to use a custom attribute?
### Helpful Details

**Topic:** right-to-left styling

**Context:** We need a selector to use for direction specific styling.

My two cents: a custom attribute would be more flexible, since it's a bad practice to add a class to the <Host> element.

**Comment by driskull** [comment]
IMO an extra dom node for presentation in the shadow DOM is less intrusive than a custom attribute on the custom element that would be documented and exposed to the user in the light DOM.

**Comment by pr3tori4n** [comment]
It wouldn't need to be an @Prop so it wouldn't be documented.
The only people who would see this are developers looking at the dev console in the browser. That a big deal?

**Comment by driskull** [comment]
> It wouldn't need to be an @prop so it wouldn't be documented.

If it doesn't use a prop, then it isn't a valid custom attribute and we would be invalidly adding it to the node.

> The only people who would see this are developers looking at the dev console in the browser. That a big deal?

If we expose it, they may set it and we wouldn't want them to.

> Additional nodes in the DOM decrease page performance - so anywhere we can trim them is a win in my eyes.

Could the utility class be set on a node that already exists? or on multiple nodes if necessary?

**Comment by pr3tori4n** [comment]
> If it doesn't use a prop, then it isn't a valid custom attribute and we would be invalidly adding it to the node.

Maybe there's some confusion here. What I'm saying is we add the property in the render function. It wouldn't be configurable by the implementer. That would still be a valid custom attribute, in the context of web components.

> Could the utility class be set on a node that already exists? or on multiple nodes if necessary?

In this case there's not a simple alternative. An alternate attribute is the simplest workaround. Trying to keep it a class is more difficult.

@jcfranco you have any thoughts?

**Comment by driskull** [comment]
>  That would still be a valid custom attribute, in the context of web components.

It wouldn't, because it wouldn't be defined on the web component.

> In this case there's not a simple alternative. An alternate attribute is the simplest workaround. Trying to keep it a class is more difficult.

I disagree. This is the use case for a class since it is just used for a selector, not an attribute.

**Comment by jcfranco** [comment]
@pr3tori4n Do you have some pseudocode you can share? I'm having trouble visualizing your proposal.

**Comment by driskull** [comment]
What's the status of this?

**Comment by pr3tori4n** [comment]
backburner for a bit. I'll open a PR soon.

**Comment by pr3tori4n** [comment]
@jcfranco 
https://github.com/Esri/calcite-app-components/pull/285

**Comment by pr3tori4n** [comment]
@jcfranco any update?

**Comment by driskull** [comment]
This is something that should be handled internal to the component with a class.

- We shouldn't pollute the host with attributes that are not apart of the component's API.
- Attributes are for configuring elements or adjusting their behavior. This is just being used as a selector.

**Comment by jcfranco** [comment]
Thanks for the demo PR @pr3tori4n!

I think we should look at the pros/cons for each approach (please correct me if I'm wrong or if there's something I missed):

#### Custom attribute

*pros*

- simplifies the util CSS since it only targets the host

*cons*

- needs to be set on the host
- needs to use non-standard custom attribute
- may cause some confusion `<calcite-foo dir=rtl rtl />`
  - can be mixed up w/ `dir`
  - not quite clear what the difference is between both
  - which one wins?

#### Custom class

*pros*

- meant to be used internally although it could be set on the host too (StencilJS already adds `hydrated`).

*cons*

- needs to be applied to a container within host

---

With this in mind, I don't see a lot of gains from switching.

**Comment by jcfranco** [comment]
WRT setting stuff on the host, I think there are valid use cases. Ionic components do this. Here's an example where a component sets [classes, role and aria-attributes on the host](https://github.com/ionic-team/ionic/blob/8a88dd25b66e72f30d2d3325ac3d3abe53396f74/core/src/components/checkbox/checkbox.tsx#L150-L163).

**Comment by driskull** [comment]
I'm ok with leaving the `role/aria-` attributes but a best practice for web components is to not self apply classes.

**Comment by jcfranco** [comment]
I'd prefer not applying classes too. I just wanted to note that Stencil/Ionic already do this.

**Comment by pr3tori4n** [comment]
> * needs to be set on the host
> * needs to use non-standard custom attribute

I don't really see how these are cons. Is there a measurable negative impact these introduce I"m not seeing? What's the harm in having a custom attribute on the host?

Main pro of custom attribute is:
* It can go on the host, while adding a class is to the host is an anti-pattern.
Other pro:
* Avoids the creation of additional HTML elements.

> * meant to be used internally

This is a limitation, not really a pro. The custom attribute could go on elements other than the host as well - it's main benefit is that it can _also_ go on the host.

**Comment by driskull** [comment]
> I don't really see how these are cons. Is there a measurable negative impact these introduce I"m not seeing? What's the harm in having a custom attribute on the host?

- It's confusing to the user.
  - User shouldn't be able to modify it or know about it.
  - competes with `dir`.
  - We shouldn't pollute the host with custom attributes that are not apart of the component's API.
- It isn't a valid custom attribute. It won't be added to `observedAttributes` on the element or documented in any fashion. 

> It can go on the host, while adding a class is to the host is an anti-pattern.

- Adding a custom attribute that isn't defined as one on the custom element is also an anti-pattern. 
- Using a custom attribute just as a selector and not as configuration or behavior is an anti-pattern. The purpose for it is to adjust styling, which is what a class is for. Attributes are for behavior/configuration.

These issues have been reiterated a few times. Can we please move on from this topic and proceed?
