### ISSUE TITLE
Enhancement: PickList support hierarchy

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#252]
![image](https://user-images.githubusercontent.com/12503298/64551827-d341dd00-d2ea-11e9-8163-fa5d1a634609.png)

### Description
PickList would be able to display PickItems that have children. 
This is related to what would be the "layer picker" in Map Viewer Beta
![image](https://user-images.githubusercontent.com/12503298/64551967-1b60ff80-d2eb-11e9-856b-ffe4de1dd1b9.png)

### Acceptance Criteria 
Standard checkbox hierarchy behavior and hooks to style children and parents appropriately.

#### Desired New Behavior
- mixed state for parent checkbox when some of children are checked
- parent is unchecked when all children are unchecked
- checking a parent with mixed or unchecked state results in checked state (includes all children)
- checking a parent with a checked state (meaning all children are selected) results in unchecking parent and all children.

#### Desired Change to Look and Feel
Need a mix-state checkbox.

#### Out of Scope
ValueList

### Relevant Info 
Map Viewer Beta will need this.

### Helpful Details

**Which Component:**
PickList

**Example Use Case:** User wants to switch layers from the right panel in the Map Viewer Beta without having to go to the LayerList in the left panel.

**Comment by asangma** [comment]
@driskull Will the standard checkbox hierarchy behavior work with how our GIS layers work?

**Comment by driskull** [comment]
@asangma I'm not sure. Is this just for selection? If so I think so. If its for visibility than probably not.

**Comment by asangma** [comment]
@driskull 100% for selection...nothing else.

**Comment by driskull** [comment]
So this will need a `calcite-pick-list-group`?

**Comment by pr3tori4n** [comment]
There's already a group component. We can probably enhance that to support something like this.

**Comment by asangma** [comment]
@pr3tori4n 
Thinking more on this, it might mean that a `pick-list-item` would need to accept a `pick-list-group`?

**Comment by pr3tori4n** [comment]
Yea...we may need another grouping mechanism. Let me play with it and see what we can do with what we have.

**Comment by pr3tori4n** [comment]
@kat10140 This enhancement is a complex one. I think it deserves a kick-off meeting where I can gather some more details from ya'll on how this should work.

**Comment by kat10140** [comment]
sure

**Comment by kat10140** [comment]
In standup today, we decided that this isn't super high priority so will come back to this and schedule later

**Comment by pr3tori4n** [comment]
k. Unassigning myself until this is ready to be worked on.

**Comment by kat10140** [comment]
closing until we get new reqs
