### ISSUE TITLE
Bug: CalciteTipManager tabindex property should not be used

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#258]
### Summary

Bug: CalciteTipManager tabindex property should not be used.

The @Prop() name "tabindex" is a reserved public name. Please rename the "tabindex" prop so it does not
           conflict with an existing standardized prototype member. Reusing prop names that are already defined on the
           element's prototype may cause unexpected runtime errors or user-interface issues on various browsers, so
           it's best to avoid them entirely.

### Relevant Info 

```
[ WARN  ]  Build Warn: src/components/calcite-tip-manager/calcite-tip-manager.tsx:61:28
           The @Prop() name "tabindex" is a reserved public name. Please rename the "tabindex" prop so it does not
           conflict with an existing standardized prototype member. Reusing prop names that are already defined on the
           element's prototype may cause unexpected runtime errors or user-interface issues on various browsers, so
           it's best to avoid them entirely.

     L61:    @Prop({ reflect: true }) tabindex = 0;
```

**Comment by pr3tori4n** [comment]
@driskull installed please verify.
