### ISSUE TITLE
Bug: A shell with only a contextual panel displays on the incorrect side

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#259]
### Summary

Bug: A shell with only a contextual panel displays on the incorrect side

### Actual Behavior

The contextual panel appears on the left side of the shell

### Expected Behavior

A user must have a primary panel. In the primary panel, they can specify a `layout` of `trailing`.

### Reproduction Steps

1. Open the shell demo page
2. Remove the primary panel node

**Comment by driskull** [comment]
cc @AdelheidF

**Comment by driskull** [comment]
@asangma is it a valid use case to just have a `contextual` panel? or should we just close this as `known issue` or `invalid`?

**Comment by driskull** [comment]
cc @kellyhutchins

**Comment by kellyhutchins** [comment]
Awesome! I'll test it out in my app

**Comment by driskull** [comment]
You'll have to wait for our next release @kellyhutchins :(

**Comment by kat10140** [comment]
I'm still seeing it on the left side @driskull :/

**Comment by driskull** [comment]
@kat10140 you must have a primary panel. In the primary panel, you can specify a layout of trailing.

**Comment by kat10140** [comment]
ok in the comment above we have:
``` Expected Behavior
The contextual panel should appear on the right side if just a contextual panel is used without a primary panel. ```

**Comment by driskull** [comment]
Updated issue! Thanks

**Comment by kat10140** [comment]
Mines still not flip flopping 😫

**Comment by kat10140** [comment]
![Screen Shot 2020-01-06 at 2 52 45 PM](https://user-images.githubusercontent.com/48069902/71854825-37f02700-3094-11ea-9f9b-72fd1ee0219e.png)
i see it's technically working but the styling looks wack

**Comment by driskull** [comment]
Can you replecate `/demos/shell/demo-app-full-window-reversed.html`?

**Comment by kat10140** [comment]
![Screen Shot 2020-01-06 at 2 57 35 PM](https://user-images.githubusercontent.com/48069902/71855071-e7c59480-3094-11ea-80e2-21a321fa13c4.png)

**Comment by driskull** [comment]
@kat10140 you may need to do an npm install and restart the build

**Comment by kat10140** [comment]
still doing the same weirdness 🤷🏼‍♀️

**Comment by driskull** [comment]
@kat10140 can you share the HTML you're using? Does the demo `/demos/shell/demo-app-full-window-reversed.html` look ok?

**Comment by kat10140** [comment]
yah it looks fine otherwise! i was deleting the contextual panel, then changing the primary panel layout property to 'trailing'
```
<calcite-shell-panel slot="primary-panel" layout="trailing" detached="" class="hydrated">
       ....    
 </calcite-shell-panel>
```

or in the reversed case, changing `trailing` to `leading`

**Comment by driskull** [comment]
If you're going to modify the layout after initialization, you'll also need to modify the action-bar to be trailing.

**Comment by kat10140** [comment]
the action bar actually automatically seems to change to"trailing" in the sense that it moves to the right (in the full window app). in the reversed, it looks fine when i just delete the contextual panel all together, everything stays put. i'll mark as verified
