### ISSUE TITLE
Question: Height rules for "extra" divs?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#260]
### Question
Our apps are sometimes placing multiple things inside e.g. **calcite-shell-panel**. They do this by returning a single div with the multiple things inside.

This often causes a **calcite-flow** to not be the full height of the panel. Should we do stuff like 

**calcite-shell-panel.scss**

```
::slotted(*) {
  height: 100%;
}
```

Or maybe a helper/utility class 
```
::slotted(.your-extra-div) {
  height: 100%;
}
```

@jcfranco @driskull @pr3tori4n @kat10140 

cc @AdelheidF

**Comment by driskull** [comment]
> They do this by returning a single div with the multiple things inside.

They shouldn't do that or they should set that div to 100% height.

If they do need to create a div, can't they add a common class on it for 100% height?

I don't think we wnat to mess with the `::slotted()` selector for this.

**Comment by AdelheidF** [comment]
OK, I will set height to 100%.

**Comment by asangma** [comment]
Understood.
My thought is it seems like the "return multiple components inside a div" will be a common thing. But if we don't feel like we need to have a selector that accommodates that, aight.

**Comment by driskull** [comment]
It seems like a component that just sets a div to 100% height would be overkill. I think just a common class within the application would get the job done.

**Comment by asangma** [comment]
K. I was also thinking a class, but yeah, I guess that's outside of general component practices.

Thanks! Closing
