### ISSUE TITLE
New Component: FAB

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#262]
### Description
A button for adding new things. It could be an extension or configuration of Action.

#### User Stories
As a map author I want easy access to the "add layer" workflow. I want to be able to do this from within the LayerList but I don't want to scroll all the way to the bottom, and having it at the top is weird.

### Acceptance Criteria
* button can be set to "float" at the bottom of the parent element.
  - and have appropriate styles
* button can be inline
  - and have appropriate styles
* button is just shows the + icon by default
* button shows label on :hover | :focus
* button can be set to show label all the time (text-enabled)

### Desired Behavior
![00 init](https://user-images.githubusercontent.com/12503298/64740837-7e999000-d4ab-11e9-9afe-3f5c28a7641a.png)

#### Floaty!
![05 floating 00 idle](https://user-images.githubusercontent.com/12503298/64740856-8c4f1580-d4ab-11e9-9530-8614935454e1.png)
![05 floating 05 hover](https://user-images.githubusercontent.com/12503298/64740874-9a9d3180-d4ab-11e9-8376-729ec6e25829.png)

#### Inline
![20 inline 00 idle](https://user-images.githubusercontent.com/12503298/64740896-a983e400-d4ab-11e9-85ed-cca5d5d5cc61.png)
![20 inline 05 hover](https://user-images.githubusercontent.com/12503298/64740898-a983e400-d4ab-11e9-8792-8bb729678f98.png)

### Helpful Details
BasemapLayerList, LayerList, SmartMapping, etc. can all benefit from this.

**Comment by driskull** [comment]
@asangma it seems like this could just be a different style of `calcite-button` maybe?

The positioning isn't handled by the button itself, right?

**Comment by asangma** [comment]
@driskull I think it could be a version of the `calcite-app-action`. It has the similar behavior of icon-only and icon+text (text-enabled).

We could possibly wrap calcite-app-action.

It also has the inline mode and FAB mode. As you suggested, it might be cool to have it automatically switch modes depending on how much content there is in its container, i.e. scrolling.

For now though, it might be good to just get a version out there that can be set manually by the developer.

**Comment by asangma** [comment]
@kat10140 Assigning to you also until we have a designated dev.

**Comment by driskull** [comment]
@asangma we might not need a new component here.

We could

- Add an option to the action to auto expand on focus/hover
- Position the calcite-action using sticky positioning.

**Comment by driskull** [comment]
Sticky icky: https://medium.com/@elad/css-position-sticky-how-it-really-works-54cd01dc2d46

https://codepen.io/elad2412/pen/MZZVjw

**Comment by asangma** [comment]
Sticky doesn't love `flex`.

**Comment by asangma** [comment]
If we want a dynamic version of this that auto-switches from an inline _style_ to a sticky one (i.e. bigger and with a bg-color & box-shadow) we'll prolly need a partial js solution.

**Comment by driskull** [comment]
If we want an action that's bigger, we should be able to do it with just a class. Just like if you wanted a bigger button or a button with a different background.

**Comment by kat10140** [comment]
Meeting notes 10/1/19:
- decide if we want to start bringing properties/modified styles in
- right now calcite comps is doing that with size color theme. 
- should we allow properties to affect styling or go with classes?
  - do we fall in line with what calcite comps is doing?

https://github.com/Esri/calcite-components/tree/master/src/components/calcite-switch#properties

**Comment by driskull** [comment]
We need to decide if we want to allow styling via attributes/properties. It would allow for more consistency without having to do anything at a framework/application level but will make it more difficult for a user to override styles.

The theme property is a little different because it only modifies CSS variables for color and not sizing or positioning differently.

Part of me thinks that consistency would be good for sizing and positioning but part of me also thinks that these attributes should alter behavior, functionality or layout. These would just alter presentation. It then makes it harder for a user to override styles because they have to consider the differences these attributes do to the default styling.

> Elements in HTML have attributes; these are additional values that configure the elements or adjust their behavior in various ways to meet the criteria the users want.

**Comment by driskull** [comment]
So we would be adding Properties to the `calcite-action` to make it:

- Sized bigger (Maybe follow `calcite-component` sizing?)
- Pill shaped

We already added a `textDisplay` Property to make it:

- Auto show text on hover/focus (needs animation styling still)

@asangma is that correct?

**Comment by driskull** [comment]
From what we discussed in the meeting:

- New component that can act as a FAB.
  - extends action
  - is bigger
  - is rounded or pill shaped
- Action doesn't need sizing, we just need a FAB

Need to figure out:

- Discuss if `calcite-action` needs textDisplay or if its just the nature of the FAB.
  - Seems like we can leave it on Action as its nice to have.
- FAB
  - Does it need a size option?? (google fab has sizing option) [here](https://material.io/components/buttons-floating-action-button/#)
- Discuss if its sticky or not. Google FAB is always floating.

@kat10140 can you set something up?

cc @asangma

**Comment by driskull** [comment]
Talked to @asangma ...

- Will create `calcite-fab` component.
- Alan will style it bigger and pill shaped
- Alan will position it absolute. If it needs to be sticky that could change if necessary.

**Comment by driskull** [comment]
@asangma do we want the `calcite-fab` to internally use the `calcite-action`?

If we do, we need to add a prop to scale the `calcite-action` to be bigger and a way to make it `pill shaped`.
If we don't, we need to implement the showing text on hover/focus in the `calcite-fab` as well.

Thoughts?

**Comment by julio8a** [comment]
@kat10140 move to calcite-components.
