### ISSUE TITLE
Create calcite-panel component and use it within calcite-flow-item

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#265]
### Description

Create `calcite-panel` component and use it within `calcite-flow-item`

`calcite-panel` component that has the following:

- Named slot for leading header button
- Named slot for header content
- Named slot for trailing header button
- Generic slot for content
- Named slot for footer content

#### Desired New Behavior

- Create `calcite-panel` component that is dismissible
- Remove `calcite-shell-floating-panel
- Use `calcite-panel` within `calcite-flow-item`
- Add a `calcitePanelDismissedChange` event to `calcite-panel`
- Escape key on `calcite-panel` should fire dismissed event

**Comment by driskull** [comment]
@asangma do we want a separate panel for this or would it be better if a user used the `calcite-flow-item` here and put a close button as the menu action?

Just thinking about consistency and how this is different

**Comment by asangma** [comment]
That might be a good idea.
`flow-item`'s footer is optional, but the heading is currently centered. If we can restyle it so that the heading aligns flex-start when it's the first flow, this could work.

**Comment by asangma** [comment]
But then devs would need to know to use a `flow-item` for this case yeah? Seems a bit unintuitive and also could lead to a lot of hand-rolled "floating panels".

**Comment by driskull** [comment]
>  Seems a bit unintuitive and also could lead to a lot of hand-rolled "floating panels".

Yeah. 

Maybe I can just have the two of them share a functional component so they are at least consistent in their design and architecture.

**Comment by driskull** [comment]
Thought about this a little more. I think I want to create a more generic `calcite-panel` component that has the following:

- Header
- Heading
- Named slot for leading header button
- Named slot for trailing header button
- Generic slot for content
- Named slot for footer content

Then the `calcite-flow-item` could use this internally.

For the "floating-panel" we could use the generic `calcite-panel` or we could have a `calcite-dismissible-panel` that uses it internally and adds a close button automatically.

We can discuss at the meeting Friday or here.

**Comment by asangma** [comment]
Do we need the **leading header button**?

**Comment by driskull** [comment]
> Do we need the leading header button?

Yes, for the back button on the flow item.

**Comment by asangma** [comment]
Oooohhh...nice.

**Comment by driskull** [comment]
@asangma installed. Can you double check CSS is good?

**Comment by asangma** [comment]
Whoa...oldie. But a goodie.
