### ISSUE TITLE
Enhancement: PickList Styles

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#268]
### Description
Add styles for the PickList and it's child components.
### Acceptance Criteria 
- [ ] PickList is styled
- [ ] PickListItem is styled
- [ ] PickListGroup is styled
#### Desired Change to Look and Feel
* Whatever Alan wants.
#### Out of Scope
* ValueList

**Comment by asangma** [comment]
MURGLED!
@kat10140 Assigning to you to for UI QA.

**Comment by kat10140** [comment]
🤙🏼Closing
