### ISSUE TITLE
Bug: PickList preselected items aren't sent in the event emitter

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#274]
### Summary
If a list is configured with pre-selected items, then they are not part of the internal state.
### Actual Behavior
Preselected items don't get added to the list of selected items.
### Expected Behavior
Preselected items get added to the list of selected items on initial load.
### Reproduction Steps

1. Setup a PickList with some of the items having the selected attribute.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified!
