### ISSUE TITLE
Bug: TipManager direction property is being used as a className

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#276]
### Summary

Bug: TipManager direction property is being used as a className

https://github.com/Esri/calcite-app-components/pull/270/files#diff-5920fe4ed9a333d0281e2bb47b7c0e79L252

### Expected Behavior

Class object is used for classnames.

**Comment by pr3tori4n** [comment]
@driskull did you fix this?

**Comment by driskull** [comment]
yes

**Comment by driskull** [comment]
@pr3tori4n I assigned it to you for verification

**Comment by driskull** [comment]
JC can you verify?

**Comment by jcfranco** [comment]
Verified on https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html. Inspected shadow DOM and direction is no longer applied as a class.
