### ISSUE TITLE
Enhancement: Calcite value list needs an event for re-ordering

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-app-components#278]
### Description
Calcite pick list needs an event for re-ordering

### Acceptance Criteria 
Client needs to know when fields were re-arranged, and maybe what was changed

#### Desired New Behavior
New event: calcitePickListOrderChange

**Which Component:**
calcite pick list

**Comment by pr3tori4n** [comment]
@dhrumil83 what do you envision as the trigger for this event? Is this for drag and drop?

**Comment by dhrumil83** [comment]
@pr3tori4n yes. drag and drop to re-order fields.

**Comment by pr3tori4n** [comment]
Ok. Can you elaborate on your use case? Re-ordering with drag and drop won't affect selection order - so I want to make sure selection ordre isn't something you're expecting a change in.

**Comment by asangma** [comment]
pick-list shouldn't allow re-ordering...unless you're talking about sorting based on a value.

**Comment by pr3tori4n** [comment]
@asangma This request came in before the split. I'll update the issue title. This is for drag and drop on value list.

**Comment by asangma** [comment]
cool cool

**Comment by kat10140** [comment]
Verified and closin
