### ISSUE TITLE
Enhancement: Add a disabled state to PickList Items

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#280]
#### Desired New Behavior
* Disabled items in the pick-list should not be clickable.
#### Desired Change to Look and Feel
* disabled items in the pick list should gray out
### Relevant Info 
This is a request from Adelheide.

### Helpful Details

**Which Component:** `<calcite-pick-list-item>`
**Example Use Case:** A user wants to allow multi-select, but only one of a type can be selected so they want to disable others.

**Comment by pr3tori4n** [comment]
@kat10140 Please verify.

**Comment by kat10140** [comment]
@pr3tori4n how are the `calcite-pick-list-items` disabled? I don't see a prop or anything

**Comment by kat10140** [comment]
Looks like the state is working, though the 'graying out' isn't.  See gif below @pr3tori4n @asangma 

![pick list item disabled state](https://user-images.githubusercontent.com/48069902/66768331-30d7c500-ee67-11e9-9b67-cf502c514efa.gif)

**Comment by kat10140** [comment]
Nevermind. This is working on the demo page, but not on my local @asangma @pr3tori4n. 
Verified.

**Comment by kat10140** [comment]
Alan will work on the style here https://github.com/Esri/calcite-app-components/issues/361
