### ISSUE TITLE
Enhancement: CalciteFloatingPanel needs a maxheight defined

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#287]
### Description

Enhancement: CalciteFloatingPanel needs a maxheight defined

### Helpful Details

When the window height is small the calcite-floating-panel doesn't scroll and gets cut off.

**Comment by driskull** [comment]
![floating-panel-responsive](https://user-images.githubusercontent.com/1231455/65284149-9bf2dd80-daed-11e9-9bb1-adbcb49d7415.gif)

cc @kevindoshier incase he is notified of this.

**Comment by kevindoshier** [comment]
Nice!  thanks i noticed that today too

**Comment by driskull** [comment]
No longer relevant since we don't have this component anymore
