### ISSUE TITLE
Enhancement: PickListItem rename textHeading to textLabel

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#288]
### Description
Rename the "textHeading" prop to be "textLabel" in order better match the DOM.

### Acceptance Criteria 
- change the prop name
- retain backward compat. for a bit

#### Desired New Behavior
Name change.

#### Desired Change to Look and Feel
No change.

### Relevant Info 
From PR : https://github.com/Esri/calcite-app-components/pull/283#discussion_r326396675

**Which Component:**
PickListItem

cc @kat10140

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified & closin'
