### ISSUE TITLE
Bug: PickListItem e2e fix

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#289]
### Summary
[e2e test](https://github.com/Esri/calcite-app-components/blob/master/src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts#L14) is failing. Needs a fixin'.

### Actual Behavior
Test fails.
### Expected Behavior
Test passes.
### Reproduction Steps

1. npm run test

### Relevant Info 
May have happened during this PR #283

**Comment by asangma** [comment]
cc @driskull @kat10140

**Comment by pr3tori4n** [comment]
@asangma please verify.

**Comment by kat10140** [comment]
Verified
