### ISSUE TITLE
Enhancement: CalcitePickList remove id attribute being set

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#291]
### Description

Enhancement: CalcitePickList remove id attribute being set

I think we can just use the guid string that is generated to be set as the group string on the Sortable instance.

**Which Component:**
**Example Use Case:**

**Comment by pr3tori4n** [comment]
This will be part of the valueList split PR: #290

**Comment by pr3tori4n** [comment]
@driskull please verify.
