### ISSUE TITLE
Enhancement: CalciteBlock host element `aria-expanded`

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#292]
### Description

Extremely minor: the `aria-expanded` attribute is being set on the host.

If we are going to set it on the host, we should make sure that it's not being set by the user.

The other option would be to move it to the `article` internal to the component.

**Comment by jcfranco** [comment]
I'm not sure this is valid. `aria-expanded` is set on the host based on the state of the component. The user shouldn't be setting it and they are, the component will override so that the value is correct.

Ionic components do this too: https://github.com/ionic-team/ionic/blob/8a88dd25b66e72f30d2d3325ac3d3abe53396f74/core/src/components/checkbox/checkbox.tsx#L150-L154

**Comment by driskull** [comment]
Ok. I'm fine with leaving this.

My suggestion was to just move this to the internals of the component so a user doesn't see it on the custom element and doesn't have the ability to change it.

**Comment by jcfranco** [comment]
Do you know how we can test if both approaches give the same a11y hints to screen readers? The Accessibility tab from Chrome Dev Tools only reports `aria-expanded` when its on the host.

**Comment by driskull** [comment]
I know the `aXe` toolbar supports shadowDom but I'm not sure if the built in `accessibility` tab does.

**Comment by jcfranco** [comment]
Based on testing (axe) and a few resources I found (see below), there doesn't seem to be an issue w/ either approach, but I do kind of prefer hiding these details from the user if possible.

https://archive.substantial.com/blog/2014/02/05/accessibility-and-the-shadow-dom/
https://developer.paciellogroup.com/blog/2012/07/notes-on-web-components-aria/
http://marcysutton.github.io/accessibility-of-web-components/slides.html#/slide1
