### ISSUE TITLE
Enhancement: CalcitePickListItem is setting properties & classes on the Host

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#298]
### Description

The `CalcitePickListItem` should not be setting `classes` on the Host element where a user could remove them. These should be internal to the component itself and not exposed to the user so they cannot modify them or see them.

The following are also being set on the host element which should be removed to internal DOM

- role
- aria-checked
- tabindex

The `selected` attribute is being modified by the internals of the component. If it is a mutable `Prop`it should be declared as one.  The prop should just be changed by setting `this.selected = newValue` instead of by being set on render.

We should be able to remove the `isSelected` state and just use the `selected` prop for updating it.

### Acceptance Criteria 

- isSelected state is no longer setting the `selected` prop on render
-  role is set internally
- aria-checked is set internally
- tabIndex is set internally
- class is set internally

#### Desired Change to Look and Feel

N/A

#### Out of Scope

N/A

### Helpful Details

N/A

**Which Component:** `calcite-pick-list-item`
**Example Use Case:**

**Comment by pr3tori4n** [comment]
[Classes should not be set on the host.](https://developers.google.com/web/fundamentals/web-components/best-practices#do-not-self-apply-classes.)
The direction class is resolved by this PR:
https://github.com/Esri/calcite-app-components/pull/285/files
The highlight class is resolved by this PR:
https://github.com/Esri/calcite-app-components/pull/290

The remaining props on the host are not a problem. So leaving as is.

**Comment by driskull** [comment]
> The direction class is resolved by this PR:

A `rtl` attribute is not an attribute we want to express on the host. This is only needed internally so it should be an internal class.
