### ISSUE TITLE
Enhancement: Add compact mode for pick-list

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#301]
### Description
Add a compact mode for pick-list and pick-list-item.
I think value-list might be able to leverage some of this too.

### Acceptance Criteria 
Ability to render the pick-list with no checkbox or radio button icon.

#### Desired New Behavior
pick-list with no checkbox or radio button icon.

#### Desired Change to Look and Feel
pick-list with no checkbox or radio button icon.

#### Out of Scope
Nested items.

### Relevant Info 
See first pass #300.

**Which Component:** pick-list, pick-list-item

**Example Use Case:** Selecting a field or something where the picker is dismissed upon selection. Also any case where there are a lot of items and the interface could benefit from tighter spacing and less visuals.

cc @driskull @jcfranco @pr3tori4n @kat10140

**Comment by asangma** [comment]
![image](https://user-images.githubusercontent.com/12503298/65536941-2bffa100-deb9-11e9-81ed-03814e01c2a2.png)

**Comment by asangma** [comment]
@kat10140 I forgot to assign to you. This is installed. Mind verfin it?

**Comment by kat10140** [comment]
@asangma it doesn't look very compact on my local right now 😭

this is on master:

<img width="534" alt="Screen Shot 2019-10-24 at 9 09 01 AM" src="https://user-images.githubusercontent.com/48069902/67504470-49ea2e00-f63e-11e9-9702-5697a8ef3e84.png">

**Comment by kat10140** [comment]
Verified
