### ISSUE TITLE
Enhancement: CSS avoid using shorthand flex

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#302]
### Description

Avoid using CSS shorthand flex for elements to avoid cross browser inconsistencies.

https://github.com/Esri/calcite-app-components/pull/296#discussion_r327743418

### Acceptance Criteria 

Flex shorthand is replaced in all components

https://github.com/Esri/calcite-app-components/pull/296#discussion_r327743418

### Helpful Details

**Which Component:** All
**Example Use Case:** N/A

**Comment by asangma** [comment]
Reviewing this, looks like I may need to update these:

- [ ] _base
- [ ] action
- [ ] flow-item
- [ ] panel
- [ ] shel

**Comment by asangma** [comment]
VERFEE!

**Comment by driskull** [comment]
Looks good. they all have 3 args.
