### ISSUE TITLE
Enhancement: Investigate using flexbox stretch instead of 100% height

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#303]
### Description

Enhancement: Investigate using flexbox stretch instead of 100% height

https://github.com/Esri/calcite-app-components/pull/296#discussion_r327741171

The following components are using 100% height. 

![image](https://user-images.githubusercontent.com/1231455/65627789-f7591b80-df84-11e9-9a62-a1c8f91c5894.png)

Can we investigate using flexbox instead of the 100% height?

### Acceptance Criteria 

Flexbox is used instead of 100% height where applicable

#### Desired New Behavior

Flexbox is used instead of 100% height where applicable

### Helpful Details

**Which Component:** All
**Example Use Case:** N/A

**Comment by asangma** [comment]
See #591

**Comment by asangma** [comment]
Initial attempts to remove all the 100% heights resulted in breaking styles when components were nested. Removed the 100% height rules where possible.

Closing.
