### ISSUE TITLE
Bug: User should not be able to use arrow keys on tip manager navigation buttons

### ISSUE THREAD

**Issue by annelfitz** [Esri/calcite-app-components#307]
### Summary
For the navigation buttons in the tip manager, the user should only be able to interact with these buttons using the space bar or the enter key. These should not respond to the arrow keys. 

### Actual Behavior
When focused on the right arrow nav button, if you hit the left arrow key, it will go back. The function of this button should only be to view tips on the right, so we should avoid using arrow keys to interact with these navigation buttons.

### Expected Behavior
Only the space bar and enter key can interact with these buttons.

### Reproduction Steps

1. https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html
2. Focus on either the left or right arrow buttons of the tip manager, try using the arrow keys to move through the tips. You should only be able to use the space and enter

**Comment by driskull** [comment]
I can take this one

**Comment by annelfitz** [comment]
Looks good!
