### ISSUE TITLE
Bug: Clicking the picklist secondary action icon should focus the surrounding button

### ISSUE THREAD

**Issue by annelfitz** [Esri/calcite-app-components#310]
### Summary
When you click on the icon of the secondary action in the Picklist, it will not focus on the action button. You have to click in the area surrounding the icon in order for it to be selected/focused. Hopefully the following GIF helps explain what I'm seeing: 
![picklist_icon](https://user-images.githubusercontent.com/51344676/65792821-65cee280-e119-11e9-9eca-286ece396f80.gif)

### Actual Behavior
Clicking the icon of the secondary action button focuses on the entire item in the picklist instead of the action button itself.

### Expected Behavior
Clicking on the icon should focus on the secondary action button

### Reproduction Steps

1. https://esri.github.io/calcite-app-components/demos/calcite-pick-list.html
2. Click specifically on the icon of the secondary action
3. You will notice the highlight goes around the whole item instead of the action button

**Comment by annelfitz** [comment]
This is not just a problem here - also noticed in calcite-action-pad. cc/ @driskull

**Comment by driskull** [comment]
Seems like we need `user-select: none` on SVG elements inside the `calcite-action`.

**Comment by driskull** [comment]
Installed

**Comment by annelfitz** [comment]
Verified locally. Looks good
