### ISSUE TITLE
Bug: Calcite-flow-item menu needs to be more accessibility friendly

### ISSUE THREAD

**Issue by annelfitz** [Esri/calcite-app-components#311]
### Summary
The calcite-flow-item menu-button needs to follow the guidelines found at this link: http://w3c.github.io/aria-practices/#menubutton
Specifically look into the `aria-haspopup` and `aria-expanded`

Also, when the user opens the menu and then continues tabbing through the page, the menu should close automatically.

### Actual Behavior
Menu stays open when focus is removed

### Expected Behavior
Menu should close when the focus is shifted to another element on the page

### Reproduction Steps

1. https://esri.github.io/calcite-app-components/demos/calcite-flow-item.html
2. Tab through, open the menu button, then continue tabbing.  Menu will not close

**Comment by driskull** [comment]
related to #58

**Comment by driskull** [comment]
Can't do this yet due to stencil limitations
