### ISSUE TITLE
Enhancement: CalciteAction text modes

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#313]
### Description

Enhancement: CalciteAction text display modes

Makes #262 unnecessary.

#### Desired New Behavior

API Proposal:

```ts
interface CalciteAction {
  @Prop({reflect:true}) textDisplay: "hidden"  | "visible" | "interactive";
  @Prop({reflect:true}) textEnabled: boolean; // deprecate!!
}
```

#### Desired Change to Look and Feel

- "hidden" will never show the text.
- "visible" will always show the text.
- "interactive" will show the text when element is hovered or focused.

```html
<calcite-action text="hello world" text-display="interactive" />
```

cc @pr3tori4n @jcfranco @asangma for feedback.

**Comment by driskull** [comment]
Installed.

**Comment by kat10140** [comment]
Verified!
