### ISSUE TITLE
Enhancement: Improve Filter Label Accessibility

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#317]
Boulder:

From aXe:

```
Form elements must have labels

Issue description
Ensures every form element has a label

Impact: critical
Learn more
Element location
#one calcite-filter input
Element source
<input placeholder="Filter results">
```

_Originally posted by @driskull in https://github.com/Esri/calcite-app-components/pull/142_

**Comment by pr3tori4n** [comment]
@driskull can you share how you are running axe? Is this a devDependency we can add and introduce an npm script for?

**Comment by driskull** [comment]
I'm using aXe toolbar for chrome. 
I think there is some way we could automate this. I think franco had an issue open somewhere.

**Comment by pr3tori4n** [comment]
@driskull please verify.
