### ISSUE TITLE
Research: Investigate potential Stencil.js bug with TipManager rendering

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#327]
### Background

https://github.com/Esri/calcite-app-components/pull/321#discussion_r330285333

Research: Investigate potential Stencil.js bug with TipManager rendering

It appears that the `key=""` should not be necessary for this component to re-render in this instance.

### Desired Outcome

Find out if its a bug or if we're doing something wrong in the component.

**Comment by pr3tori4n** [comment]
I don't think this is an issue for our repo - just open a bug in Stencil and add it here:
https://github.com/Esri/calcite-app-components/wiki/Stencil-Bugs-Tracking-Progress

**Comment by jcfranco** [comment]
@pr3tori4n Noted. This issue is mostly for future reference and to remind me to investigate and prepare a test case.

BTW, I narrowed it down and using SVGs somehow is affecting render updates. I have a reproducible test here that I'll submit to StencilJS:

<details>
<summary>rendering bug test case</summary>

```tsx
import {Component, h, State,} from "@stencil/core";

@Component({
  tag: "my-component",
  shadow: true
})
export class MyComponent {

  @State() selectedIndex = 0;

  previousClicked = (): void => {
    this.selectedIndex = this.selectedIndex - 1;
  };

  nextClicked = (): void => {
    this.selectedIndex = this.selectedIndex + 1;
  };

  render() {
    const { selectedIndex } = this;

    const leftIcon = "M9.707 4l-4 4 4 4H8.293l-4-4 4-4z";
    const rightIcon = "M6.293 12l4-4-4-4h1.414l4 4-4 4z";

    console.log("current index", selectedIndex);

    return (
      <div>
        <span
          onClick={this.previousClicked}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            height="16"
            width="16"
            viewBox={`0 0 16 16`}
          >
            <path d={leftIcon} />
          </svg>
        </span>
        <span>
          {selectedIndex}
        </span>
        <span onClick={this.nextClicked}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            height="16"
            width="16"
            viewBox={`0 0 16 16`}
          >
            <path d={rightIcon} />
          </svg>
        </span>
      </div>
    );
  }
}
```
</details>

**Comment by jcfranco** [comment]
Created issue: https://github.com/ionic-team/stencil/issues/1917 and updated the Stencil bug tracking wiki.
