### ISSUE TITLE
Enhancement: Style CalciteAction with 'textDisplay="interactive"'

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#328]
### Description

Enhancement: Style CalciteAction with 'textDisplay="interactive"'

### Acceptance Criteria 

Styling with animation for the interactive `textDisplay` that only shows text when the `calcite-action` is hovered or focused.

#### Desired New Behavior

N/A

#### Desired Change to Look and Feel

Styling with animation for the interactive `textDisplay` that only shows text when the `calcite-action` is hovered or focused.

### Helpful Details

**Which Component:** CalciteAction

**Comment by asangma** [comment]
@driskull this is the OG or #391 I think.

**Comment by driskull** [comment]
yeah these are both the same. closing!
