### ISSUE TITLE
Enhancement: Adding a sort slot for pick and value list

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#331]
Add a slot to pick-list and value-list so Adelheid can wire up her functionality to be able to sort items in the respective lists. 

This slot is to sit below the filter component and above the list.  I think Mitch has the designs.

**Comment by pr3tori4n** [comment]
@kat10140 I've added a slot. @asangma if you'd like to update the styling go for it. The slot is merged into master but unreleased so we can change if necessary.

**Comment by pr3tori4n** [comment]
@kat10140 installed please verify.

**Comment by kat10140** [comment]
@pr3tori4n is this installed on master? There are no commits or PRs referencing in here

**Comment by kat10140** [comment]
Oh I see you call it menu-actions. Verified
