### ISSUE TITLE
Enhancement: PickList/ValueList Filter Label

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#333]
### Description
I've put the placeholder on an aria-label attribute for now. I'm opening this issue to tackle what sort of labeling we want to support for the internal filters. Do we want to add a prop that allows the pickList author to set the label? Do we need to add a slot for this to support HTML or will plain text work? 
### Acceptance Criteria 
~@asangma @kat10140 could you do some requirements gathering for this?~

- text label default value is going to be just 'filter' 
- remove text label from dom

### Helpful Details

**Which Component:** Filter

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified
