### ISSUE TITLE
Bug: Clicking tip manager nav buttons should cause focus outline (all browsers but chrome)

### ISSUE THREAD

**Issue by annelfitz** [Esri/calcite-app-components#335]
### Summary
Clicking on the tip manager navigation buttons should cause a focus outline around the button specifically - but instead is causing the entire tip manager to be focused. This is occurring in all browsers (Safari, Firefox, Edge) except Chrome.

### Actual Behavior
Example in Safari:
![calcite_no_focus](https://user-images.githubusercontent.com/51344676/66143608-4f62d400-e5bc-11e9-887e-8045c557dae7.gif)

Notice how clicking on the tip navigation button does not cause a focus outline around the button.

### Expected Behavior
Example in Chrome: 
![calcite_focus](https://user-images.githubusercontent.com/51344676/66143614-5853a580-e5bc-11e9-984a-6ff847818ba3.gif)

Button is focused when clicked. 👍 

### Reproduction Steps

1. https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html

**Comment by pr3tori4n** [comment]
@annelfitz @asangma we'd need to put specific focus styles on the button in `calcite-action` in order to achieve this. I'll add a starting point but @asangma you'll probably want to finesse it.

**Comment by driskull** [comment]
DOM element styling differs from browser to browser. Even though the element is focused, it may look different in FF/Safari.

IMO I think we can ignore this one and close.

**Comment by annelfitz** [comment]
I'm fine if you want to close it - still works as it should for keyboard users
