### ISSUE TITLE
Enhancement: PickListItem Event Bubbles enable

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#338]
### Description
The PickList is stopping propagation of the pickListItem change event. @dhrumil83 is requesting this event be available so he can listen to checked/unchecked of a single item.

#### Desired New Behavior
* stop propagation is removed from PickList and ValueList so child events bubble up.

**Which Component:** `<calcite-pick-list>` `<calcite-value-list>`
**Example Use Case:** User has a multi select pick list, and wants to listen to when is checked/unchecked. Doesn't need to know the full list of selections.

**Comment by pr3tori4n** [comment]
@kat10140 @asangma can you vet this request. Is there any reason we shouldn't do this that I'm missing?

**Comment by asangma** [comment]
I don't see an issue here.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified!
