### ISSUE TITLE
Enhancement: PickList & ValueList - Add a prop to enable/disable the filter

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#339]
### Description
The filter always appears right now, users want to be able to disable it.

#### Desired New Behavior
* Filter is disabled by default
* prop can be set to enable the filter.

### Helpful Details

**Which Component:** `<calcite-pick-list>` `<calcite-value-list>`

========================

## API Design

```js
/**
   * When true, an input appears at the top of the list that can be used by end users to filter items in the list.
   */
  @Prop({ reflect: true }) filterEnabled = false;
```

**Comment by pr3tori4n** [comment]
@asangma @kat10140 fyi.

**Comment by pr3tori4n** [comment]
@driskull @jcfranco added an API design

**Comment by driskull** [comment]
👍

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified.
