### ISSUE TITLE
Bug: CalciteFilter shows "x" clear button in Edge but it doesn't return unfiltered items

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#340]
### Summary

Bug: CalciteFilter shows "x" clear button in Edge but it doesn't return unfiltered items

### Actual Behavior

Bug: CalciteFilter shows "x" clear button in Edge but it doesn't return unfiltered items

### Expected Behavior

Either:

- The clear button is not displayed.
- The clear button shows all items again.

### Reproduction Steps

1. Open sample with a filter in edge
1. Type in a filter.
1. Click the clear "x" button.
1. Notice how the results are still hidden.

### Relevant Info 

![image](https://user-images.githubusercontent.com/1231455/66352228-0ee4bc80-e914-11e9-99da-442055056d91.png)

**Comment by pr3tori4n** [comment]
> MDN Link for this feature - https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear
> Related Edge bug - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17584515/
> [So it's non-standard, and also broken.](https://github.com/angular/angular/issues/26307#issuecomment-428416280)

Bug affects inputs of type text, not just search.

Solution will be to hide it using:
```css
::-ms-clear { display: none; }
```

We'll have to add this manually if it's a feature we'd like, and it'd be available for all browsers.

**Comment by pr3tori4n** [comment]
@driskull Please verify.
