### ISSUE TITLE
Bug: Flow animation kicks in if the edit button is clicked on the BasemapLayerList jsapi widget

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#343]
### Summary
Flow animation kicks in if the edit button is clicked on the BasemapLayerList jsapi widget

### Expected Behavior
The animation doesnt start again
### Reproduction Steps

1

![basemaplayerlist](https://user-images.githubusercontent.com/11093161/66416197-23779200-e9b2-11e9-981e-9fc5bdb40234.gif)

**Comment by driskull** [comment]
@kevindoshier when do you need this in by? I have a PR open and good to go. just wondering if we need to patch this week or if it can wait till next tuesday.

**Comment by kevindoshier** [comment]
Next tuesday will be fine, as long as we have it for beta 1 of the viewer I think we are good

**Comment by kevindoshier** [comment]
Nice!  Looks good today, thanks!  Im not able to change labels or anything, but this one is fixed

**Comment by driskull** [comment]
Thanks Kevin!
