### ISSUE TITLE
New Component: Card

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#348]
### Description
Cards contain content and actions about a single subject.
See [Material card](https://material.io/components/cards/#anatomy).

#### User Stories
Developer wants to add a highly visual entry point to more content or a larger set of configurations.

### Acceptance Criteria 
![image](https://user-images.githubusercontent.com/12503298/66436320-95b09c80-e9db-11e9-8ce7-d2e99e3c1b25.png)

_stolen from https://material.io/components/cards/_

1. Container
Card containers hold all card elements, and their size is determined by the space those elements occupy. Card elevation is expressed by the container.

2. Thumbnail [required]
Cards can include thumbnails to display an avatar, logo, or icon.

3. Heading text [required]
Header text can include things like the name of a photo album or article.

4. Footer with leading and trailing slots

4. ~Subhead [optional]~
~Subhead text can include text elements such as an article byline or a tagged location.~

5. ~Media [optional]~
~Cards can include a variety of media, including photos, and graphics, such as weather icons.~

6. ~Supporting text [optional]~
~Supporting text include text like an article summary or a restaurant description.~

7. ~Buttons~ Single Button [optional]
~Cards can include buttons for actions.~ Cards can include a single call-to-action button.

8. Icons [optional]
Cards can include icons for actions.

9. Props for image-crop // image-crop-scale (for dealing with thumbnail)

#### Desired Behavior
States
- idle
- hover/focus
- selected
- disabled
- loading

#### Desired Look & Feel
How @mitc7862 wants it.

### Helpful Details
Would be nice if we can match the calcite-components needs and eventually port there.
https://github.com/Esri/calcite-components/issues/52

**Comment by driskull** [comment]
This is a good onboarding component. @kat10140 would you have any interest in developing this one?

**Comment by kat10140** [comment]
Sure! @driskull

**Comment by kat10140** [comment]
@mitc7862 do you have designs for this?

**Comment by driskull** [comment]
Here are calcite web cards: https://esri.github.io/calcite-web/documentation/components/#card

**Comment by mitc7862** [comment]
![image](https://user-images.githubusercontent.com/12564905/68063321-3e95a300-fccd-11e9-895e-5be0e7770d56.png)

**Comment by julio8a** [comment]
@kat10140 move to calcite-components. Katy, you'll still be building the component.

**Comment by kat10140** [comment]
```
 @Prop({ reflect: true }) disabled = false;

 @Prop({ reflect: true }) loading = false;

 @Prop({ reflect: true }) hover = false;

 @Prop({ reflect: true }) selected = false;

 @Prop({ reflect: true }) idle = false;

 @Prop({ reflect: true }) headerText = string;

 @Prop({ reflect: true }) subHead = string;

 @Prop({ reflect: true }) supportingText = string;

 @Prop({ reflect: true }) imageCrop = false;

 @Prop({ reflect: true }) imageCropScale: "small" | "medium" | "large" = "medium"; 

```

```
<slot name="thumbnail">  
<slot name="icon">  
```

**Comment by driskull** [comment]
- We can remove `hover` as a prop
- Lets find out if we need an `idle` prop. @asangma??
- General heading slot for text and icons
- Remove subHead prop  & remove supportingText prop.
- Slot for single action. "action" slot.
- Better name for image crop property? Something to explain what its doing. 
- `imagePropScale` to `imageScale` and use `s`, `m`, `l` for consistency.
- footer leading and trailing slots
- `compact` prop to make everything smaller?

**Comment by julio8a** [comment]
Hey guys, 

Checking in to see where this component is being built. Last time we talked it was going to be built in calcite-components.

**Comment by driskull** [comment]
@julio8a @kat10140 Yes, it should be built in calcite-components. @kat10140 can you move the issue there?

**Comment by kat10140** [comment]
https://github.com/Esri/calcite-components/issues/230

**Comment by kat10140** [comment]
@driskull opening back up to keep tabs in our repo

**Comment by driskull** [comment]
@kat10140 I don't think we need to worry about `card` in our repo. We just need issues to track the `CalciteIcon` and `CalciteScrim` since this repo will use those.
