### ISSUE TITLE
Enhancement: calcite-panel without header text but close icon

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#354]
### Description
I changed from `calcite-shell-floating-panel` to `calcite-panel` and added `dismissible=true`. Then the close icon appeared on the wrong side.

![1](https://user-images.githubusercontent.com/44481292/66501281-f8577600-ea77-11e9-8216-e672f52a3af7.png)

Then we noticed that if we add an empty div for the `content-header` slot it works. But we don't need any text in the header. Could this be optional?

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by driskull** [comment]
@AdelheidF I can make it so those slots are always there.

**Comment by AdelheidF** [comment]
@kat10140 I don't have this test case anymore. Could you verify? Thanks.

**Comment by kat10140** [comment]
Verified !
