### ISSUE TITLE
Enhancement: CalciteFlowItem - add loading & disabled properties

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#359]
### Description

Enhancement: CalciteFlowItem add loading & disabled properties. 
CalciteFlowItem will then pass down props to CalcitePanel. 
All styles for CalcitePanel will live in the panels scss file.

### Acceptance Criteria 

Loading and disabled boolean properties on the component.

#### Desired New Behavior

- Loading should display a visual loading state on the component.
- Disabled should display a visually disabled state on the component and prevent user interaction as necessary.
- Loading should use any appropriate `calcite-components` for loading as necessary.

#### Desired Change to Look and Feel

Loading style and disabled style on the item, passed down to panel

### Relevant Info 

Related to #248

### Helpful Details

@asangma you can help me figure out what exactly needs to be blocked and what the ideal design should look like.

**Comment by asangma** [comment]
Installed. @kat10140 
BYER BYER BYEEEEEER...

**Comment by kat10140** [comment]
I see props on here, but no demo! I made a separate issue for that @407
