### ISSUE TITLE
Enhancement: CalciteShellPanel - add loading & disabled properties

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#360]
### Description

Enhancement: CalciteShellPanel add loading & disabled properties

### Acceptance Criteria 

Loading and disabled boolean properties on the component.

#### Desired New Behavior

- Loading should display a visual loading state on the component.
- Disabled should display a visually disabled state on the component and prevent user interaction as necessary.
- Loading should use any appropriate `calcite-components` for loading as necessary.

#### Desired Change to Look and Feel

Loading style and disabled style

### Relevant Info 

Related to #248

### Helpful Details

@asangma you can help me figure out what exactly needs to be blocked and what the ideal design should look like.

**Comment by asangma** [comment]
I think with the disabled & loading states for Action and FlowItem, we may not need this.
What y'all say? @driskull @jcfranco

**Comment by kat10140** [comment]
Ok can we close this one? @driskull @asangma

**Comment by driskull** [comment]
I'll close it and remove the properties from the component. sound good?

**Comment by kat10140** [comment]
sounds good!
