### ISSUE TITLE
Enhancement: CalcitePickList - add loading & disabled properties

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#361]
### Description

Enhancement: CalcitePickList add loading & disabled properties

### Acceptance Criteria 

Loading and disabled boolean properties on the component.

#### Desired New Behavior

- Loading should display a visual loading state on the component.
- Disabled should display a visually disabled state on the component and prevent user interaction as necessary.
- Loading should use any appropriate `calcite-components` for loading as necessary.

#### Desired Change to Look and Feel

Loading style and disabled style

### Relevant Info 

Related to #248

### Helpful Details

@asangma you can help me figure out what exactly needs to be blocked and what the ideal design should look like.

**Comment by asangma** [comment]
@kat10140 Installed.

**Comment by kat10140** [comment]
Verified!
