### ISSUE TITLE
Enhancement: block-section. Use small calcite-switch for switch mode

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#370]
### Description
use `scale="s"`
`<calcite-switch switched={open} onChange={this.toggleSection} scale="s" />`

**Which Component:** block-section
**Example Use Case:** 
Fix this
![image](https://user-images.githubusercontent.com/12503298/66587037-839b3f00-eb3e-11e9-9be6-37ab182aa027.png)

**Comment by asangma** [comment]
cc @AdelheidF

**Comment by AdelheidF** [comment]
Also, do we want the horizontal line between the header and the content? 

![image](https://user-images.githubusercontent.com/44481292/66588535-8d727180-eb41-11e9-8029-8b5515ee2e5d.png)
