### ISSUE TITLE
Enhancement: block-section move border to bottom

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#372]
### Description
From https://github.com/Esri/calcite-app-components/issues/370#issuecomment-540670487

Move border to bottom of section.

### Acceptance Criteria 
clearer section separation

#### Desired New Behavior
no change

#### Desired Change to Look and Feel
border on bottom of section.

**Which Component:** block-section

cc @AdelheidF

**Comment by asangma** [comment]
I'll have a rule in there for :last-child to not have a border. 👍

**Comment by asangma** [comment]
@AdelheidF Installed!

**Comment by AdelheidF** [comment]
Looks good now. 

Do you submit, fix and verify your issues? :)
