### ISSUE TITLE
Question: Does calcite-panel need headerLeadingContent?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#374]
### Question
Do you think we could redo the panel header so that it matches the flow-item header structure/props?

Right now they're similar in layout but different in how they are put together.

This may be moot depending on the answer to this question: does panel need both leading and trailing header content? Seems like our use cases here are for putting stuff in the popover in which case we'd only need a default trailing X action.

Maybe I'm missing something...?

### Helpful Details

**Topic:** Panel header

**Context:** calcite-panel

@driskull @jcfranco @pr3tori4n @kat10140

**Comment by asangma** [comment]
from https://github.com/Esri/calcite-app-components/issues/366#issuecomment-540842536

**Comment by driskull** [comment]
Needs it for the back button on the flow-item.

**Comment by pr3tori4n** [comment]
@asangma can you help me understand the goal here? How are they different, and what would making them more consistent solve?
