### ISSUE TITLE
New Component: Custom select

### ISSUE THREAD

**Issue by janett-baresel** [Esri/calcite-app-components#383]
### Description
Scene Viewer team would like a "custom" select element, where the entries can be styled in CSS as well as contain images/icons.
Examples from Scene Viewer and Map Viewer are here:
![grafik](https://user-images.githubusercontent.com/11048042/66841530-1df9e900-ef6a-11e9-8f87-3f2890be969e.png)

![grafik](https://user-images.githubusercontent.com/11048042/66841909-a5475c80-ef6a-11e9-90d9-d4e0449c05ce.png)

#### User Stories
Some of the more complex options in the Scene Viewer authoring UI require explanations and images to make it simple for the user to pick one option. 

### Acceptance Criteria 
- define name of each option (shown when the option is selected) and optional label which can contain a html string

#### Desired Behavior
- when select is opened, you see the options with optional custom styling
- when you select an option you see the label
- otherwise this custom select behaves as native HTML select

#### Desired Look & Feel
- as native HTML select just with extended label option

### Helpful Details
We previously used dojos `dijit/form/FilteringSelect` which provided this functionality but we now want to move away from it.

**Comment by asangma** [comment]
@driskull @janett-baresel I think the first example could be handled with the pick-list using the `compact` attribute.

The second example would be addressed with the "compact" or "list mode" of the card component (#348). @mitc7862 should be doing the designs.

**Comment by asangma** [comment]
This is what compact mode looks like in pick-list:
![image](https://user-images.githubusercontent.com/12503298/66964268-f6b72080-f02a-11e9-8048-0d1f460c83c0.png)

The (i) is slot.

I'm not sure if this has gone out in a release yet. (Doesn't show up in the IO demos.)

**Comment by janett-baresel** [comment]
but the pick-list is just a list. No drop-down, select, collapse kind of functionality right?

**Comment by pr3tori4n** [comment]
@asangma need to connect with calcite team to determine best COA.

**Comment by driskull** [comment]
This is getting stale. Is this something that is happening in `calcite-components`? Can we close this?

**Comment by driskull** [comment]
closing in favor of https://github.com/Esri/calcite-components/issues/61
