### ISSUE TITLE
Enhancement: Ability to control calcite value list item size

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-app-components#390]
### Description
calcite-value-list-item uses calcite-pick-list-item, and the client does not have access to the shadow dom to control it's size

#### Desired New Behavior
Ability to make the height smaller:
![image](https://user-images.githubusercontent.com/14285436/66942765-9dd19300-effe-11e9-91f1-fd9c682d4f1f.png)

**Comment by kat10140** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/48069902/67342571-62940000-f4e7-11e9-8823-3633593764a2.png)
![Screenshot (4)](https://user-images.githubusercontent.com/48069902/67342573-645dc380-f4e7-11e9-8f56-b5a2836533d9.png)

**Comment by kat10140** [comment]
This is what it looks like on the surface as well as my remote desktop

**Comment by kat10140** [comment]
on all browsers

**Comment by asangma** [comment]
Thanks @kat10140 !

**Comment by asangma** [comment]
@dhrumil83 @CodeBarker See #456
