### ISSUE TITLE
Question: how to increase calcite-shell-panel width

### ISSUE THREAD

**Issue by yobeidat** [Esri/calcite-app-components#392]
### Question
how to increase width of calcite-shell-panel? for example to 500px.
### Helpful Details
In calcite-shell-full-window demo, I want to increase the width of the right panel(contextual-panel) but the width property does affect the with of the panel.
**Topic:**

**Context:**

**Comment by driskull** [comment]
@asangma can you answer this?

**Comment by asangma** [comment]
@yobeidat At the time, we are keeping the panel width dynamic and based on the window width. I think if we get enough requests to have more control over the panel width, we could consider exposing a CSS var.

**Comment by asangma** [comment]
Closing. @yobeidat Please re-open if you feel this isn't solved.
