### ISSUE TITLE
Bug: Adding action pad to contextual action bar causes some styling issues

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#393]
### Summary
After the first rendering of the action pad, if I hide then show it again, I get scroll bars in the shell

To see this try this link, and click the help action on bottom right

https://energy.mapsdevext.arcgis.com/apps/mapviewer/index.html

![action_bar_action_pad](https://user-images.githubusercontent.com/11093161/67019448-89020780-f0b1-11e9-83d1-7adc848d14f4.gif)

### Reproduction Steps

1.

**Comment by driskull** [comment]
@kevindoshier the overflow is actually on the body there since the popover is outside of the shell. Can you set `overflow:hidden` on the body of the document?

**Comment by kevindoshier** [comment]
@driskull - we need to have scrollbars when the window gets to small, what do I need to add to handle both cases?

**Comment by driskull** [comment]
@kevindoshier shouldn't the panels handle the scrolling? the `calcite-shell-panel` or `calcite-flow-item` should get the scrollbars.

**Comment by kevindoshier** [comment]
calcite-shell sets it to hidden
![image](https://user-images.githubusercontent.com/11093161/67311461-7d994c80-f4b4-11e9-9239-880d123751ff.png)

**Comment by driskull** [comment]
Its just the `min-width` on the `calcite-shell` that limits the view from shrinking.

@asangma do we want to relax these minimum widths and heights a bit? I think we could go smaller and still be usable.

@kevindoshier I think it would be good to remove scrolling from the body still. A full page app shouldn't have scrollbars IMO.

**Comment by kevindoshier** [comment]
Yeah I agree, but then calcite-shell etc, should better handle smaller widths so the right hand actionBar can still be used, otherwise it gets hidden and there isnt a way to get to it without a scrollbar

cc: @AdelheidF

**Comment by AdelheidF** [comment]
Yes!, I have a small Surface and it keeps scrolling. I'm expecting a small map in that case.

**Comment by driskull** [comment]
@kevindoshier the actionbar does get a scrollbar now if necessary.

**Comment by kat10140** [comment]
verified and closing
