### ISSUE TITLE
Bug: Value-list label editing not working

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#395]
### Summary
Label editing isn't working. Value list doesn't have a labelEditingEnabled property like in the initial design. (Did we decide to change this? not on the issue- I remember you saying something about using HTML for this)

### Actual Behavior
Label can't be edited.

![label editing not working](https://user-images.githubusercontent.com/48069902/67046644-84574680-f0e5-11e9-8539-955ffb223c8c.gif)
^^^ that was me clicking, pressing enter, and space bar trying to get an <input>

### Expected Behavior
Label can be edited.

### Reproduction Steps

1. Go to http://localhost:3333/demos/calcite-value-list.html and try to edit

### Relevant Info 
(Alan tagged you  bc we'll need to think about styling when this is done)

**Comment by asangma** [comment]
@kat10140 sorry I didn't update the req. We decided to nix the label editing. It may come back later but for now, we'll keep the interaction simple.
