### ISSUE TITLE
Enhancement: calcite-pick-list - add `X` to empty filter input + change filter text + update scrolling

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#396]
### Description
calcite-pick-list

(1)
To remove an entered filter string it would be useful to clear it with an X click instead of having to delete the string.

(2)
Is it possible to change the string in the filter?

Design
<img src=https://user-images.githubusercontent.com/44481292/67066856-1765a000-f129-11e9-8364-d8a9a752acc3.png width=250/>
Component:
<img src=https://user-images.githubusercontent.com/44481292/67066889-38c68c00-f129-11e9-808c-9d217f600c0c.png width=250/>

(3)
My picklist is going to be longer than what I can display in a calcite-popover, so there has to be vertical scroll bars. But I would like to keep the filter showing and just the list of item scrolling. This is not possible currently. My popover has a max-height but the picklist totally overlaps that popover unless I give it an overflow. But then the filter scrolls away too. I would like to have the picklist doing the scrolling on its own if it can't fit into the parent node. And keep the filter input box always visible.

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by AdelheidF** [comment]
Added (3) for scrolling

**Comment by pr3tori4n** [comment]
@kat10140 could you triage this and split each request into a separate issue?

**Comment by asangma** [comment]
@kat10140 Lemme know if you want any halp breaking this down.

**Comment by pr3tori4n** [comment]
@asangma I'm going to take a stab at this. If you have some designs you want me to follow, please provide.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
verified

**Comment by AdelheidF** [comment]
@kat10140 How can I change the string 'Filter results'? Also, will the current string get translated?

**Comment by asangma** [comment]
@kat10140 @pr3tori4n Looks like part of this issue was not addressed.

> Is it possible to change the string in the filter?

Reopening.

**Comment by pr3tori4n** [comment]
@asangma it would be better to open each feature request as a separate issue. Can we create new issues for the other two requests, and keep this closed as the issue addressing the clear button?

**Comment by AdelheidF** [comment]
https://github.com/Esri/calcite-app-components/issues/597

**Comment by kat10140** [comment]
above issue has been assigned. Closing
