### ISSUE TITLE
Bug: CalciteTip background/shadow applied incorrectly

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#398]
### Summary

The `calcite-tip` has a shadow inside of itself. The shadow should be either on the host or the background color should be defined where the shadow is.

![image](https://user-images.githubusercontent.com/1231455/67050676-e9169f00-f0ed-11e9-9dda-3498694e68f2.png)

### Actual Behavior

The shadow is inside the tip

### Expected Behavior

The shadow is outside of the tip

**Comment by asangma** [comment]
verified locally
