### ISSUE TITLE
Bug: Value-list select not highlighting

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#399]
### Summary
Items in value list have selected property.  When selected, they are meant to be highlighted as a visual representation of the selection. This isn't happening, so the user isn't visually aware of what is selected. 

### Actual Behavior
![value list highlighting](https://user-images.githubusercontent.com/48069902/67050744-224f0f00-f0ee-11e9-9a68-32b99cae26b9.gif)

### Expected Behavior
Hilite!
### Reproduction Steps

1. https://esri.github.io/calcite-app-components/demos/calcite-value-list.html

**Comment by asangma** [comment]
Mind re-checking this one.
Selected value-list-items seems to be showing the selected state now. :)

**Comment by kat10140** [comment]
i thought this was supposed to highlight blue i didn't see the box MY BAD!!
