### ISSUE TITLE
Bug: calcite-pick-list filter is hiding all items

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#400]
### Summary

Using "@esri/calcite-app-components@4.2.1"

(1)
- [ ] When using the filter the list goes empty and doesn't come back when I remove the filter.

<img src=https://user-images.githubusercontent.com/44481292/67053556-a1e0dc00-f0f6-11e9-8616-fe04dda4508e.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/67053615-c1780480-f0f6-11e9-91e1-4e43d321f19d.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/67053642-d3f23e00-f0f6-11e9-8584-a2dc409bdead.png width=200/>

(2) 
- [x] When using slot menu-actions with a dropdown there's a CSS issue.
Separate issue created: https://github.com/Esri/calcite-app-components/issues/417

<img src=https://user-images.githubusercontent.com/44481292/67053591-b58c4280-f0f6-11e9-8938-42261abef845.png width=100/>

```
        <calcite-pick-list
          filter-enabled="true"
          multiple="true"
        >
          <calcite-dropdown slot="menu-actions" alignment="right">
            <calcite-action
              slot="dropdown-trigger"
              onclick=...
              label="Sort"
            >
              <svg>...</svg>
            </calcite-action>
            <calcite-dropdown-group grouptitle="Sort by">
              <calcite-dropdown-item active>Display name</calcite-dropdown-item>
              <calcite-dropdown-item>Type</calcite-dropdown-item>
            </calcite-dropdown-group>
          </calcite-dropdown>
          {items}
        </calcite-pick-list>

```

(3) 
- [ ] When in `multiple=false` mode I can deselect the single selected radio button by clicking on it again. I don't think it should let me do that. When in radio button mode there should be always one selected.

When using the "calciteListChange" event on a filtered list I assume I still get all checked items, correct? The filter doesn't affect the list of items. Can't test this currently.

### Reproduction Steps

local version of https://devext.arcgis.com/apps/mapviewer/index.html

**Comment by jbartley** [comment]
What is the latest on this issue? @pr3tori4n

**Comment by pr3tori4n** [comment]
@jbartley I'm trying to find the root cause. I'm having trouble reproducing this in isolation. I just found out that Adelheide has a test-app setup in the app-components repo so I'm going to take a look at that. This is a priority for me.

**Comment by pr3tori4n** [comment]
> When using the "calciteListChange" event on a filtered list I assume I still get all checked items, correct? The filter doesn't affect the list of items. Can't test this currently.

@AdelheidF  That's correct. The filter only changes what's displayed, it doesn't affect the current selections.

**Comment by pr3tori4n** [comment]
> When in multiple=false mode I can deselect the single selected radio button by clicking on it again. I don't think it should let me do that. When in radio button mode there should be always one selected.

@kat10140 @asangma Can you triage this and create an enhancement issue. Do we need a flag for this behavior (there a use case for the way we have it now?) or can we just modify the default?

**Comment by pr3tori4n** [comment]
@AdelheidF @jbartley @jcfranco this is being caused by the same Maquette.js issue we saw when the pre-selection wasn't working. I hesitate to move more setup code to run after first-render. I'd like to dig into Maquette a bit and see why this is happening - why some attributes are populated on first render, but others aren't. This could happen with other components as well so I'd like to do more research. If there's a way of preventing this behavior in using Maquette that'd be the ideal solution imo. If not, we might find a better solution with some more advanced mutationObservers.

@AdelheidF if you need a workaround soon - I can offer you something temporary in the meantime. Let me know.

**Comment by AdelheidF** [comment]
> if you need a workaround soon - I can offer you something temporary in the meantime. Let me know.

Since it's already on devext and pretty obvious a temporary solution would be great. Thanks!

**Comment by jcfranco** [comment]
> why some attributes are populated on first render, but others aren't. 

I doubt this is being caused by maquette. Could it be some NonReact™ component oddness?

**Comment by pr3tori4n** [comment]
@AdelheidF @jbartley I have a temporary fix in until I find out the true root cause.

**Comment by pr3tori4n** [comment]
@kat10140 can you help triage this item and move #3 into a separate issue?

**Comment by kat10140** [comment]
@pr3tori4n that issue is closed?

**Comment by AdelheidF** [comment]
1 and 2 are fixed, 3 I can handle myself if it's not considered a bug. Thanks.

**Comment by pr3tori4n** [comment]
@kat10140 sorry link was unintentional :) - didn't mean issue 3 but the 3rd item in Adelheides initial comment `(3)`.

**Comment by pr3tori4n** [comment]
@kat10140 Please verify.

**Comment by kat10140** [comment]
@pr3tori4n looks like radio buttons can still be deselected

**Comment by kat10140** [comment]
![radio buttons](https://user-images.githubusercontent.com/48069902/68513580-3dfe8e80-0230-11ea-99b3-b827f93a9e81.gif)

**Comment by kat10140** [comment]
nvm, making this into separate issue
