### ISSUE TITLE
Enhancement: Use storybook for demos

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#401]
### Description

`calcite-components` is now using storybook for displaying demos. I think we should probably do the same.

https://esri.github.io/calcite-components/

### Acceptance Criteria 

- Use storybook for demos
- Remove demo nav

### Relevant Info 

See PR for calcite-components: https://github.com/Esri/calcite-components/pull/177

**Comment by jcfranco** [comment]
@kat10140 Can we target this for Eberhart or Fern? I can start doing some setup work and I'll pull in more people when it comes to adding individual component stories.

**Comment by kat10140** [comment]
Sure, sounds good @jcfranco 💫

**Comment by jcfranco** [comment]
Installed storybook groundwork. Will create follow-up issue to complete stories.

**Comment by driskull** [comment]
Groundwork looks good @jcfranco!
