### ISSUE TITLE
Enhancement: Block - control slot needed before the heading

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#404]
### Description
We need a named slot that can be rendered _before_ the heading of a Block (we have one for the right corner right now). 

This will primarily be used for dragon dropz functionality by Dhrumil. (I added 'named' slot since we are talking about possibly having a dragon drop component that uses the dnd icon for blocks when the named slot meets the reqs) -  we can talk about this in the next meeting.

### Acceptance Criteria 
- Slot before the heading/title of Block component

#### Desired New Behavior
Slawt

#### Desired Change to Look and Feel
Slawt

**Comment by jcfranco** [comment]
Installed.
