### ISSUE TITLE
Enhancement: calcite-flow-item with two lines in header

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#406]
### Description

The smartMapping and the popup configuration components need two lines in a calcite-flow-item header when displaying layer field information.

This is the design:
<img src=https://user-images.githubusercontent.com/44481292/67156044-8c260f00-f2ce-11e9-8774-df093c086c25.png width=300/>

For new map viewer
https://energy.mapsdevext.arcgis.com/apps/mapviewer/index.html

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by driskull** [comment]
@asangma how should this be addressed? Do we need to accept a slot instead for this or do we want a subheading prop?

**Comment by asangma** [comment]
prolly need a `summary` prop like pick-list-item

**Comment by driskull** [comment]
Created PR for this. and there's an issue here: https://github.com/Esri/calcite-app-components/issues/450

**Comment by asangma** [comment]
Looks like we will have need for this. Reopening.

**Comment by driskull** [comment]
@asangma this one is already open: https://github.com/Esri/calcite-app-components/issues/450
