### ISSUE TITLE
Bug: pick-list action slot styling

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#417]
### Summary
The pick/value-list `menu-actions` need styling.

### Actual Behavior
<img width="352" alt="Screen Shot 2019-10-21 at 1 20 26 PM" src="https://user-images.githubusercontent.com/12503298/67240129-add5e200-f405-11e9-9386-84b68702fe2f.png">

### Expected Behavior
Should look better.

### Reproduction Steps

1. add an action to the `menu-actions` slot.

cc @kat10140

**Comment by asangma** [comment]
cc @AdelheidF

**Comment by kat10140** [comment]
yeyer

**Comment by AdelheidF** [comment]
Looks good now
