### ISSUE TITLE
Enhancement: Add popover to full width demo

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#421]
### Description
Add a popover with a panel to the actions in the full width shell demo.  Inside the panel will be a pick-list with a filter and the menu-actions slot is to have an action. 

### Acceptance Criteria 
![Screen Shot 2019-10-21 at 3 59 27 PM](https://user-images.githubusercontent.com/48069902/67249276-fe583a00-f41b-11e9-96d7-d04668973355.png)

**Comment by kat10140** [comment]
insterled. @asangma verifee?

**Comment by asangma** [comment]
VERFEEE
