### ISSUE TITLE
Bug: Create Test to make sure event passes item HTMLElement correctly.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#423]
### Summary

Add a test for `calciteListItemChange` on `calcite-pick-list-item` to make sure that the `item` property is correctly defined in the event.

### Actual Behavior

Previously, the event did not pass the item like it was supposed to.

### Expected Behavior

The event has the item defined as a HTMLElement.

### Relevant Info 

https://github.com/Esri/calcite-app-components/commit/80e590081c87f4b5e1bd3830077e0134e4eb998a

**Comment by pr3tori4n** [comment]
@driskull please verify.
