### ISSUE TITLE
Bug: CalcitePickList warnings for unused modules and constants

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#426]
### Summary

The `calcite-pick-list-item` and `calcite-value-list` are throwing warnings when building because of unused imports and constants. Can we clean these up?

The linter should catch these things.

### Reproduction Steps

```
[ WARN  ]  TypeScript: src/components/calcite-pick-list-item/calcite-pick-list-item.tsx:14:1
           'classnames' is declared but its value is never read.

     L13:  import { checkSquare16, circle16, circleFilled16, drag16, square16 } from "@esri/calcite-ui-icons";
     L14:  import classnames from "classnames";
     L15:  import { CSS } from "./resources";

[ WARN  ]  TypeScript: src/components/calcite-pick-list-item/calcite-pick-list-item.tsx:17:1
           'CSS_UTILITY' is declared but its value is never read.

     L16:  import { ICON_TYPES } from "../calcite-pick-list/resources";
     L17:  import { CSS_UTILITY } from "../utils/resources";
     L18:  import CalciteIcon from "../utils/CalciteIcon";

[ WARN  ]  TypeScript: src/components/calcite-value-list/calcite-value-list.tsx:286:42
           'disabled' is declared but its value is never read.

    L285:  render() {
    L286:    const { dataForFilter, handleFilter, disabled, filterEnabled, loading } = this;
    L287:    return (
```

**Comment by driskull** [comment]
@jcfranco @pr3tori4n would we want to add linting as part of the build testing to catch these?

**Comment by jcfranco** [comment]
Yep. We should also make sure linting is enabled on our IDEs. #showsquiggliessomelove

**Comment by driskull** [comment]
My linter found these jsdoc errors too. 

![image](https://user-images.githubusercontent.com/1231455/67328696-b21a0200-f4ce-11e9-95dc-31cc52ce31e2.png)

@pr3tori4n can you lint on save if you don't like it auto linting?

**Comment by driskull** [comment]
Closing this since it was done. @jcfranco just link the PR to this when you get a chance.

**Comment by jcfranco** [comment]
Fixed by https://github.com/Esri/calcite-app-components/pull/528.
