### ISSUE TITLE
Bug: CalciteBlock header color is too dark for the dark theme

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#427]
### Summary

Bug: CalciteBlock header color is too dark for the dark theme

### Actual Behavior

The text color is black on dark gray

### Expected Behavior

The text color should be lighter.

### Reproduction Steps

1. See the shell demo page for dark theme.

### Relevant Info 

![image](https://user-images.githubusercontent.com/1231455/67314567-bab40d80-f4b9-11e9-84dc-8d0674b31692.png)

**Comment by asangma** [comment]
@driskull Did I need to verify this?

**Comment by asangma** [comment]
LOL

**Comment by driskull** [comment]
done
