### ISSUE TITLE
Bug: calcite-pick-list-item: text wrapping

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#430]
### Summary

Could we have the text wrap a bit nicer? 
![image](https://user-images.githubusercontent.com/44481292/67320362-f8696400-f4c2-11e9-8943-efb461fd84b5.png)

### Actual Behavior
[alan] Currently strings are broken at any character.

### Expected Behavior
[alan] Break on word and retain second line truncation.

### Reproduction Steps

1.

**Comment by jbartley** [comment]
I would put this higher on the priority.  Needed for beta 1.

**Comment by asangma** [comment]
@AdelheidF This is resulting from the request to truncate after two lines.

**Comment by asangma** [comment]
Like there was a desire to show the alias like this when it was long.
![image](https://user-images.githubusercontent.com/12503298/67422076-94a86f00-f586-11e9-90e2-de7466417262.png)

**Comment by asangma** [comment]
We can make it truncate after one line...?
![image](https://user-images.githubusercontent.com/12503298/67422169-c8839480-f586-11e9-8699-4cec81dde759.png)

**Comment by asangma** [comment]
Finally we can probably break on the word and keep the truncation at the 2nd line.
![image](https://user-images.githubusercontent.com/12503298/67422375-34fe9380-f587-11e9-9a59-e922457c0dbb.png)

Would we need the summary (`text-description`) to also truncate after two lines?
![image](https://user-images.githubusercontent.com/12503298/67422447-595a7000-f587-11e9-8e28-73200b763476.png)

**Comment by AdelheidF** [comment]
> Finally we can probably break on the word and keep the truncation at the 2nd line.

This is nice.

> Would we need the summary (text-description) to also truncate after two lines?

Currently this feature is in none of my designs, but it probably would make sense.

**Comment by asangma** [comment]
@AdelheidF 🤔 
If we only break on the word, we can see this kind of thing happen.
![image](https://user-images.githubusercontent.com/12503298/67433996-0f30b900-f59e-11e9-9cd8-9915712e89c9.png)

**Comment by asangma** [comment]
This is actually why we started with `word-break: all` 😭

**Comment by AdelheidF** [comment]
Could it look where the first space is then decide then what class to use?

**Comment by asangma** [comment]
Seems a bit brittle since we'd need to check font-size, component width, etc. Or am I overcomplicating it?

A quicker and more robust adjustment would be to to only do the one-line.

**Comment by asangma** [comment]
As a note, I can also add a `hyphen` style but it doesn't work consistently across languages or within a particular language. Here, it works all right except for the last item.
![image](https://user-images.githubusercontent.com/12503298/67436280-dfd07b00-f5a2-11e9-9f81-8c49fd689731.png)

**Comment by AdelheidF** [comment]
> A quicker and more robust adjustment would be to to only do the one-line.

This would be very annoying for demographic layers with similar starting field names.

**Comment by AdelheidF** [comment]
> Seems a bit brittle since we'd need to check font-size, component width, etc. Or am I overcomplicating it?

I don't think this has to be perfect. Use the width of the component and a count of letters that's relatively safe. 
I rather see 80% correct than 80% weird.

**Comment by asangma** [comment]
Also, the **hyphen** is tricky because we don't know what the content is. If it's the name of an attribute, e.g. we wouldn't wanna add a character.

**Comment by asangma** [comment]
Hmmm...I feel like @pr3tori4n @driskull @jcfranco would have a better handle on [this](https://github.com/Esri/calcite-app-components/issues/430#issuecomment-545643193).

**Comment by driskull** [comment]
We use this in the API, can we use it here?

```scss
@mixin wordbreak() {
  /* For Firefox */
  white-space: pre-wrap;
  word-break: break-all;

  /* For Chrome and IE */
  word-wrap: break-word;
}
```

**Comment by asangma** [comment]
@driskull Minus the `white-space` rule, that's pretty much what we've got in production. As far as I can tell, `white-space: pre-wrap` doesn't affect our component.

**Comment by driskull** [comment]
We don't want to be doing calculations on width, word count or character count. We should solve this with CSS and not JS so that it's not brittle or difficult to maintain.

I think we should just go with the above breaking words. That snippet above will break even if its only one long word.

https://codepen.io/driskull/pen/JjjWQPV

**Comment by asangma** [comment]
@AdelheidF I saw that we are doing the same thing in LayerList as we are here. Do we still want to keep this issue?

**Comment by AdelheidF** [comment]
up to you...

**Comment by asangma** [comment]
Closing.
