### ISSUE TITLE
Enhancement: CalcitePickListItem - move key handler to label node

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#433]
### Description

Enhancement: CalcitePickListItem - move key handler to label node

The click event is on the label and it seems the keyup event should be as well.

### Acceptance Criteria 

https://github.com/Esri/calcite-app-components/pull/326#pullrequestreview-305369043

### Relevant Info 

https://github.com/Esri/calcite-app-components/pull/326#issuecomment-545134369

### Helpful Details

**Which Component:** CalcitePickListItem

**Comment by kat10140** [comment]
closing bc murgled
