### ISSUE TITLE
Bug: CalcitePickList - secondary action gets pushed outside container

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#439]
### Summary

Bug: CalcitePickList - secondary action gets pushed outside container

### Actual Behavior

Bug: CalcitePickList - secondary action gets pushed outside container

### Expected Behavior

Bug: CalcitePickList - secondary action stays within its container and text is either cut off or spans a second line.

### Reproduction Steps

1. See the calcite-pick-list demo

### Relevant Info 

![image](https://user-images.githubusercontent.com/1231455/67339789-bcdd9280-f4e0-11e9-8a59-1f547b8b8de4.png)

**Comment by asangma** [comment]
Installed.

**Comment by kat10140** [comment]
Yay good job Alern!
