### ISSUE TITLE
Tooling: Investigate why builds fail after bumping stencil.js to ^1.7.4

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#441]
### Description

Running any build that doesn't use the docs-config will cause the subsequent docs build to fail when upgrading stencil.js to ^1.7.4.

### Helpful Details

The release build was failing when I tried to do this.

**Comment by driskull** [comment]
This can be bumped to 1.7.4 now :)

**Comment by jcfranco** [comment]
lol 1.7.4 fixes the issue, will revert!

**Comment by driskull** [comment]
OMG stencil :stuck_out_tongue_closed_eyes:

**Comment by jcfranco** [comment]
This is no longer an issue w/ the latest NPM dependency updates.
