### ISSUE TITLE
Enhancement: (pick-list-item) disable summary in compact mode

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#447]
### Description
Disable the summary (`textDescription`) when `compact` is true.

### Acceptance Criteria 
Summary doesn't show when `compact`.

#### Desired New Behavior
Summary doesn't show when `compact`.

#### Desired Change to Look and Feel
Tighter vertical spacing.
Might could also reduce padding.

### Relevant Info 
#390 

### Helpful Details
**Which Component:** pick-list-item

**Comment by asangma** [comment]
MURGLED! @kat10140 Please verfee.

**Comment by kat10140** [comment]
Verifeeeeed

**Comment by asangma** [comment]
💥
