### ISSUE TITLE
Enhancement: calcite-popover - add option to hide caret

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#449]
### Description
Current look 
![image](https://user-images.githubusercontent.com/44481292/67417150-f532ae80-f57c-11e9-9a1d-c597fc6022d0.png)

In this workflow though I don't really have anything to point this popover at, So there should be no caret.

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by driskull** [comment]
@AdelheidF installed but `calcite-components` will need to do another release before we can use it.

**Comment by AdelheidF** [comment]
Looks good!
