### ISSUE TITLE
Enhancement: calcite-flow-item - add second header line

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#450]
### Description

design:
![image](https://user-images.githubusercontent.com/44481292/67417721-48f1c780-f57e-11e9-94cc-90a79df90ed6.png)

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by AdelheidF** [comment]
Duplicate of https://github.com/Esri/calcite-app-components/issues/406

**Comment by driskull** [comment]
https://github.com/Esri/calcite-app-components/pull/448

**Comment by AdelheidF** [comment]
@asangma @mitc7862 

Do we still want to show field name and field type in the header of the new map viewer attribute selection pop-up? Currently it shows below the header.
Not sure how it treats long names.

![image](https://user-images.githubusercontent.com/44481292/71752018-6078e680-2e32-11ea-8c65-c49c88eac1b9.png)

**Comment by mitc7862** [comment]
Yeah, That should be in the header. The component will need to accommodate that somehow.

**Comment by driskull** [comment]
Next release it should be able to.

**Comment by kat10140** [comment]
verified

**Comment by AdelheidF** [comment]
@mitc7862 

This is what it looks like with a long field name. I now can't see the field type at all. A hover doesn't show anything.

<img src=https://user-images.githubusercontent.com/44481292/72484715-0ffe7300-37ba-11ea-9771-736ab80e3992.png width=250/>

I guess we need to keep the line with the field name and type inside the body anyway. In that case I'm not clear what's the use of having it in the header then too.

<img src=https://user-images.githubusercontent.com/44481292/72484850-9450f600-37ba-11ea-9594-a90a27bc9547.png width=250/>

**Comment by mitc7862** [comment]
Yikes!

I consulted Alan and we agree that having the field type to the sub header isn't going to work. Can we the following?

![image](https://user-images.githubusercontent.com/12564905/72647321-2416b180-392d-11ea-97ac-5ca27ad3fc1b.png)
