### ISSUE TITLE
Bug: auto-generated CHANGELOG.md is incorrect - too many items in features.

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#452]
### Summary
`standard-version` is seems to be adding all commits that aren't prefixed with "fix:" to the features list in the CHANGELOG.md for that release.

### Actual Behavior
Features list in CHANGELOG.md are incorrect
### Expected Behavior
Features list in CHANGELOG.md only include commits that begin with "feat:"
### Reproduction Steps

0. Add some commits to master that don't follow conventionalcommits (e.g. no prefixes).
1. `npm version patch`
2. See generated CHANGELOG.md

### Relevant Info 
![image](https://user-images.githubusercontent.com/12614215/67433538-2ae78f80-f59d-11e9-9b0a-df82c9ac63e5.png)

**Comment by pr3tori4n** [comment]
@jcfranco let me know if you plan on cleaning up the CHANGELOG as a part of this PR or if you'd prefer to keep that separate. Currently the CHANGELOG contains a lot of noise that's not valuable for implementers.

**Comment by jcfranco** [comment]
This is actually working as expected. Look at the list of commits w/ `feat`/`fix` in the last release:

```
37a074ca fix: filter items not working with maquette
0b83c2cd fix: spacebar on secondaryAction
046393aa feat(value-list): added container. move attr out of host
e2d65fcf fix(panel): moved position:relative to :host
22c711dc feat(value-list): removed aria-disabled.
26027e2b feat(value-list): using Scrim for loading and disabled.
f5dd2a6b feat(panel): moved attr out of Host
2e9f6c2a feat(block): simplified loader insertion. Thanks @jcfranco!
a104f5e2 feat(block): removed unused method and associated import.
5ebb2d3c feat(block): updated prop description.
eb04e7f2 feat(block): updated VNode import updated.
4394bf1b feat(block): moved attr out of Host. Removed aria-disabled.
323f6dcb feat(panel): cleanup.
b12078c3 feat(panel): cleanup.
1f69c9f8 feat(panel): use Scrim for loading & disabled.
9ddab6aa feat(block): use Scrim for loading & disabled.
abe254c6 feat(value-list): stub for Scrim. Waiting on #381. (#362)
4e59c5a9 feat(value-list): Added disabled and loading props. Destructuring and added aria. (#362)
fffaa6e0 feat(all): Scrim destructure.
2e770186 feat(all): Scrim as functional component. Added styles inline.
3f1e8dc0 feat(block): added loading and disabled to destructuring.
333ee890 feat(block): added relative to .content (#358)
56f9dd2c feat(all): converted Scrim to FunctionalComponent.
a7d784a8 feat(all): blocking scrim. added option to turn off aria attibutes.
25d846e9 feat(all): blocking scrim + pick-list loading and disabled. TODO clean-up (#361 #357 #358 #359 #361 #362)
9a231012 feat(block): a11y aria labels for disabled and loading (#358)
d4caeca4 feat(flow-item, panel): added loading and disabled props, nodes, and styles. (#359)
20e5ccde feat(block): added disabled style. updated demo with way to toggle disabled property. (#358)
6978d8c8 feat(block): demo tweak
a5b87c04 feat(block): added calcite-loader and associated styles. Updated demo. (#358)
```

> let me know if you plan on cleaning up the CHANGELOG as a part of this PR or if you'd prefer to keep that separate. 

I'll let you handle this separately.

**Comment by pr3tori4n** [comment]
Something's not right here. We did a release yesterday. There's no way we merged in that many features in less than a day.

**Comment by jcfranco** [comment]
`standard-version` will process all commits between the last release and the current one (including the ones from a merge commit).

**Comment by jcfranco** [comment]
> There's no way we merged in that many features in less than a day.

If you click on the version you’ll see that the comparison is between 4.2.0 and 4.3.1 not 4.3.0 and 4.3.1. Something got botched while releasing.

**Comment by jcfranco** [comment]
I suspect out-of-sync tags are the culprit. Tags aren't fetched before generating the changelog, so if your dev setup isn't keeping them up to date, chaos ensues. I'll update the script to do this before generating the changelog.

**Comment by jcfranco** [comment]
I take that back, `standard-version` has some logic to get the latest tag. After closer inspection, the 4.3.0 release got botched: 

**expected (tag on `master`)**

```
* 37acb1e5 2019-10-23 | 4.3.1 (tag: v4.3.1, origin/master, origin/HEAD, master) [Harry Robbins]
```

```
* 8a1953a6 2019-10-17 | 4.2.1 (tag: v4.2.1) [JC Franco]
```

**actual (tag on branch)**

```
* a9c1a2ee 2019-10-22 | 4.3.0 [Matt Driscoll]
* 9d6466df 2019-10-22 | Revert to stencil 1.6.1 [Matt Driscoll]
* 54f29aaf 2019-10-22 | chore(README): fix deployment step typo [JC Franco]
| * caa7c55f 2019-10-22 | 4.3.0 (tag: v4.3.0) [Matt Driscoll]
| * 49a17fde 2019-10-22 | Revert to stencil 1.6.1 [Matt Driscoll]
|/
*   bf878ab0 2019-10-22 | Merge pull request #438 from Esri/asangma/pick-list-action-slot-417 [Matt Driscoll]
```
