### ISSUE TITLE
Bug: calcite-block-content padding got removed

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#454]
### Summary

Not sure if this is a feature or a bug, but it didn't behave like this until recently. I'm also not quite sure which element had the padding in the past.

The problem now is that the content of a calcite-block does not have any right and left padding and so my text/items start at the very left. All my containing div elements would need to have padding applied to fix this change and I use _a lot_ of them across my components.
If the calcite-block happens to contain a calcite-block-section then it's fine because this one has padding, as shown on the image below.

![image](https://user-images.githubusercontent.com/44481292/67452625-aadf1b00-f5d8-11e9-926e-66e2b5d375b7.png)

I want to make sure this is purpose before I change my styling everywhere.
Maybe I'm not using it correctly....

### Reproduction Steps

http://devext.arcgis.com/apps/mapviewer/index.html

### Relevant Info 

cc @asangma

**Comment by asangma** [comment]
Over to you @kat10140 for verfeeness.

**Comment by driskull** [comment]
This one good now @AdelheidF?

**Comment by kat10140** [comment]
closing. @AdelheidF please repoen if theres a issue
