### ISSUE TITLE
Bug: calcite-block-section -  styling updates for multi-line text

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#455]
### Summary

It's using `calcite-block-section` here with `toggle-display="switch"` and it doesn't look quite right for multi-line text next to the toggle button.

<img src=https://user-images.githubusercontent.com/44481292/67453908-132ffb80-f5dd-11e9-874b-dad749923921.png width=200/>

### Reproduction Steps

http://devext.arcgis.com/apps/mapviewer/index.html

### Relevant Info 

cc @asangma

**Comment by asangma** [comment]
@kat10140 verf plearse.

**Comment by kat10140** [comment]
![Screen Shot 2019-11-07 at 2 24 33 PM](https://user-images.githubusercontent.com/48069902/68432978-57d59e00-016a-11ea-91e7-6be31e8d73f8.png)
@asangma

**Comment by kat10140** [comment]
![Screen Shot 2019-11-07 at 2 27 43 PM](https://user-images.githubusercontent.com/48069902/68433197-cfa3c880-016a-11ea-94d6-76301a2bbf9b.png)
@asangma that might have happened bcuz of that super long, very creative string LOL

**Comment by kat10140** [comment]
![Screen Shot 2019-11-07 at 2 29 40 PM](https://user-images.githubusercontent.com/48069902/68433316-11347380-016b-11ea-87df-ea6859943bfb.png)
its working as long as no one puts in a 50 letter word. but also- if the input is super long it hides the checkbox/input below it
