### ISSUE TITLE
Bug: PickList Filter match is too aggressive

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#461]
### Actual Behavior
When filtering, some items are matched due to some attributes containing one or two letters
### Expected Behavior
Only the following pickListItem attributes are used for filtering: `textLabel`, `textDescription`, `value`, and `metadata`

**Comment by kat10140** [comment]
@AdelheidF want to check this in the current build?

**Comment by AdelheidF** [comment]
Seems to work as I would expect now. Just did a bit of testing.

**Comment by kat10140** [comment]
verified & closing
