### ISSUE TITLE
Docs: Clean up demo pages

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#463]
## Summary

Demo pages should be simple and focus on their own component.

## Measure of Success

**Pain point:**

Some demo pages have more than one component that is unrelated and adds complexity (e.g., [calcite-block.html](https://github.com/Esri/calcite-app-components/blob/master/src/demos/calcite-block.html). These should be cleaned up and possibly moved over to one or more advanced demo pages.

**Desired outcome:**

Simpler demo pages and, optionally, addition of advanced pages.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
verified
