### ISSUE TITLE
Enhancement: Allow non-collapsible calcite-block-section

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#464]
### Description

@subgan82 brought up having non-collapsible sections for cases where there is no need to hide additional block content. This would help maintain the visual structure of header/content in sections regardless of being collapsible or not.

### Acceptance Criteria 

Add `collapsible` property similar to `calcite-block`.

#### Desired New Behavior

Same as `calcite-block`, when non-collapsible the section header will be simple text.

#### Desired Change to Look and Feel

TBD @asangma @kat10140 

#### Out of Scope

N/A

### Relevant Info 

`calcite-block` should be used as an example of desired API and behavior.

**Comment by jcfranco** [comment]
Slight hiccup. `collapsible` in Block is false by default, so if we follow suit, this will be a breaking change for people using HTML markup and expect the default toggling behavior. There is no way to set !collapsible with an attribute besides omitting it, so this change will require users to add the `collapsible` attribute to preserve the existing behavior. 

We can introduce another property/attribute with the opposite default (e.g., `fixed`) or roll out the breaking change. 

cc @driskull @pr3tori4n

**Comment by subgan82** [comment]
> We can introduce another property/attribute with the opposite default (e.g., fixed) or roll out the breaking change.

Another property would be good to avoid the breaking change.

**Comment by pr3tori4n** [comment]
Trying to see the forest through the trees here. What essentially _is_ a non-collapsible block-section? Does the icon get removed? Is it just a container with padding at that point? If so, maybe this would best be solved by introducing the `<calcite-container>` component for general use container needs.

**Comment by jcfranco** [comment]
> What essentially is a non-collapsible block-section?

Section header + content, both always shown and can't be toggled. 

<img width="301" alt="Screen Shot 2019-10-31 at 11 34 43 AM" src="https://user-images.githubusercontent.com/197440/67976515-77515180-fbd3-11e9-8a6d-65f90b7c0416.png">

The container could help, but wouldn't take care of the header.

**Comment by asangma** [comment]
I think an immediate solution here could be to set the relevant sections to `open`.

Let us know if there's a strong reason to prevent users from having the ability to collapse a section.

**Comment by asangma** [comment]
@subgan82 ☝️

**Comment by asangma** [comment]
@subgan82 
I think an immediate solution here could be to set the relevant sections to `open`.

Let us know if there's a strong reason to prevent users from having the ability to collapse a section.

**Comment by subgan82** [comment]
@asangma having the option is useful in our wireframe it was without the toggle.

**Comment by subgan82** [comment]
Currently look like this 

![Screen Shot 2019-11-01 at 4 00 12 PM](https://user-images.githubusercontent.com/1017712/68056286-bdd0aa00-fcc0-11e9-91fd-d0862c6c183d.png)


cc: @phlorah

**Comment by asangma** [comment]
@subgan82 I will check with Mike, but it seems like it's keeping the sections as collapsible is not going to have a negative impact on the UX.

**Comment by rmstinson** [comment]
@asangma @subgan82 I will update the screens to make sure that collapsible sections are accounted for!

**Comment by jcfranco** [comment]
@asangma Is there a need for this still or should it be closed?

**Comment by asangma** [comment]
@jcfranco I'm cool if we close it.

**Comment by jcfranco** [comment]
Closing until further notice.
