### ISSUE TITLE
Refactor: Fix Stencil build warnings

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#466]
The following warnings started showing up after moving over to Stencil v1.7.4 in `calcite-value-list`, `calcite-pick-list` and `calcite-pick-list-item` E2E tests:

```
%c[STENCIL-DEV-MODE] color:#4c47ff;font-weight: bold 
The state/prop "selected" changed during rendering. 
This can potentially lead to infinite-loops and other bugs. 
```

See https://travis-ci.com/Esri/calcite-app-components/builds/133595791 for more details.

cc @kat10140

**Comment by driskull** [comment]
Installed 🎉

**Comment by jcfranco** [comment]
Verified locally.
