### ISSUE TITLE
New Component: Wrapper for calcite-switch that conforms to panel layouts

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#469]
### Description
We regularly need the `calcite-switch` component to act as a "row" in our panel interfaces. Out of the box, `calcite-switch` will now layout as needed. 

### Acceptance Criteria 
* require no additional styling
* use `calcite-switch`
* events? @jcfranco could use your help on this.

#### Desired Look & Feel
![image](https://user-images.githubusercontent.com/12503298/67609906-20b3c580-f744-11e9-9818-17afa512fbe8.png)

**Comment by asangma** [comment]
Per discussion from the last calcite-app-components meeting, this is a go.

**Comment by jcfranco** [comment]
![Thunderbirds+are+go+_79f02300ba769e21bb09807c0edcfb2a](https://user-images.githubusercontent.com/197440/67811445-09cde580-fa5a-11e9-9743-abae7b2a9d2b.gif)

**Comment by kat10140** [comment]
cc @asangma maybe move to calcite-components as an attribute?

**Comment by asangma** [comment]
Moving to this https://github.com/Esri/calcite-components/pull/248
