### ISSUE TITLE
Enhancement: could calcite-block-section get a loading state?

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#471]
### Description

When creating the HistogramSlider the app needs to calculate statistics and the histogram first. This takes some time. But waiting on the slider should not impact the entire panel. It only needs a waiting state for block-section.

![image](https://user-images.githubusercontent.com/44481292/67624160-15af7280-f7e2-11e9-9fa1-709239a611c0.png)

The FeatureFilter component currently displays text.
<img src=https://user-images.githubusercontent.com/44481292/67624172-3d9ed600-f7e2-11e9-8693-0be083b7b084.png width=200/>

http://devext.arcgis.com/apps/mapviewer/index.html

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by jcfranco** [comment]
@kat10140 A few questions:

* Should the loading only block the section's content? 
* Should I follow the pattern on Block or are there different design considerations? cc @asangma

**Comment by asangma** [comment]
@jcfranco @kat10140 Spoke with @AdelheidF and we may not need to do this just yet since Adelheid can use calcite-loader directly.

**Comment by jcfranco** [comment]
Based on ☝️, moving to next milestone.

**Comment by jcfranco** [comment]
> we may not need to do this just yet since Adelheid can use calcite-loader directly.

@asangma @kat10140 Any update on the priority for this one?

**Comment by AdelheidF** [comment]
I don't need this anymore since calcite-loader does what I need.
