### ISSUE TITLE
Bug: calcite-flow-item loading=true doesn't show animation on top of all nodes.

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#472]
### Summary

It looks like the loading box animation hides behind the active element. I don't quite understand what happens exactly. When the user clicks on a new renderer style tile it sets the loading state of the flow-item and then waits until the new renderer gets created. Once that's successful the tile updates its look a bit.
I would expect the active element to look greyed out as well and the animated box to show on top of all.

<img src=https://user-images.githubusercontent.com/44481292/67624370-940d1400-f7e4-11e9-94aa-180f21ab5c98.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/67624446-93c14880-f7e5-11e9-9a9a-42c20556392e.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/67624484-fc102a00-f7e5-11e9-9dcf-11d65af8fb1b.png width=200/>

### Reproduction Steps

1.

**Comment by driskull** [comment]
co-assigning @alansangma because this may be styles related to zIndex.

**Comment by driskull** [comment]
In this case it looks like those items have a higher z-index value. We should probably set the following on the `calcite-panel`.

```scss
:host([loading]) .container {
  position: relative;
  z-index: 1;
}
```

@asangma can you take a stab at it?

**Comment by asangma** [comment]
@AdelheidF Once this is in the release, you can verify in your app.

**Comment by AdelheidF** [comment]
Seems fine now
