### ISSUE TITLE
Enhancement: simple component just for loading state

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#473]
### Description

The image below shows a list of unique values for a field. When the user selects that the very first time the list of unique values needs to be generated which takes a bit of time. This does not affect the rest of the panel, so I do not want to place the entire flow-item into a loading state. Also, the entire Expression box here does not use any calcite component, such as calcite-block-section, that I could set the loading state on. Currently the list of unique values displays in a simple div element. I'm not sure if there is a calcite component with a loading state that I can remove all headers and icons from so it looks like what I need here. 

Could we add a simple calcite component without header, padding, icons, ... that I can set a loading state on?

<img src=https://user-images.githubusercontent.com/44481292/67626429-3c7ca180-f800-11e9-9408-c99ba5200fe7.png width=200/>

Currently it shows text

<img src=https://user-images.githubusercontent.com/44481292/67626580-f0caf780-f801-11e9-9322-437ed82ff1dc.png width=200/>

------------

Same issue for all smartMapping sliders that are contained in simple divs and take time loading because it needs statistics and histogram calculations.
<img src=https://user-images.githubusercontent.com/44481292/67626607-56b77f00-f802-11e9-8719-5e7750abdad9.png width=200/>

---------------

http://devext.arcgis.com/apps/mapviewer/index.html

### Helpful Details

**Which Component:**
**Example Use Case:**

**Comment by kat10140** [comment]
@AdelheidF Alan made a [functional Scrim component](https://github.com/Esri/calcite-app-components/blob/master/src/components/utils/CalciteScrim.tsx) that would make it easier for you to implement these loading states on components

**Comment by jcfranco** [comment]
@kat10140 It'll be have to be me made into its own component since functional components can't be used outside of this project. Is this something we'd like to do here or would it make sense to move to `calcite-components`? cc @asangma

**Comment by AdelheidF** [comment]
Maybe I can use `calcite-loader`. I'll try that today.

**Comment by AdelheidF** [comment]
`calcite-loader` is what I needed.
