### ISSUE TITLE
Bug: calcite-popover pointer placement

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#474]
### Summary

The placement of the triangle pointer doesn't seem correct. I assume there should be no grey shadow looking through between the popover box and the triangle.

![image](https://user-images.githubusercontent.com/44481292/67626872-79e42d80-f806-11e9-8814-24fafbe7d782.png)

![image](https://user-images.githubusercontent.com/44481292/67626875-8799b300-f806-11e9-9170-c6a23fec9d72.png)

### Reproduction Steps

http://devext.arcgis.com/apps/mapviewer/index.html

**Comment by kat10140** [comment]
@AdelheidF I've moved this issue over to calcite-components repo:
https://github.com/Esri/calcite-components/issues/201
