### ISSUE TITLE
Bug: Tip-manager adding to tip-manager slot doesnt seem to work

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#477]
### Summary

![image](https://user-images.githubusercontent.com/11093161/67783681-d7a39000-fa27-11e9-9fae-87266621e62d.png)

![image](https://user-images.githubusercontent.com/11093161/67783783-00c42080-fa28-11e9-8bbf-a4dff42883d1.png)

### Reproduction Steps

1.

**Comment by pr3tori4n** [comment]
@kat10140 could you please help me triage this? Repro steps or a link to an environment that demos the issue would help. This is working on our demo pages.
https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html

**Comment by driskull** [comment]
@kevindoshier is this related to adding a tip-manager to the shell?

We have a slot for it, but I don't think we've added any styles to position it at all. @alansangma I think you would be needed here to place the tip-manager where it should go with z-index and such.

**Comment by kevindoshier** [comment]
Yeah when adding it to the shell

**Comment by driskull** [comment]
https://github.com/Esri/calcite-app-components/pull/514 @asangma

**Comment by driskull** [comment]
@kevindoshier installed.

**Comment by driskull** [comment]
Closing. @kevindoshier reopen if still an issue.
