### ISSUE TITLE
Enhancement: stop splitting words on multi line list item label

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#478]
![Screen Shot 2019-10-29 at 10 47 57 AM](https://user-images.githubusercontent.com/48069902/67794674-45f14e00-fa3a-11e9-9f52-befa8542dcf4.png)

Words be splittin and it looks goofy. Let's add some CSS/logic so it don't do that anymore

**Comment by asangma** [comment]
LOL...is this the same as #455 ?

**Comment by kat10140** [comment]
No that one is about the switch toggle. This one is for words splitting between rows on a multiline item

**Comment by asangma** [comment]
I don't think we're gonna change this anytime soon. It's a reality of long strings with no browser-detected places to break.

`break-all` is also what we've been doing in LayerList for some time now.

**Comment by kat10140** [comment]
closing. this was discussed a long time ago and never closed.
