### ISSUE TITLE
Bug: calcite-pick-list adds padding to some items if sorted

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#479]
### Summary
When sorting the attribute selection pick-list some pick-list-items get a padding of 7. I'm not sure where this is coming from and I'm pretty sure it's not something I set.

before
![image](https://user-images.githubusercontent.com/44481292/67811650-7fd24c80-fa5a-11e9-9e0f-ef0e8ddadb24.png)

after
![image](https://user-images.githubusercontent.com/44481292/67811613-692bf580-fa5a-11e9-9cf7-a0e31b562f51.png)

with wrong padding
![image](https://user-images.githubusercontent.com/44481292/67811735-a85a4680-fa5a-11e9-97c2-8a165c68aecd.png)

correct
![image](https://user-images.githubusercontent.com/44481292/67811780-c0ca6100-fa5a-11e9-956e-be89a67e4bd3.png)

It seems like the compact="false" is causing it
![image](https://user-images.githubusercontent.com/44481292/67811863-f40cf000-fa5a-11e9-80e6-2ef8977ffb39.png)

### Reproduction Steps

https://devext.arcgis.com/apps/mapviewer/index.html

**Comment by asangma** [comment]
@AdelheidF I'm not sure how to repro this.

**Comment by AdelheidF** [comment]
Not sure if this is a styling issue alone. Can we start by investigating why `compact=false` gets added? I think this is causing the issue.

**Comment by asangma** [comment]
Thanks @AdelheidF.
@pr3tori4n This might be something for you to look at?

**Comment by AdelheidF** [comment]
This seems to have fixed itself. I don't see it anymore.

**Comment by pr3tori4n** [comment]
@AdelheidF can we close this issue?
