### ISSUE TITLE
New Component: Container component

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#482]
### Description
This component would act as a container for other elements to be placed inside.
This component's primary purpose is to provide consistent spacing and visual boundaries for what's inside it. This will help normalize and avoid duplicating container styles across components. It will also provide an abstraction layer where we can build upon container logic. Additionally, it could provide a utility to consumers of our components for when they need a container to house custom markup that doesn't come with additional functionality that our other components currently provide.

#### User Stories
**Insert Adelheide's Block use case**
#### Desired Behavior
The container should have some configuration to handle scenarios where there are nested containers, to avoid scenarios of doubling up on spacing and other visual boundaries.
#### Desired Look & Feel
Alan to design a basic 'container' with certain optional states (e.g. nonPadded, noBoundary)
#### Out of Scope 
Any special functionality we think might belong on a container can be an enhancement. Examples might be `dismissible`, or `resizable`.
### Helpful Details
TBD: If we only intend to use this as an internal abstraction, we may want to make a functional component. If we want to provide this utility to app devs, we'd want a custom element.
TBD: We should also evaluate if this would better be housed in `calcite-components` or if they have an existing component that fits these needs.

**Comment by pr3tori4n** [comment]
@kat10140 @asangma  Here is a `container` component issue. Please vet my requirements and update as needed. I've assigned to Eberhardt milestone.

**Comment by driskull** [comment]
This can be closed @asangma ??
