### ISSUE TITLE
New Component: DNDList/SortableList

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#483]
### Description
We want to make a reusable drag and drop component, as we are implementing something similar (via sortable) in many other components.  Having it as its own component will provide consistency and makes drag and droppable "lists" easier to implement in the future. 

#### User Stories
As an app developer, I want to be able to easily implement drag and drop within items in a panel. 

### Acceptance Criteria 
- Drag and drop container
- Wrapper for DnD items

#### Desired Behavior
To be able to drag and drop items vertically that are organized in a list like fashion.  This can be actual lists, block sections, etc. 

#### Desired Look & Feel
Items to have distinct wrapper and drag icon. (Alan?)

**Comment by kat10140** [comment]
reassigning to @pr3tori4n (seems like you have a little more time right now)

**Comment by kat10140** [comment]
Audit which components can be used with this. @asangma @pr3tori4n

**Comment by pr3tori4n** [comment]
Block Components is the only addition for now.

**Comment by pr3tori4n** [comment]
hey @kat10140 could you setup a kickoff meeting for this early next week? I think this will probably end up falling into grob glob.

**Comment by kat10140** [comment]
Goal:
- broad story: general use drag and drop 
  - keyboard navigation paired with sortable (Adds event handlers for arrow keys)
  - consistent UX for mouse and keyboard users
- block is our immediate use case 
- as for wireframes, look at value list for now
  - v1 is just a vertical list, no grid

QA test case to evaluate heavily nested components. 

Harry make custom component for handle? Maybs?
Drag enabled property (or some prop) will still be passed down. This is how we'll use the space functionality.

Check in with Dhrumil with what he did on popup configuration? (Dragging whole block vs just using the handle). 

@kat10140 put all this in the first comment

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
Verified!! Woohoo!
