### ISSUE TITLE
Question: Docs

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#486]
CAC Doc notes

Shell 
- Leading and trailing slots can be more descriptive 
- Wording is weird 
- If any are optional or required, note (Matt)

Demo: demo all 5 slots (mainly top 4)
- Put text so we can see where each ones goes in the demo 

Value list and pick list
- Which ones are required and which are optional (all optional) make clear 
- Document the default slot

Pick list and value list item
- Values required field (filter and selections just won’t work at lal without value)
- Which fields are required and optional. Required are label and value. Others optional 
- Lists are controlling the Icon (end user doesn’t need to set this) set from the parent component
- Event description could get more info about the data you get back form it (describe the detail property on event object) document the structure (its a map of the value to html element)

Shell-panel 
- Layout property and its possible values 
- (Might need a code change here)
- If the panel is put in the leading panel in the shell, why should we have to set this prop
    - Can we automate this prop? 
    - Beef up description (what changes when going through leading and trailing? Icons? Margin and padding?)
- Describe the event data structure
- Document the default slot
- Go into description of action bar slot more. Where does it end up on the panel? (Leading vs trailing?)
    - Describe the default vs action bar/pad layout 

Action-bar
- Talk about layout leading vs trailing. (More of a discussion with Matt. Is this supposed to only be usable in shell panel?)
- Doc required vs optional (layout should default to something rather than being undefined)
- Detail type of data we get back on events
- Doc default slot

Maybe put screenshots in readies??

Popover
- Required vs optional 
- Reference element req. 
- Default slot
- Methods 
-

**Comment by driskull** [comment]
![image](https://user-images.githubusercontent.com/1231455/68329784-df49e100-0086-11ea-837a-ebe843236626.png)

[patch.diff.zip](https://github.com/Esri/calcite-app-components/files/3816305/patch.diff.zip)

**Comment by driskull** [comment]
@kat10140 this is how we can set optional/required props:

```tsx
/**
   * Arrangement of the component.
   */
  @Prop({ reflect: true }) layout?: CalciteLayout;

  /**
   * Used to set the component's color scheme.
   */

  @Prop({ reflect: true }) theme!: CalciteTheme;
```

**Comment by driskull** [comment]
@kat10140 can we close this issue if these are just notes?
