### ISSUE TITLE
Enhancement: Update spacing for Panel, Blocks, and Action to align with calcite components

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-app-components#487]
### Description
- Simplify the spacing of nested container elements

### Acceptance Criteria 
- text is consistently styled and aligned
- hierarchy of nested components is clear

#### Desired New Behavior
- No behavior change

#### Desired Change to Look and Feel
- Will post design

#### Out of Scope
- We aren't considering any updates that would require changes to the structure of the components themselves.

### Relevant Info 
- This enhancement was requested by the calcite component team in order to achieve greater design consistency across the two resources.  

### Helpful Details

**Which Component:** Block, Block section, Panel, ActionBar, ActionPad, Action
**Example Use Case:** n/a

**Comment by asangma** [comment]
The update that removed padding causes more issues than it solves (#454).
Bringing it back as this issue suggests (and possibly enhancing it) will will negate the need to add a padding prop (#457).

**Comment by asangma** [comment]
Also re #482

**Comment by asangma** [comment]
re #186

**Comment by asangma** [comment]
@mitch We can review on my local to verfee.

**Comment by kat10140** [comment]
thumbified
