### ISSUE TITLE
Enhancement: Scalability - nested components with the same slot names

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#498]
### Description

A component that uses a slot name and nests another component with the same slot name can be problematic in identifying if the slot is populated.

### Acceptance Criteria 

Come up with a scalable way to detect if a component's slot is populated and not apart of a nested component

### Helpful Details

https://github.com/Esri/calcite-app-components/pull/497
https://github.com/Esri/calcite-app-components/issues/409

**Which Component:** All or any that nest other components with the same slot name

**Example Use Case:**

```html
<calcite-flow-item heading="What are the most popular commute alternatives?">
            <div>
              <h2>Content</h2>
              <calcite-pick-list>
                <calcite-action slot="menu-actions" indicator label="Cool" text="Cool"
                  ><svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                    <path d="M14 4H2V3h12zm0 4H2v1h12zm0 5H2v1h12z" />
                  </svg>
                </calcite-action>
              </calcite-pick-list>
            </div>
          </calcite-flow-item>
```

**Comment by asangma** [comment]
There are possibly also issues when the slot name is not the same, e.g. flow-item's footer-actions slot being passed into panel's footer slot.

Seems like the DOM is not respected or something.

**Comment by driskull** [comment]
@jcfranco do we have a stencil support issue for this? It might be good to check with them and see how we should proceed with this one.

**Comment by jcfranco** [comment]
Installed. @driskull Can you help verify?

**Comment by driskull** [comment]
Verified using example in issue! Looks good. Thanks @jcfranco !!!
