### ISSUE TITLE
Enhancement: Refactor all `getAttribute` and `hasAttribute` methods

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#501]
### Description
Maquette and other hyperscript libraries set properties on html elements and not attributes, even if the JSX syntax is similar to HTML attributes.

This means if we're using  `getAttribute` and `hasAttribute` in first-render lifecycle functions, it can cause bugs where the property and attribute are our of sync. So we need to rely on the properties over the attributes for discerning component logic.

### Acceptance Criteria 
This is mainly a refactor. The use of the above methods should be replaced by dot notation lookup of an elements property, and testing against undefined, respectively.
#### Desired New Behavior
The behavior should remain the same.
#### Desired Change to Look and Feel
The styles should remain the same.

### Helpful Details
**Which Component:** Any that use one of those methods.

**Comment by kat10140** [comment]
@driskull should all this have been taken care of in the merge?

**Comment by driskull** [comment]
Yes

**Comment by pr3tori4n** [comment]
@kat10140 Please verify.

**Comment by kat10140** [comment]
verified!
