### ISSUE TITLE
Enhancement: Sticky Filter

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#503]
### Description
As filter is now, if one scrolls with the pick or value list, the filter scrolls as well. We want the filter to stick at the top of the list at all times.

### Acceptance Criteria 
Sticky filter

#### Desired New Behavior
Filter to stick at top of panel when scrolling 

#### Desired Change to Look and Feel
Sticky

**Comment by pr3tori4n** [comment]
In code review.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
gonna verify this tomorrow when we release again in the new mapviewer

**Comment by kat10140** [comment]
verified
