### ISSUE TITLE
Bug: ActionPad got missed during the styling update

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#506]
### Summary
Remove the extra space.

### Actual Behavior
<img width="391" alt="Screen Shot 2019-11-06 at 7 18 24 AM" src="https://user-images.githubusercontent.com/12503298/68311014-c4b34000-0065-11ea-8cbe-ff25286e33cf.png">

### Expected Behavior
![image](https://user-images.githubusercontent.com/12503298/68311133-fcba8300-0065-11ea-9a74-9b478989de24.png)

### Reproduction Steps

1. Demo

### Relevant Info 
Can this be in a patch?

**Comment by asangma** [comment]
Verfee please!

**Comment by kat10140** [comment]
🤙🏼
