### ISSUE TITLE
Bug: calcite-block-section padding 

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#507]
### Summary

'Classify data' is a calcite-block-section

closed
![image](https://user-images.githubusercontent.com/44481292/68325601-9beb7480-007e-11ea-94cb-afcf25d07342.png)

open
![image](https://user-images.githubusercontent.com/44481292/68325663-b9b8d980-007e-11ea-8a59-e988febfc7f9.png)

![image](https://user-images.githubusercontent.com/44481292/68325767-ee2c9580-007e-11ea-96bf-aba2a9a12b2a.png)

cc @asangma 

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
nice now...

<img src=https://user-images.githubusercontent.com/44481292/68350346-dec83f00-00b4-11ea-8e4f-e97460b5afc7.png width=200 />

**Comment by AdelheidF** [comment]
Though looks like calcite-switch has a right margin. Why?

<img src=https://user-images.githubusercontent.com/44481292/68350470-47afb700-00b5-11ea-8bdd-509f7640ced7.png width=300/>

**Comment by driskull** [comment]
@AdelheidF that styling is coming from the switch itself so probably a good `calcite-components` question for @macandcheese

**Comment by AdelheidF** [comment]
One more thing.

If you have a longer text in the block-section header the toggle button is higher than the top line. That doesn't look right...

<img src=https://user-images.githubusercontent.com/44481292/68367218-0980ba80-00ea-11ea-9e6f-46dd6bc72b67.png width=200/>

![image](https://user-images.githubusercontent.com/44481292/68367260-20bfa800-00ea-11ea-9523-47867171078e.png)

**Comment by AdelheidF** [comment]
.. and another thing

There should be more space between the text and the toggle button.

<img src=https://user-images.githubusercontent.com/44481292/68379767-58871980-0103-11ea-8876-488a450d45b5.png width=200/>

**Comment by driskull** [comment]
@AdelheidF can we move these to a new issue?
