### ISSUE TITLE
Enhancement: Panel. Add scale property to set dynamic height

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#513]
### Description
Add an optional property to **panel** which would result in defining the max-height.

Proposal
```
/** specify the scale of the panel, defaults to m */
  @Prop({ reflect: true, mutable: true }) heightScale: "s" | "m" | "l" = "m";
```

```
.container {
  ...
  overflow: auto;
}

:host[height-scale="s"] .container {
 max-height: 33vh;
}

// etc
```

### Acceptance Criteria 
User can define panel scale.
Works with pick-list with a sticky header. (#509)

#### Desired Change to Look and Feel
~Could also add a style to set the width dynamic in line with the shell-panel's responsive width.~
This would need to see an update in calcite-components popover which currently has a max-width set.

#### Out of Scope
Setting panel width.

### Helpful Details

**Which Component:**
**Example Use Case:**
**map viewer beta**
- Currently devs are having to set heights, etc. for each panel...specifically inside popovers.
- Symbol styler could use a mutable scale prop

**Comment by driskull** [comment]
@asangma so this would be for panel, not popover?

**Comment by asangma** [comment]
@driskull Ya.

**Comment by asangma** [comment]
@driskull @kat10140 
I'm gonna start on this for the next release.
I am thinking the property would be specific to height. I also think that down the road a panel could have a property to allow for dynamic width similar to shell-panel for cases when it is in a popover.

Updating initial comment with proposed prop name.

**Comment by driskull** [comment]
Sounds good. I can help if needed. 👍

**Comment by driskull** [comment]
@asangma I don't think we want the default to be "m" or any value right? Because the flow-manager we want to take up 100% height by default. Seems like they should opt into the sizes right?

**Comment by kat10140** [comment]
i tried editing the heightScale in the console in the demos and nothing is happening 😫
