### ISSUE TITLE
Enhancement: Use CSS vars for calculations

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#516]
### Description
We're currently using Sass vars in [_layout.scss](https://github.com/Esri/calcite-app-components/blob/master/src/assets/styles/_layout.scss#L9) for our different spacing sizes.

```
--calcite-app-side-spacing-three-quarters: #{floor($side-spacing * 3/4)};
```

We should use the CSS var in these calculations, so that if/when we expose them users can change just the top-level CSS vars and not need to run a Sass build.

### Acceptance Criteria 
Depend more on CSS vars for calculated values.

#### Desired New Behavior
```
--calcite-app-side-spacing-three-quarters: calc(var(--calcite-app-side-spacing) * 3/4);
```

#### Desired Change to Look and Feel
No change.

### Helpful Details

**Which Component:** All
**Example Use Case:** Theming.

**Comment by asangma** [comment]
VARY FIE!

**Comment by kat10140** [comment]
lewks gewd!
