### ISSUE TITLE
Bug: value-list-item :last-child shouldn't have a box-shadow/border

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#517]
### Actual Behavior
![Screen Shot 2019-11-07 at 8 28 37 AM](https://user-images.githubusercontent.com/12503298/68407641-c7329a00-0138-11ea-824e-86c634f123f2.png)

### Expected Behavior
No shadow/border on last one.

### Reproduction Steps

1. demo

**Comment by asangma** [comment]
@kat10140 May need to artificially add a bit of border to the bottom of the value-list in the full-window shell demo to see the diff.

**Comment by kat10140** [comment]
verfyyyyd
