### ISSUE TITLE
Bug: Action. Icon is a little high

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#518]
### Actual Behavior
![Screen Shot 2019-11-07 at 8 33 47 AM](https://user-images.githubusercontent.com/12503298/68408015-68215500-0139-11ea-8336-fec541f5fb82.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/12503298/68408058-7ec7ac00-0139-11ea-8d0a-8878219c1b95.png)

Centered.....ahhhh...

### Reproduction Steps

1.

**Comment by kat10140** [comment]
katy pls  verfeeee

**Comment by kat10140** [comment]
verified!
