### ISSUE TITLE
Enhancement: Update base pixel size from 15px to 16px

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#519]
**~WAIT for Map Viewer meeting approval.~**

### Description
**From Slack**
>I have some design and consistency reasons to change our base pixel value (see  src/assets/styles/_layout.scss), but would like to get your thoughts.
And anybody else’s thoughts too.

>I think it might be good to bump the size to 16px. Our icons are generally 16px, so that might be good. It’s also a really minor change.

>I think we’d discussed 12px. And while this makes the designs nice and tight, it does make a fair number of our interface elements a bit small for touch interaction.

This would mean that almost all of our size ratios would be even numbers, e.g. `-half` would be 8 instead of being 7.5 or needing `floor`.

#### Desired Change to Look and Feel
Another pixel.

**Which Component:** All

**Comment by asangma** [comment]
@kat10140 VERF!

**Comment by kat10140** [comment]
verfiiiiiidd
