### ISSUE TITLE
Enhancement:  pick-list-item action styling

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#524]
### Description

I noticed when hovering a pick-list-item the action on the right has a BG color. Shouldn’t it be transparent?

Why BG color on circle icon?

![image](https://user-images.githubusercontent.com/1231455/68434511-fd3e4100-016d-11ea-9f32-ddf8a65484f8.png)

#### Desired Change to Look and Feel

Transparent BG on icon

**Which Component:** CalcitePickList/CalciteValueList

**Comment by kat10140** [comment]
https://github.com/Esri/calcite-app-components/issues/309

**Comment by pr3tori4n** [comment]
Update both list demos to add appearance prop to slotted actions.
