### ISSUE TITLE
Bug: calcite-block + calcite-block-section focus box cut off

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#527]
### Summary

block closed
<img src=https://user-images.githubusercontent.com/44481292/68443228-2f5c9c80-0188-11ea-97e2-a497652eabd1.png width=300/>

block open with focus on header. The calcite-block-section seems to start 1 pixel too high.
<img src=https://user-images.githubusercontent.com/44481292/68443211-1fdd5380-0188-11ea-9887-c726c2918b17.png width=300/>

Only happens if the header text needs two lines.

cc @asangma 

### Reproduction Steps

1.

**Comment by pr3tori4n** [comment]
@pr3tori4n review the demo after docs merge.

**Comment by pr3tori4n** [comment]
Still seeing this with the latest docs push.
https://esri.github.io/calcite-app-components/demos/calcite-block.html
Moving to Fern.

**Comment by asangma** [comment]
This should be handled by the PR (#615) and is the parallel issue to #573. @AdelheidF We should be able to close this.

**Comment by AdelheidF** [comment]
I still see it on devext today.

![image](https://user-images.githubusercontent.com/44481292/70651984-b331fa80-1c06-11ea-87ed-e5eb30666f0a.png)

**Comment by kat10140** [comment]
This looks good on my end

**Comment by AdelheidF** [comment]
Did you try this case with calcite-block containing a clacite-block-section with a swith and a 2 line text?

**Comment by kat10140** [comment]
@AdelheidF it looks fine for me on Chrome
![Screen Shot 2019-12-20 at 10 04 15 AM](https://user-images.githubusercontent.com/48069902/71280473-2119a880-2310-11ea-9ece-dbc0ba27980a.png)

**Comment by kat10140** [comment]
@driskull @asangma should I keep this open and move to the next milestone? Fern closes today

**Comment by driskull** [comment]
Yep!

**Comment by asangma** [comment]
@AdelheidF @jcfranco 
I'm not seeing the focus issue anymore. @kat10140 Can you confirm.

However, it looks like with a block-section with `toggle-display="switch"`, the label can't be focused. The switch can be focused, using the keyboard to switch it doesn't hide/show the section content.

@jcfranco I will make a separate issue for this.

**Comment by AdelheidF** [comment]
> using the keyboard to switch it doesn't hide/show the section content.

yes, seeing the same thing on devext

keyboard enter
![image](https://user-images.githubusercontent.com/44481292/73677168-89c3a700-466a-11ea-891c-8293bb353fd6.png)

mouse click
![image](https://user-images.githubusercontent.com/44481292/73677191-947e3c00-466a-11ea-84fe-5cf0378c860a.png)

**Comment by kat10140** [comment]
Keyboard switch is working now and I don't see Adelheid's issue but I do see another one I'll make a separate issue

**Comment by AdelheidF** [comment]
Still happening with 5.3.2. The bottom border of the focused block header is weird.
I assume it's the block + block-section-toggle combo.

![image](https://user-images.githubusercontent.com/44481292/75077293-25507680-54b7-11ea-85ed-39e195ee3d54.png)

![image](https://user-images.githubusercontent.com/44481292/75077417-87a97700-54b7-11ea-864b-669f0c3c1a2c.png)
