### ISSUE TITLE
Enhancement: Add property to toggle opening/closing of TipManager

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#530]
### Description

Enhancement: Add property to toggle opening/closing of TipManager

### Acceptance Criteria 

Currently, the tip manager is closed by adding `hidden` attribute but because we need to prevent the transition animation from happening when reopening, we should have a property that handles opening/closing the tip manager.

### Relevant Info 

This is what happens when reopening after paginating:

![Nov-08-2019 11-08-06](https://user-images.githubusercontent.com/1231455/68503601-1d2a3f00-0218-11ea-85c7-b71dc187ff08.gif)

### Helpful Details

The `@state direction` needs to be removed when closing the TipManager. Since we need to set this, we need a property to open/close.

**Which Component:** TipManager
**Example Use Case:**

Propose adding a `closed` or `dismissed` property to the TipManager.

**Comment by driskull** [comment]
cc @asangma @kevindoshier

**Comment by kat10140** [comment]
Verified
