### ISSUE TITLE
Tooling: Set up SCSS linting + auto-fixes

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#531]
## Summary

It would be useful to lint our styles and auto-fix whenever possible.

## Measure of Success

**Pain point:** Sass is not being linted and can lead to inconsistencies.

**Desired outcome:** Linting + auto-fixing on commit.

### Resources 

https://github.com/Esri/calcite-app-components/tree/jcfranco/set-up-style-linting

**Comment by jcfranco** [comment]
Installed.

@driskull Can you help verify? There's also a VSCode plugin: https://github.com/shinnn/vscode-stylelint

**Comment by driskull** [comment]
Works. extension is nice too.

![image](https://user-images.githubusercontent.com/1231455/69461966-9fdcef00-0d2c-11ea-8efe-00b37b632dbf.png)
