### ISSUE TITLE
Bug: radio buttons shouldn't be allowed to deselect

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#536]
### Summary
radio buttons in pick list can be deselected when  clicked in pick list. this aint right

### Actual Behavior
![radio buttons](https://user-images.githubusercontent.com/48069902/68513951-3b506900-0231-11ea-9840-a84b772fb087.gif)

### Expected Behavior
no deselect

### Reproduction Steps

1. https://esri.github.io/calcite-app-components/demos/calcite-pick-list.html click a selected radio button

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
verified!
