### ISSUE TITLE
Enhancement: Figure out aria-role for valueList

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#538]
### Description
`aria-role="checkbox"` is on the Host for the list-items. But it'd be more appropriate on the icon. However value lists don't have an icon. Need to find another solution.
#### Desired New Behavior
none. This is more of a refactor. Functionality shouldn't change. A11y should still pass.
#### Desired Change to Look and Feel
none
### Relevant Info 
its invalid on the label element.
### Helpful Details
**Which Component:** `calcite-value-list-item, calcite-pick-list-item`

**Comment by kat10140** [comment]
verified
