### ISSUE TITLE
Bug: Block with control has collapse icon in Edge

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#540]
### Summary
Block section with a control still has a collapse icon in Edge. 

### Actual Behavior

![Capture](https://user-images.githubusercontent.com/48069902/68608541-0b3edb00-0468-11ea-9d0d-3a09169de9bf.PNG)

### Expected Behavior
No collapsible icon when section has a control

### Reproduction Steps

1. go to https://esri.github.io/calcite-app-components/demos/calcite-block.html in edge

### Relevant Info 
The New Map Viewer doesn't work in Edge, so this isn't urgent for MV, but just in general for our components

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
@jcfranco the icon is gone! On hover, expand label still shows and toggles on click in the console. 


![Screen Shot 2019-11-25 at 9 37 48 AM](https://user-images.githubusercontent.com/48069902/69564419-dd798c00-0f67-11ea-8145-e45159a17e99.png)
![Screen Shot 2019-11-25 at 9 41 26 AM](https://user-images.githubusercontent.com/48069902/69564425-dfdbe600-0f67-11ea-921d-dbcd34899c45.png)

**Comment by kat10140** [comment]
The icon is removed! We're still getting expand/collapse labels on hover over the 'test control' where the expand button/icon would have been

![Screen Shot 2019-11-25 at 10 59 08 AM](https://user-images.githubusercontent.com/48069902/69569608-d7d57380-0f72-11ea-9370-77730259bd23.png)

![Screen Shot 2019-11-25 at 10 59 31 AM](https://user-images.githubusercontent.com/48069902/69569614-dad06400-0f72-11ea-8171-9519788a6c6a.png)

**Comment by jcfranco** [comment]
That's expected. You'll need to set `title` on the control element if you want a different tooltip. Is this from the demo page? I can update it so that elements using the control slot set a custom tooltip.

**Comment by kat10140** [comment]
@jcfranco that is from the demo page. I'll close this issue and if you think that's important then we can do it.
