### ISSUE TITLE
Bug: CalciteValueList - Selecting last item doesn't show any visual indication.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#542]
### Actual Behavior

The last selected item doesn't have any visual indication of selection.

### Expected Behavior

The last selected item gets represented visually

### Reproduction Steps

1. Go to the following `demos/calcite-value-list.html`
2. Click the last item under the multiple list
3. Notice that there is no outline on the item yet it is selected in the event.

### Relevant Info 
N/A

**Comment by asangma** [comment]
Installed.

**Comment by asangma** [comment]
🎉
