### ISSUE TITLE
A11y: Selected state of CalciteValueList is a little too subtle

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#543]
### Summary

Does the selected state of the value-list seem a little too subtle? At first, it wasn’t easy to tell which was selected or not.

### Actual Behavior

The selected visual indication can be mistaken for an outline or not recognized at all.

### Expected Behavior

More distinct representation between which items are selected or not selected.

### Reproduction Steps

1. View `demos/calcite-pick-list.html`
2. Select an item
3. Notice how it doesn't differ enough from an unselected state

### Relevant Info 

![image](https://user-images.githubusercontent.com/1231455/68626224-b911b000-048f-11ea-9dfa-5042e94af058.png)

### Working W3C Example/Tutorial 

N/A

**Comment by asangma** [comment]
@driskull  Would you say that #615 would handle this?

**Comment by driskull** [comment]
I think it would help. The selected state of an item is still just a 1px border. Is that enough for a user to understand the item is selected? Might want to test that.

**Comment by driskull** [comment]
IMO, its still a bit difficult to identify if the 3rd one is selected or not.

![image](https://user-images.githubusercontent.com/1231455/70642423-09497280-1bf4-11ea-9eea-75cfede52213.png)

**Comment by driskull** [comment]
@mitc7862 please advise.

**Comment by driskull** [comment]
@asangma should the selected item's background color be different? Should there be a thick border-left to identify a selected item?

**Comment by driskull** [comment]
It's better, but I don't think the "selected" state is still quite enough. I'll close the issue but I have a feeling this may come up from UX testing.
