### ISSUE TITLE
Enhancement: document default slots: pick and value list

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#545]
### Description
Document the default slot for the pick and value list. While you're in there maybe go ahead and note what properties are optional and what are required.

#### Which Component
Pick-list and value-list

**Comment by driskull** [comment]
We don't document any default slots. Should we start doing so?

**Comment by pr3tori4n** [comment]
I definitely think so. It's a quality of life improvement for someone trying to implement our components, and aren't super clear how they work.

**Comment by kat10140** [comment]
verified
