### ISSUE TITLE
Bug: calcite-block loading not 'hiding' slider handles

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#546]
### Summary

The slider handles don't appear grey.

<img src=https://user-images.githubusercontent.com/44481292/68637036-4b2ab000-04b2-11ea-8d39-9421bc8b490a.png width=200/>

cc @asangma 

### Reproduction Steps

Go to new map viewer, select location style, open transparency block, select 'new Expression' as attribute. Only enters the loading state the first time you do this because it needs to request a feature.

**Comment by driskull** [comment]
Seems like the zIndex is not being respected somewhere.

**Comment by kat10140** [comment]
katy verifyu
pls

**Comment by AdelheidF** [comment]
It's good now

<img src=https://user-images.githubusercontent.com/44481292/70368331-34cc0600-185e-11ea-85f0-bfa080892cfa.png width=200/>

**Comment by kat10140** [comment]
Verified. Thank you Adelheid!
