### ISSUE TITLE
Bug: panel. Don't render header leading or trailing nodes when empty

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#547]
### Summary
re: header. Only render related notes when content is passed to leading and trailing slots in header.

### Actual Behavior
When leading slot is empty, flex justify-content still acts like there's stuff in there.
![image](https://user-images.githubusercontent.com/12503298/68703325-45c77700-053f-11ea-866c-e99bfe541bb6.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/12503298/68703334-4bbd5800-053f-11ea-845b-4f87a25a2e23.png)

### Reproduction Steps

1.

**Comment by driskull** [comment]
@asangma if we remove the nodes when the slot is not populated the `close` button would be to the left. How would we address that?

**Comment by asangma** [comment]
The header is `justify-content: space-between`. It should automatically layout like the above screen if there's no leading slot. I will have to check what it looks like when there's not trailing. Either way, it looks weird currently.

**Comment by asangma** [comment]
@kat10140 Please verfee. :)

**Comment by kat10140** [comment]
verified!
