### ISSUE TITLE
Bug: [Block] `disabled` does not prevent tab focusing on children

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#548]
### Summary

When a `calcite-block` is disabled, its content can still be focused and interacted with via keyboard.

### Actual Behavior

Disabled `calcite-block` only blocks mouse interaction.

### Expected Behavior

Disabled `calcite-block` does not allow mouse nor keyboard interaction.

### Reproduction Steps

Simple test case:

```html
<calcite-block heading="Header" open disabled>
  <button>I can be tabbed into!</button>
</calcite-block>
```

**Comment by driskull** [comment]
@jcfranco if the block tabIndex is set to "-1" does that fix it?

**Comment by jcfranco** [comment]
Yes, but that would prevent users from toggling the disabled content on/off, which I believe we want to keep as a user convenience. 👈 @asangma?

**Comment by driskull** [comment]
This issue may apply to other `disabled` components as well. I don't think we set any tabIndex when disabled.

**Comment by jcfranco** [comment]
I have not found a reliable solution that lets us keep the header interactive **AND** prevents the content from being keyboard-navigable.

The promising wicg-inert prollyfills ([WICG](https://github.com/WICG/inert) & [Google](https://github.com/GoogleChrome/inert-polyfill)) do not help when set inside a shadow DOM context and have [their](https://github.com/WICG/inert#performance-and-gotchas) [own](https://github.com/GoogleChrome/inert-polyfill#limitations) caveats (performance and functionality-wise).

Setting `tabIndex=-1` or `inert` on the host component would get us closer to preventing keyboard navigation when disabled, but it does mean the block is no longer interactive/collapsible.

I see the following options:

1. Leave block in its current state, prevent user from expanding/focusing†, but still allow programmatic toggling.
2. Collapse block, prevent user from expanding/focusing†, and visually indicate it's not interactive.

† would use either `tabIndex` (preferred) or `inert`

@asangma @mitc7862 @kat10140 Please advise.

**Comment by driskull** [comment]
@jcfranco can you set `tabIndex="-1"` on the container of the content and leave the host and header focusable?

**Comment by jcfranco** [comment]
Either option from ☝️ impacts https://github.com/Esri/calcite-app-components/issues/572.

**Comment by jcfranco** [comment]
> @jcfranco can you set tabIndex="-1" on the container of the content

@driskull Sadly, that doesn't affect children. :sob:

**Comment by driskull** [comment]
😢

**Comment by asangma** [comment]
I think Option 1 is better.
Mostly because it won't cause stuff to shift when enabling/disabling.

**Comment by jcfranco** [comment]
Per conversation w/ @asangma, the slotted control (if any) should now be rendered and not hidden anymore (previous workaround to avoid interaction).

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
Verified!
