### ISSUE TITLE
Bug: Shift click unselection in calcite-pick-list doesn't work

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#551]
### Summary

Bug: Shift click unselection in calcite-pick-list doesn't work

### Actual Behavior

You can shift click to select all items up to the selected item but you can't do the same for unselecting them

### Expected Behavior

If You have all the items selected and shift-click on them, they should all become unselected

### Reproduction Steps

1. Select all items
2. Try to unselect all but the first item by shift clicking on the first item.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
verified
