### ISSUE TITLE
Bug: Save text disappears in Map Viewer beta

### ISSUE THREAD

**Issue by sha10152** [Esri/calcite-app-components#553]
@kevi2258 @chri4732

![image](https://user-images.githubusercontent.com/57729604/68801473-05382e00-0611-11ea-8a91-c891633c4206.png)

As soon as I save a map, 'Share Map' button activates..but Save text disappears
image

**Comment by driskull** [comment]
This seems like an app issue @sha10152 . @AdelheidF @kevindoshier can you confirm?

**Comment by kevindoshier** [comment]
I wasnt able to reproduce today, it might have just been something going on with yesterdays build

**Comment by sha10152** [comment]
@kevindoshier You are right. It's working fine today. All set with this one.
