### ISSUE TITLE
Bug: panel header + action height is weird when content is scrolling

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#554]
### Actual Behavior
![panel min-height](https://user-images.githubusercontent.com/12503298/68816040-147ba380-0632-11ea-8744-f8b8486f09d6.gif)

### Expected Behavior
No border weirdness.

### Reproduction Steps

1. Flow demo

### Relevant Info 
Could set flex-basis instead of min-height.
Could also set flex-basis based on the height of Action which is basically our size basis (16px) * 3.

**Comment by asangma** [comment]
This was not actually fixed by the referencing PR.
![panel header min-height](https://user-images.githubusercontent.com/12503298/69077080-aea06a80-09e9-11ea-9d6e-83558cd2ec62.gif)

**Comment by kat10140** [comment]
PR #591

**Comment by asangma** [comment]
@kat10140 VERFEE

**Comment by kat10140** [comment]
verified!
