### ISSUE TITLE
Enhancement: Action. Add property enable clear bg-color

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#557]
### Description
The white bg of Action gets weird during hover states in stuff like value-list-item.
![image](https://user-images.githubusercontent.com/12503298/68879986-41c26300-06bf-11ea-88db-0ac3b7aaf141.png)

### Acceptance Criteria 
Look more like this
![image](https://user-images.githubusercontent.com/12503298/68880040-5e5e9b00-06bf-11ea-9669-e1a1f5031821.png)

And ensure that there's a related hover state.

#### Which Component
Action

#### Example Use Case
Used in value-list-item

cc @AdelheidF @kat10140

**Comment by driskull** [comment]
@asangma can it just be clear by default? Do we need to set the BG color?

**Comment by asangma** [comment]
I like it.

**Comment by asangma** [comment]
Would still need to do some stuff regarding the hover state.

**Comment by driskull** [comment]
Seems like the only time it would need a bg color is when its in another component and can be styled by that component. 👍

**Comment by asangma** [comment]
I would need to move all the styles out of the `button` that's inside the shadow dom.

**Comment by driskull** [comment]
Lets be consistent with `calcite-components` and add a clear property

**Comment by asangma** [comment]
Cool. `appearance="clear"` will be the closest analogy to calcite-components' [button](https://esri.github.io/calcite-components/?path=/story/button--simple).

**Comment by driskull** [comment]
So we would have a property on the Action called `appearance` and by default it would be `solid`

**Comment by asangma** [comment]
Hee hee...already doon it. :)

**Comment by asangma** [comment]
```
/** Specify the appearance style of the action, defaults to solid. */
  @Prop({ reflect: true }) appearance: "solid" | "clear" = "solid";
```

**Comment by kat10140** [comment]
![Screen Shot 2019-12-03 at 10 56 14 AM](https://user-images.githubusercontent.com/48069902/70080638-c831dc80-15bb-11ea-89bf-27bbaddfd61c.png)
![Screen Shot 2019-12-03 at 10 57 33 AM](https://user-images.githubusercontent.com/48069902/70080639-c831dc80-15bb-11ea-80ea-e27343aee519.png)

doesn't look like it fixed ☹️
