### ISSUE TITLE
Bug: calcite-block disabled state doesn't 'hide' slider handle

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#560]
### Summary

![image](https://user-images.githubusercontent.com/44481292/68901696-3edd6780-06eb-11ea-9e56-fd54c69514dd.png)

cc @asangma @jcfranco 

### Reproduction Steps

1.

**Comment by jcfranco** [comment]
The scrim currently uses a z-index of 2, so there are cases where siblings in the same stacking context will show above it. I propose for now a simple CSS var for the scrim's z-index and if necessary, we can create a follow-up issue for something more involved to guarantee that it's always above. 

@asangma @pr3tori4n @driskull WDYT?

**Comment by driskull** [comment]
@jcfranco This is the current structure of the scrim

```tsx
<div class={CSS.content} hidden={!hasContent || !open}>
   <slot />
  {loading || disabled ? <CalciteScrim loading={false}></CalciteScrim> : null}
</div>
```

Can we just do the following to get the stacking index relative to where the scrim is?

```tsx
<div class={CSS.content} hidden={!hasContent || !open}>
  <div style="position:relative; z-index:1">
     <slot />
  </div>
  <div>
  {loading || disabled ? <CalciteScrim loading={false}></CalciteScrim> : null}
</div>
```

**Comment by driskull** [comment]
We could also enhance `<CalciteScrim>` to surround the content you want contained in the right z-index stacking. That might be even better.

**Comment by jcfranco** [comment]
@AdelheidF Can you help verify this one?

**Comment by AdelheidF** [comment]
Tested locally. Seems fine now.

<img src=https://user-images.githubusercontent.com/44481292/69205162-10ea8f80-0afe-11ea-88a8-cc8a557f3ad5.png width=200/>
