### ISSUE TITLE
Bug: Tip. Header still renders when non-dismissible and no heading slot content

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#566]
### Actual Behavior
![image](https://user-images.githubusercontent.com/12503298/68964320-e4e1ae00-078d-11ea-9c0a-0c2174142c69.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/12503298/68968834-56bef500-0798-11ea-81d8-6f11df7653e6.png)

### Reproduction Steps

1. Make a Tip with no heading and non-dismissible

**Comment by asangma** [comment]
note: there are probz a few other CSS things to go along with this.

**Comment by driskull** [comment]
Installed

**Comment by asangma** [comment]
VERFEED!
