### ISSUE TITLE
A11y: Action focus ring gets largely hidden

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#569]
### Summary
Action focus ring in ActionBar gets hidden.

### Actual & Expected Behavior
![action focus](https://user-images.githubusercontent.com/12503298/68984807-14f97300-07c7-11ea-91d8-13ccfa961583.gif)

### Reproduction Steps

1. focus an Action in a ActionBar.

**Comment by asangma** [comment]
cc @arjavbadjatiya

**Comment by asangma** [comment]
@kat10140 verfee!

**Comment by kat10140** [comment]
Verfeeeeeeeeeeee
