### ISSUE TITLE
Enhancement: Event when user starts typing to filter

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-app-components#571]
### Description
Return an event when user starts typing to filter.

### Acceptance Criteria 
The event can return all currently visible values for the user + what the user actually typed.

#### Which Component
calcite-value-list and calcite-pick-list

**Comment by pr3tori4n** [comment]
I spoke with Dhrumil and he's going to try using [CalciteFilterChange event](https://github.com/Esri/calcite-app-components/tree/master/src/components/calcite-filter#events), which already exists as part of the filter. Closing as no longer needed.
