### ISSUE TITLE
Enhancement: calcite-block to collapse disabled blocks

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#572]
### Description
If the user enters the SymbolStyler with a PictureMakerSymbol we want to set the fill and outline to certain color values in case the user switches to a SimpleMakerSymbol. In order to have those things available and visible when the user switches to SimpleMS I pass in these open and enabled states below. But it looks weird if all that is greyed out at first, since the PictureMS is still the one being used.
 
Would it be possible to auto collapse the blocks if they’re disabled? And open them once the disabled state gets taken off? Also, should the header text appear disabled as well?

From @jcfranco 
I kind of prefer and would expect this too. I see the reasoning on leaving them enabled since it allows the user to still collapse to get more space, but it’s a bit confusing the other way, where you open a disabled block (that otherwise looks enabled) only to see its content disabled. 

![1](https://user-images.githubusercontent.com/44481292/69187899-4f695580-0ad0-11ea-87bf-2da17b645b6b.png)

cc @asangma 

#### Example Use Case

http://devext.arcgis.com/apps/mapviewer/index.html

**Comment by jcfranco** [comment]
@mitc7862 Can you chime in on this one? There's been some back and forth on how a block's header and content should be presented when disabled.

**Comment by jcfranco** [comment]
@AdelheidF @mitc7862 for #548, we'll be disabling the entire block and will leave it up to the developer to either close or leave expanded when the component is disabled, see https://github.com/Esri/calcite-app-components/issues/548#issuecomment-564784629 for more info.

**Comment by AdelheidF** [comment]
If the new Stencil SymbolStyler is using blocks, what will it do with a disabled block?

**Comment by jcfranco** [comment]
That's a @mitc7862 question. 😄 We have that discussion elsewhere since it's unrelated to this repo.

**Comment by jcfranco** [comment]
#548 has been installed. Blocks will now be disabled and developers can choose to either close or leave it expanded when disabling.
