### ISSUE TITLE
Enhancement: Interim focus style

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#573]
### Description
Until #111 is full addressed, add a consistent adjustment to browser standard `outline`. Seems like most issues with default focus ring styles are the ring getting clipped.

Propose a mixin that insets the focus outline.

```
@mixin focusRingInset() {
&:focus {
    outline-offset: var(--calcite-app-outline-inset);
  }
}
```

`--calcite-app-outline-inset` is already in.

### Acceptance Criteria 
A good interim solution for focus ring issues.

### Relevant Info 
[W3 focus doc](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html)

#### Which Component
All.

#### Example Use Case
Keyboard navigation.

**Comment by asangma** [comment]
@kat10140 VERVEY!

**Comment by kat10140** [comment]
Verified!

**Comment by kat10140** [comment]
![value list focus](https://user-images.githubusercontent.com/48069902/70483818-a5616580-1a9e-11ea-8aff-3c352c08a840.gif)

@asangma I missed this on compact mode on the value list- notice the smaller focus on compact items. Also cuts off a bit on the main meat of the dragon drop items

**Comment by asangma** [comment]
VERF AGERN

**Comment by kat10140** [comment]
lewks gewd
