### ISSUE TITLE
Enhancement: Flow - Menu keyboard navigation

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#58]
### Description

Enhancement: Flow - Menu keyboard navigation

#### Desired New Behavior

Add ability to navigate the action menu in the Flow header by using the arrow keys.

- The escape key should close the menu
- The down arrow key should focus the next menu item and back to the first if its the last item
- The up arrow key should focus the previous menu item and to the last if its the first item
- The down arrow key on the menu button should open the menu and focus on the first item.
- The up arrow key on the menu button should open the menu and focus on the last item

### Relevant Info <small>(e.g. Dependencies, Blockers)</small>

#6

**Comment by driskull** [comment]
Can't fix this until we get the option of setting the `delegatesFocus` on the shadow dom.

calling `.focus()` on a `calcite-action` doesn't do anything because the focus needs to be called on the button element inside.

> When a node inside shadow DOM gains focus, :focus applies to the host in addition to the focused element.

https://developers.google.com/web/fundamentals/web-components/shadowdom

**Comment by driskull** [comment]
Summary
The calcite-flow-item menu-button needs to follow the guidelines found at this link: http://w3c.github.io/aria-practices/#menubutton
Specifically look into the aria-haspopup and aria-expanded

Also, when the user opens the menu and then continues tabbing through the page, the menu should close automatically.

Actual Behavior
Menu stays open when focus is removed

Expected Behavior
Menu should close when the focus is shifted to another element on the page

Reproduction Steps
https://esri.github.io/calcite-app-components/demos/calcite-flow-item.html
Tab through, open the menu button, then continue tabbing. Menu will not close
Relevant Info

**Comment by kat10140** [comment]
verified!
