### ISSUE TITLE
Enhancement: Flow should remove the current panel automatically when back is clicked

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#586]
### Description

Enhancement: Flow should remove the current panel automatically when back is clicked

From: https://github.com/Esri/calcite-app-components/wiki/2019-Weekly-Meeting#2019-11-15

### Acceptance Criteria 

Add property `beforeBack`.

```tsx
@Prop() beforeBack: () => Promise<void> = () =>
```

#### Which Component
CalciteFlow

**Comment by driskull** [comment]
This will be a breaking change, so I will remove all deprecations as well.

**Comment by jcfranco** [comment]
Verified locally.
