### ISSUE TITLE
Enhancement: ShellPanel - make floated content height dynamic

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#594]
### Description
Find a solution for this problem: 
Currently, unable to accomplish a content-based height in the float mode because doing so conflicts with a flow-item's sticky header and footer.

So the scale prop sets the height to one of three sizes:
Small
![image](https://user-images.githubusercontent.com/12503298/69678621-ef882700-105a-11ea-93e9-6ad3013345dd.png)

Medium (default)
![image](https://user-images.githubusercontent.com/12503298/69678637-ff077000-105a-11ea-90a4-7e1e9484a3d3.png)

Large
![image](https://user-images.githubusercontent.com/12503298/69678654-0dee2280-105b-11ea-9ca8-abd207602f54.png)

from #591 

### Acceptance Criteria 
* Panel is only as tall as the content requires until it hits max-height
* A FlowItem in a floated content node will still have a sticky header and footer
* A Panel in a floated content node will still have a sticky header and footer

#### Which Component
ShellPanel, FlowItem, Panel

If anybody else wants to take a whack at this, I could use the help.

**Comment by kat10140** [comment]
DOOP
