### ISSUE TITLE
Enhancement: calcite-pick-list - change filter text

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#597]
### Description

Is it possible to change the string in the filter?

Design
<img src=https://user-images.githubusercontent.com/44481292/67066856-1765a000-f129-11e9-8364-d8a9a752acc3.png width=250/>
Component:
<img src=https://user-images.githubusercontent.com/44481292/67066889-38c68c00-f129-11e9-808c-9d217f600c0c.png width=250/>

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by AdelheidF** [comment]
Works with 4.11.1.

<img src=https://user-images.githubusercontent.com/44481292/71122722-19ce8f80-2196-11ea-88ed-1c2dff954f3c.png width=250/>

**Comment by kat10140** [comment]
Werkin for me!
