### ISSUE TITLE
Bug: Filter. X is showing when there is nothing in input

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#599]
### Summary
X should only show when there is something in the input.

### Actual Behavior
![image](https://user-images.githubusercontent.com/12503298/70082426-3fb53b00-15bf-11ea-8419-3a10c1f55724.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/12503298/70082457-4e035700-15bf-11ea-81be-072649eb5095.png)

And when there's text...
![image](https://user-images.githubusercontent.com/12503298/70082497-5eb3cd00-15bf-11ea-90b8-0e6613a6439e.png)

### Reproduction Steps

1.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
verified
