### ISSUE TITLE
Enhancement: Start using REMs instead of pixels

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#601]
### Description
Update typography to use rems.

### Acceptance Criteria 
REMs

### Relevant Info 
Modernity.

#### Which Component
ALL DEM

#### Example Use Case
THE INTERNET.

![image](https://user-images.githubusercontent.com/12503298/70098105-f6291800-15df-11ea-8d11-a3db8df6330d.png)

**Comment by asangma** [comment]
@kat10140 VERFEE!

**Comment by kat10140** [comment]
is calcite-app-cap-spacing typography? if so we still have px definitions.
also looks like in _type.scss we have `--calcite-app-base-font-size: 16px;`

**Comment by kat10140** [comment]
@asangma

**Comment by asangma** [comment]
`spacing` would fall outside of typography.

We are explicitly setting `base-font-size` to 16px based on that being what most browsers already set it to by default. So this would keep things consistent if a browser wants to get cray.

**Comment by kat10140** [comment]
okee! verfied
