### ISSUE TITLE
Remove irrelevant loading and disabled buttons from demos

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#609]
### Summary
Loading and disabled toggle buttons should be taken off the homepage as well as components that don't have that integration. 

Remove from: Homepage, Tip Manager, Tip, Flow (has disabled), Flow-item

**Comment by driskull** [comment]
@kat10140 it might be better to just add the script to the pages that need it instead of the opposite. 

Which pages need the script?

Also, I think some have disabled but not loading so the script should account for one or the other I think.

**Comment by pr3tori4n** [comment]
Is this still necessary with Storybook coming soon?

**Comment by pr3tori4n** [comment]
Closing, since we have storybook now.
