### ISSUE TITLE
Bug: Edge Floating Panels and Popover

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#611]
### Actual Behavior
On click, the floating panels open super wonky. 
Weirdness happens also on the popover- popover is in the right place, but there is extra padding on the left 

![Screen Shot 2019-12-06 at 9 57 49 AM](https://user-images.githubusercontent.com/48069902/70350132-024ce980-181b-11ea-954f-a2e52e3dc1ef.png)
![Screen Shot 2019-12-06 at 9 58 11 AM](https://user-images.githubusercontent.com/48069902/70350133-024ce980-181b-11ea-8047-bdb08339244b.png)
^^ Above is on click of Over Shell Floating Panel
![Screen Shot 2019-12-06 at 9 58 21 AM](https://user-images.githubusercontent.com/48069902/70350134-024ce980-181b-11ea-9386-98c1caf115c2.png)

### Repro

1. Full width shell demo in Edge

**Comment by driskull** [comment]
Related to edge polyfill bug.
