### ISSUE TITLE
Enhancement: Flow to accept any node

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#616]
### Description
Update calcite-flow to apply flow-item styles, e.g. animation, to any node placed inside flow's slot.

### Acceptance Criteria 
Devs can push their own components into a flow without having to do anything special and get the benefits that flow-item gets.

### Relevant Info 
We are going to see more prebuilt components like from arcgis-app-components becoming relevant here.

#### Which Component
Flow

#### Example Use Case
Adding an arcgis component to a flow.

**Comment by driskull** [comment]
@asangma then their own component would be responsible for the back button and removing the item they place. Is that desired?

This may be able to work. The only part that would need to change is we query for the number of flow-items currently and that would have to change to query any direct children instead.

**Comment by driskull** [comment]
@asangma what is the hardship with them putting their content into a `flow-item`?

**Comment by asangma** [comment]
I think the hardship can be that the component might have its own header and such. But I will know more in the next couple days.

**Comment by driskull** [comment]
IMO the component shouldn't have its own header. Then we get into inconsistencies. The point of the components is to not have multiple versions of things

**Comment by asangma** [comment]
I def get that.
The case I'm seeing uses calcite-panel, etc. to create a more complex component. I will find out more.

**Comment by asangma** [comment]
Moving this to backlog for now.

**Comment by asangma** [comment]
I think this is no longer a thing. Gonna close. We can reopen or create a new one if this comes back up.
