### ISSUE TITLE
New Component: Calcite-Scrim

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#618]
### Description
We want a more widespread component for loading and disabled states. Gonna make our calcite-app functional component into a calcite "component component" that can be used in this repo and brought into arcgis-components (for Dhrumil).

#### Acceptance Criteria
Props for:
- loading
- disabled

Div styling that matches our spinning science of where icon for loading state and changed opacity for disabled states.

[Calcite-Components issue](https://github.com/Esri/calcite-components/issues/252)

**Comment by asangma** [comment]
@driskull I am confirming that our components are using calcite-components Scrim, yah?

**Comment by driskull** [comment]
Yeah 👍

**Comment by asangma** [comment]
Looks good. Seems like we'd want components to pass their `theme` to Scrim.

There is a style issue at the moment with Scrim in dark theme, but I think the issue is something we'd want to sync with Calcite Components on.

**Comment by driskull** [comment]
> Seems like we'd want components to pass their theme to Scrim.

Ah, yep. I forgot we don't share vars for that. Can you create an issue for me?

**Comment by asangma** [comment]
Cool.
I thought that maybe matching colors would work, but a low-opacity dark color on top of another dark color layers to be an even darker color.

So we'll end up with this kinna thing:
![image](https://user-images.githubusercontent.com/12503298/82386922-84f0ec00-99ea-11ea-8b46-f981db3c3c68.png)

Will need to strategize between calcite-components and calcite-app-components yeah?

**Comment by driskull** [comment]
yeah

**Comment by asangma** [comment]
Noice!
