### ISSUE TITLE
Bug: FlowItem does not get animation when added to Flow.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#626]
### Summary
When a FlowItem gets added to Flow, it is not getting the animation.
I'm not sure if this is a Flow bug or FlowItem bug.

### Actual Behavior
FlowItem doesn't get animation.

### Expected Behavior
FlowItem should get animation.

### Reproduction Steps
1. Dynamically add a FlowItem to a Flow.

**Comment by asangma** [comment]
Might need to add the "add flowitem" button back to the demo.

**Comment by driskull** [comment]
@asangma it is in the advanced demo. https://esri.github.io/calcite-app-components/demos/advanced/flow-adding-items.html

Are they removing all flows before adding one? Because we don't animate the first flow (if there is only one flow, we don't animate)

**Comment by asangma** [comment]
I'm seeing it when an item is getting added to a flow, e.g. when selecting a renderer for smart mapping. The back animation works tho.

**Comment by asangma** [comment]
Per Slack discussion, it looks like this might be a MutationObserver thing.

**Comment by driskull** [comment]
Installed. Do we need a release for this @asangma ?

**Comment by asangma** [comment]
Yeah...that'd be cool.

**Comment by driskull** [comment]
Ok ill release later today.

**Comment by driskull** [comment]
We can reproduce this by adding the following to the `flow-adding-items.html` demo.

After line 133.
```js
setTimeout(function() {
          newNode.innerHTML = "new content";
        }, 100);
```

**Comment by driskull** [comment]
Added snippet to demo.

**Comment by asangma** [comment]
Yew! Will verify in app.

**Comment by AdelheidF** [comment]
I'm not quite sure what to look for when verifying. I see an animation if I click on a renderer style tile on production.

**Comment by driskull** [comment]
@asangma can verify

**Comment by driskull** [comment]
Can you go to styles, add a field and try clicking on style options?

![image](https://user-images.githubusercontent.com/1231455/70670436-cad0a980-1c2d-11ea-99ec-4f05d9d51e36.png)

The flow should animate. on devext it doesn't animate currently.

**Comment by driskull** [comment]
Not animating:

![not-animating](https://user-images.githubusercontent.com/1231455/70670488-ef2c8600-1c2d-11ea-8193-9127568dd5d4.gif)

**Comment by AdelheidF** [comment]
It animates with a bivariate renderer into the second flow-item, but not the third...

**Comment by asangma** [comment]
Thanks @AdelheidF 
VERFEED!

**Comment by AdelheidF** [comment]
... I didn't verify it, Last I checked it didn't work for the third level of bivariate renderers.

**Comment by asangma** [comment]
I checked this morning on devext and devtesting. I will reopen if you wanna verify.

**Comment by AdelheidF** [comment]
Yes, works on devext today.

**Comment by asangma** [comment]
Thanks @AdelheidF !
