### ISSUE TITLE
Tooling: Move `calcite-example` boilerplate to be a resource shared between projects

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#640]
## Summary 

Tooling: Move `calcite-example` boilerplate to be a resource shared between projects

## Measure of Success 

`calcite-example` is a higher level resource that links to examples and is shared between repositories. Could be a separate repo or in a common project.

### Resources 

We had discussed a repo for `calcite-component-resources` to share common utilities and this could maybe go there.

**Comment by driskull** [comment]
@julio8a created a repo but its a private one for now until we get it setup with the code necessary and documentation. Then we can make it public on the Esri org.

**Comment by jcfranco** [comment]
@driskull Could this be assimilated into #172? I was thinking we would link to component patterns and  examples from that document. cc @kat10140

**Comment by driskull** [comment]
yep. sounds good

**Comment by jcfranco** [comment]
Thanks, closing!
