### ISSUE TITLE
Docs: [Storybook] Complete component stories

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#644]
### Description 

#401 sets up storybook for demos and only one functional story (see resources below) as an example. The rest are placeholders that need to be filled out.

### Which Component

@driskull 

* [x] `calcite-action` 
* [x] `calcite-action-bar`
* [x] `calcite-action-pad`
* [x] `calcite-flow`
* [x] `calcite-panel`
* [x] `calcite-shell`

@pr3tori4n 

* [x] `calcite-pick-list`
* [x] `calcite-tip`
* [x] `calcite-tip-manager`
* [x] `calcite-value-list`

I can help out if needed. I'll just need info on the stories we want. The story-building utility might also need some tweaks to accommodate other use cases. 

Once all stories are complete, we should replace the old way of generating docs (i.e., undo 6f9441b).

### Resources 

https://storybook.js.org/docs/basics/writing-stories/
[`calcite-block.stories.ts`](https://github.com/Esri/calcite-app-components/blob/master/src/components/calcite-block/calcite-block.stories.ts)

**Comment by driskull** [comment]
We should probably do some cross browser testing before swapping gh-pages to this.

**Comment by jcfranco** [comment]
☝️ Did a quick test on all browsers (Chrome, Firefox, Safari, Edge) and everything seems to run fine.

**Comment by driskull** [comment]
Sweet! lets kick off the PR to make this public :)

**Comment by jcfranco** [comment]
☝️ 💥

@driskull @pr3tori4n Excellent job, you guys!

**Comment by jcfranco** [comment]
Verified on https://esri.github.io/calcite-app-components 🎉
