### ISSUE TITLE
Docs:  Configure storybook to have a better landing/welcome page and getting started info

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#647]
Docs:  Configure storybook to have a better landing/welcome page and getting started info

### Description 

I found an example storybook that has a nice section that a user lands on and has more information.  Currently, we just land right into the first component but it would be nice to have some information about the project, how to use it, how to contribute, etc. 

A lot of this info is already in our readme and markdown files.

### Resources 

Good example: 
https://necolas.github.io/react-native-web/docs/?path=/docs/overview-getting-started--page

From: https://storybook.js.org/docs/examples/

## Information to include

We could include

- Changelog
- Readme
- Code of conduct
- Contributing

cc @jcfranco

**Comment by driskull** [comment]
Have a PR open to get this setup for contributions.

**Comment by kat10140** [comment]
Verified!
