### ISSUE TITLE
Bug: calcite-popover with "auto" still gets cut off

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#650]
### Summary
Using calcite-popover with "auto" placement cuts the popover when the reference element is near a corner because it always centers the popover on the reference element. Maybe it should shift off-center too.

![image](https://user-images.githubusercontent.com/44481292/70823050-d0e09a80-1d93-11ea-9468-a0bb057fb6d1.png)

![image](https://user-images.githubusercontent.com/44481292/70823072-e229a700-1d93-11ea-8720-15446055c682.png)

![image](https://user-images.githubusercontent.com/44481292/70823119-01283900-1d94-11ea-98d9-b1a5b1fd8f48.png)

![image](https://user-images.githubusercontent.com/44481292/70823268-53695a00-1d94-11ea-8b1b-b0e31bf69f5c.png)

### Reproduction Steps

1.

**Comment by driskull** [comment]
Unfortunately, the positioning is handled by Popper.js. They are working on a v2 and we'll keep checking in on it and update once we can.

https://github.com/popperjs/popper.js/issues/617
