### ISSUE TITLE
Enhancement: ActionPad. Add same expand/collaps behavior as ActionBar

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#656]
### Description
Once #608 is merged, add expand/collapse property and functional matching ActionBar behavior. 

### Acceptance Criteria 
- ActionPad can be expanded/collapsed by end user
- ActionPad can be expanded/collapsed by dev user
- Dev user can enable/disable the expand or collapse button.

#### Which Component
ActionBar

@kat10140 Let's triage this.

**Comment by driskull** [comment]
@asangma do we just need a floating property on the `calcite-action-bar` and kill off the `action-pad`? Seems like they are becoming one component.

**Comment by asangma** [comment]
@driskull Hmmm...maybe. I wonder which would be more funky to manage:

- two components that are similar
- conditional styling

**Comment by asangma** [comment]
I also think the use cases for either component are different even though some of the behaviors are the same. 🤔

**Comment by driskull** [comment]
We should discuss at a meeting. If we do this to the actionPad, then they have the same code but different styles

**Comment by kat10140** [comment]
@asangma want to review this?

**Comment by kat10140** [comment]
we have a divider in action pad. have a looksie

**Comment by driskull** [comment]
Not sure if we want to add any additional usage doc for this?

**Comment by kat10140** [comment]
@driskull yes, i'll do that

**Comment by asangma** [comment]
Sorry for the slow beans.
