### ISSUE TITLE
Tooling: Remove helper CalciteIcon and use calcite-icon component

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#671]
## Summary 

Tooling: Remove helper CalciteIcon and use calcite-icon component

## Measure of Success 

Tooling: Remove helper CalciteIcon and use calcite-icon component

### Resources 

https://github.com/Esri/calcite-components/issues/250
https://github.com/Esri/calcite-components/pull/265

Also remove `createSVG` helper for storybook.

**Comment by driskull** [comment]
cc @jcfranco

**Comment by jcfranco** [comment]
Verified locally.
