### ISSUE TITLE
Docs: [Storybook] previews always have scrollbars

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#673]
### Description 

Component previews always have a scrollbar. 

<img width="1055" alt="Screen Shot 2019-12-19 at 10 22 49 AM" src="https://user-images.githubusercontent.com/197440/71198827-86ef2d00-2249-11ea-9bf4-bec1096e5113.png">

☝️ https://esri.github.io/calcite-app-components/?path=/story/components-calcite-action--basic

### Which Component

All components.

**Comment by jcfranco** [comment]
This is being caused by the following:

https://github.com/Esri/calcite-app-components/blob/8f1bf5021059e7fa55042b0c3e061e8e0ca0e788/.storybook/preview-head.html#L12-L17

I think we'll have to live with this one since ☝️ is a workaround for disappearing components when zooming. 

@asangma @driskull @pr3tori4n WDYT?

**Comment by kat10140** [comment]
closing as decided in 1/6 meeting
