### ISSUE TITLE
Docs: [Storybook] Double titles are displayed in the Docs tab

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#674]
### Description 

The docs tab seems to repeat the component title. 

<img width="614" alt="Screen Shot 2019-12-19 at 10 19 38 AM" src="https://user-images.githubusercontent.com/197440/71199033-e5b4a680-2249-11ea-9707-be4835235e38.png">

**Comment by jcfranco** [comment]
Installed. @kat10140 Please verify. 🙇

**Comment by kat10140** [comment]
looks good!
