### ISSUE TITLE
Enhancement: ShellPanel. Add tests and stories for detached mode and panel heigh-scale prop

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#686]
### Description
Add stories and tests for changes from the #591 PR.

### Acceptance Criteria 
- [x] ~~test for panel `height-scale` prop]~~ 
- [x] test for shell-panel `detached` prop
- [x] ~~test for shell-panel `detached-scale` prop~~
- [x] story / knob for panel `height-scale`
- [x] story / knob for shell-panel `detached` prop
- [x] story / knob for shell-panel `scale` prop

#### Which Component
ShellPanel.

**Comment by driskull** [comment]
I don't think the scale props need tests. I don't want to make it too feeble where its checking heights :)

**Comment by asangma** [comment]
Sounds good.

**Comment by asangma** [comment]
Lookin' good. Question: is it all right that the heights on the panel and shell-panel are vh while the demos are not full browser window?

**Comment by driskull** [comment]
> is it all right that the heights on the panel and shell-panel are vh while the demos are not full browser window?

I think so, maybe we should note or document that the heights are based off the window view? Maybe we say that a shell should be 100% width and height of the window?

**Comment by asangma** [comment]
Yeah...that seems good.

**Comment by asangma** [comment]
This is looking good to me. @kat10140 is gonna help verify the tests.

**Comment by kat10140** [comment]
lewks gewd!
