### ISSUE TITLE
Enhancement: Tip Manager - Solidify logic for add/remove behavior creating conflicts

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#72]
### Description
The Tip Manager responds to changes to the tips nested inside. As of now it detects additions/deletions to the list of tips. Some edge-case scenarios can arise that left unmanaged lead to a poor UX. We should nail down the best UX for these scenarios. Depending on the ideal - we may be able to consolidate code between initialLoad logic, and when one of these modifications occur.

#### Desired New Behavior
 **(Still needs to be finalized)**
1. When tips are added or removed
   1. reset the selected tip to the first in the list. Ignore any tips that have the "selected" attribute.
   OR
   1. When tips are added and more than one has a selected attribute, select the **first** tip that's marked selected, or the first tip if none are marked.
   1. When tips are removed, and no tips are marked selected, select the first tip.

1. Always update the group title when the selected tip is changed.

### Relevant Info
- Look for opportunities to share logic between the constructor (first load) and the mutation handler (childList change).

### Helpful Details

**Which Component:** Tip Manager

**Example Use Case:** 
1. A dev-user adds a new tip that has the selected attribute, creating a scenario where two tips are "selected".
1. A dev-user removes the tip that was previously selected.

**Comment by pr3tori4n** [comment]
@franco @driskull @asangma Moving to Milestone BMO since this is already marked installed.

**Comment by asangma** [comment]
👍
