### ISSUE TITLE
Bug: FlowItem RTL trailing icon isn't on the far side

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#721]
### Summary

Bug: FlowItem RTL trailing icon isn't on the far side

### Actual Behavior

trailing icon is right next to the text

### Expected Behavior

trailing icon should be all the way on the other side

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/?path=/story/components-calcite-flow--basic
2. Set the component to be RTL using the dom inspector

### Relevant Info 

![Screen Shot 2019-12-31 at 3 56 25 PM](https://user-images.githubusercontent.com/1231455/71636516-4c40a980-2be6-11ea-844e-535924a115d6.png)

**Comment by asangma** [comment]
Verified locally.
