### ISSUE TITLE
Enhancement: Calcite-block can we have the way to show the collapsible icon Header + collapsible + control 

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-app-components#726]
### Description
when a calcite-block had Header + collapsible + control 
can we have a way to show the collapsible icon.

### Acceptance Criteria 
when block has Header + collapsible + control then there should be a way to show icon for close

#### Which Component
Calcite-Block

**Comment by asangma** [comment]
Are we seeing people confused about whether they can collapse the block or not?

**Comment by kat10140** [comment]
@kumarGayu

**Comment by asangma** [comment]
@kumarGayu Are we seeing people confused about whether they can collapse the block or not?

**Comment by kumarGayu** [comment]
> @kumarGayu Are we seeing people confused about whether they can collapse the block or not?

Yes. I am really sorry for delayed reply. because when we have action header and collapsed true as a user I do not know we can collapse it or not.

**Comment by kat10140** [comment]
@asangma

**Comment by kat10140** [comment]
im closing this. kumar please reach out if this is still an issue
