### ISSUE TITLE
Bug: PickList slot name should be kebab case

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#728]
### Summary

slot="secondaryAction" should be secondary-action right?

Derived from https://github.com/Esri/calcite-app-components/pull/700#pullrequestreview-336625806

**Comment by driskull** [comment]
@kat10140 @pr3tori4n  I see some references to `secondaryAction` in `.html` and usage `.md` files. Can we update those?

**Comment by pr3tori4n** [comment]
the md files should update naturally when we do a build. HTML files will need manual updates

**Comment by driskull** [comment]
The usage md files would still need to be updated. They are not auto generated.

**Comment by driskull** [comment]
Installed fixes

**Comment by kat10140** [comment]
@driskull if you ever need help with something like this just slack me! Sometimes I don't see github comments right away. 

Verified!
