### ISSUE TITLE
Bug: PickList > drag handle UI bug

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#729]
### Summary
Drag handle has a li'l box-shadow.

### Actual Behavior
![Screen Shot 2020-01-06 at 10 00 41 AM](https://user-images.githubusercontent.com/12503298/71837594-ac62a000-306b-11ea-9c5c-a76780ae37b2.png)

### Expected Behavior
No borders.

cc @kat10140

**Comment by asangma** [comment]
@kat10140 PR #776 should fix this. Mind verfeeing?

**Comment by kat10140** [comment]
lewks good! also this looks like it's for value list, gonna change the title @asangma

**Comment by kat10140** [comment]
or is it for a value list item (which is a pick list item?)
