### ISSUE TITLE
Bug: Modify global styles to remove host

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#733]
### Summary

From Stencil support:

**Question:** Are we able to use `:host{}` in the global style?
**Answer:** `:host` no, i don’t think that’d work, they should use :root or html instead
:host would mean like the component host element, but for a global style on the document i’m not sure it’d know what host is

### Actual Behavior

Host is used in global includes

### Expected Behavior

Host should not be used in global includes. 

### Relevant Info 

We should probably create a mixin we can import to each component.

Host is used in `_base.scss`, and `_color.scss`

@jcfranco does this sound correct?

**Comment by driskull** [comment]
@jcfranco We should discuss what we want to do.

**Comment by jcfranco** [comment]
Verified locally.
