### ISSUE TITLE
Bug: Calcite-Value-List: when the list item value changes in tsx the old selected list item value is not deleted

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-app-components#738]
### Summary
Calcite-Value-List: for a single select when the list item value changes in tsx the old selected value is not deleted

### Actual Behavior
e.detail has 2 values. one was the older value and the other one is newer selected value.

### Expected Behavior
Ideally list change event should have one item selected in e.detail for a single select.

### Reproduction Steps

1. have a single select list with multiple values.
2. cahnge the list value description synamically through tsx prop update.
3. now go and select the other item
4. e.detail has 2 values.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
verified
