### ISSUE TITLE
Enhancement: calcite-pick-list - minimalist option for padding?

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#746]
### Description

See discussion here: https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1087#issuecomment-2025553

Would it be possible to have a pick-list option that uses a minimalist approach to padding?
See the padding in this mock-up (used in FeatureFilter component for 'includes'):

![image](https://user-images.githubusercontent.com/44481292/72106246-dc1bdd00-32e3-11ea-8389-5a563279fc82.png)
 
Currently it's this:
![image](https://user-images.githubusercontent.com/44481292/72106282-eccc5300-32e3-11ea-8ba5-d906349d7b38.png)

cc @asangma

**Comment by pr3tori4n** [comment]
@asangma is this something you're looking into?

**Comment by AdelheidF** [comment]
duplicate of https://github.com/Esri/calcite-app-components/issues/795
