### ISSUE TITLE
Bug: [Block] unintentional toggle when control is focused and Space/Enter is pressed

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#751]
### Summary

Bubbled keyboard events (Space/Enter) can cause the block to unintentionally toggle.

### Actual Behavior

Block is toggled when a Space/Enter keyboard event is dispatched from a control element.

### Expected Behavior

!:point_up:

### Reproduction Steps

1. Open the following [test case](https://codepen.io/jcfranco-the-scripter/pen/zYxjZvW).
2. Focus on the control
3. Press Space or Enter key
4. Note how the block is toggled (unexpected)

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
@jcfranco looks like it's still happening with the test case you provided. should i test this somewhere else?

**Comment by jcfranco** [comment]
@kat10140 This fix will be in the next release, so you'll need to test locally for now.

**Comment by kat10140** [comment]
@jcfranco this is happening locally and on the test case you provided.

**Comment by jcfranco** [comment]
It works fine using the latest: https://codepen.io/jcfranco-the-scripter/pen/VwYOBPz

1. Focus on the control text (`focus me and hit SPACE/ENTER`)
2. Press Space or Enter key
3. Block is not toggled. ✅

**Comment by kat10140** [comment]
facepalm. i only changed the version of the stylesheets
