### ISSUE TITLE
Bug: Caclite-value-list: order of calcite-value-list-item is lost if we recreate value list using state in tsx

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-app-components#757]
### Summary
initially
![image](https://user-images.githubusercontent.com/9862218/72391737-e292c600-36e2-11ea-9453-71a1049e7af7.png)

I did drag battery to position 1.

but even then the UI did not change on a redraw.

on drag I get updated array on that I create a new value-list this seems to be working fine. however in UI the updated value is not visible.

```tsx
const lt = this.series?.map((eachSeries: Series) => {
      return eachSeries !== undefined ? (
        <calcite-value-list-item
          textLabel={eachSeries.name}
          value={eachSeries.name}
        ></calcite-value-list-item>
      ) : null;
    });
    return (
      <calcite-value-list
        dragEnabled
        onCalciteListChange={this.seriesSelect}
        onCalciteListOrderChange={this.onCalciteListOrderChange}
      >
        {lt}
      </calcite-value-list>
    );```

**Comment by pr3tori4n** [comment]
### Update

I've been able to reproduce this behavior without the sorting. If there's an array set as state, and that array is used to render elements in the component Stencil seems to connect the order of the elements in the dom with an index in that array. If the elements order is modified using JS, the state array to element mapping doesn't seem to get updated. Imagine an array `[1,2,3]` renders `<div>1</div><div>2</div><div>3</div>` If you change the order of the divs to display `2,1,3`, (swapping the order of the first 2) the component state will have pairing `1 => 2; 2 => 1; 3=> 3`. Then if the array is adjusted to be `2,1,3` it will swap the first two items as part of the re-render.

This sounds like it may be a bug in Stencil - indices of the array should map to a specific DOM element, not an index of elements in the DOM as that's brittle for the above reasons. I'll open an issue with Stencil to get the discussion started. I haven't as of yet been able to determine where in the code this problem exists.

**Comment by pr3tori4n** [comment]
@kumarGayu 
Here is the issue.
https://github.com/ionic-team/stencil/issues/2187

I think there are some workarounds possible here. In fact, I half expect the Stencil team to advise we don't use the same state array to do the first render as well as be what's updated on sorting changes. One thing could be having two arrays - one for the first render of the list and the other to print the sorted order, and only update the latter of the two arrays. Reach out over slack and we can pair up to try and get this working if you need any help.

**Comment by kumarGayu** [comment]
@pr3tori4n thank you very much 👍

**Comment by pr3tori4n** [comment]
@kat10140 I suggest we close this issue for now and track the Stencil bug under the Wiki page:
https://github.com/Esri/calcite-app-components/wiki/Stencil-Bugs-Tracking-Progress

**Comment by pr3tori4n** [comment]
Unassigning myself.

**Comment by kat10140** [comment]
closing per harry's comment.
