### ISSUE TITLE
Enhancement: calcite-action - add scale option

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#759]
### Description

Currently the calcite-action is using up a lot of width/height when used inside a 'text box'. It would be nice if there was an option to have a small size.

![image](https://user-images.githubusercontent.com/44481292/72474342-74f7a000-379d-11ea-97e5-84c4f9789d6f.png)

From the labeling config design:
![image](https://user-images.githubusercontent.com/44481292/72474498-bbe59580-379d-11ea-9ce7-f2f7c2fb0d59.png)

And could we use a small version then in pick-list so there's less blank space?, maybe `compact=true` works there too.
<img src=https://user-images.githubusercontent.com/44481292/72482459-9ca53300-37b2-11ea-8153-3ecade00a5ee.png width=200/><img src=https://user-images.githubusercontent.com/44481292/72482543-ed1c9080-37b2-11ea-9152-c0c6cc9d0102.png width=200/><img src=https://user-images.githubusercontent.com/44481292/72482579-0d4c4f80-37b3-11ea-9842-a6ec62222669.png width=200/>

cc @asangma

**Comment by driskull** [comment]
@asangma what do you think? If we add scale, would we get rid of compact?

**Comment by asangma** [comment]
@driskull Yeah...better to follow our other patterns and use **CalciteScale**.

**Comment by asangma** [comment]
@AdelheidF this is installed but not yet released yet. Feel free to start adding the prop to any actions you deem in need of small-ness.

**Comment by asangma** [comment]
@kat10140 Make for the verfee?

**Comment by kat10140** [comment]
verified!

**Comment by AdelheidF** [comment]
Looks good

![image](https://user-images.githubusercontent.com/44481292/73780674-c1eae880-4743-11ea-9015-6cd5f50a140b.png)

Will add it for map viewer beta 4
