### ISSUE TITLE
Bug: [calcite-block] Broken toggle behavior in Edge

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#763]
### Summary

Toggling doesn't work as expected in Edge when you have a block with a control and content.

### Actual Behavior

With the aforementioned setup, blocks can be collapsed, but not expanded.

### Expected Behavior

Consistent toggling behavior.

### Reproduction Steps

Using the following snippet, try to toggle the block.

```html
<calcite-block heading="With control" summary="has inline input" open collapsible>
  <label slot="control">test <input placeholder="I'm a header control"/></label>
  <calcite-block-section text="Animals" open>
    <img alt="demo" src="https://placeimg.com/640/480/animals" />
  </calcite-block-section>
</calcite-block>
```

### Relevant Info 

Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.1776

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
verified!
