### ISSUE TITLE
Bug: calcite-flow-item summery hidden if panel has vertical scroll

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#764]
### Summary
This is fine
<img src=https://user-images.githubusercontent.com/44481292/72484451-20fab480-37b9-11ea-8953-7ff7ecb98d1a.png width=200/>

This is not
<img src=https://user-images.githubusercontent.com/44481292/72484475-3243c100-37b9-11ea-9e47-8bca0e030e1c.png width=200/>

![image](https://user-images.githubusercontent.com/44481292/73294226-41b00a80-41ba-11ea-94ae-ee11e03d526a.png)

cc @asangma 

### Reproduction Steps

1.

**Comment by asangma** [comment]
@kat10140 @AdelheidF Please let me know if this works.
Should look like this.
![image](https://user-images.githubusercontent.com/12503298/73886346-44e07180-481e-11ea-9534-dbadc2a977f4.png)

**Comment by kat10140** [comment]
This looks good on my machine
