### ISSUE TITLE
Enhancement: Nested list items in pick list

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-app-components#767]
### Description

* A Pick List's items can be nested to create a heirarchy.
* The parent items should be selectable.
* The filter should show children when it matches a parent element.
* The filter should show a parent ( but not siblings ) when matching a child element.

**Comment by pr3tori4n** [comment]
@kat10140 please verify.

**Comment by kat10140** [comment]
@pr3tori4n if a parent is selected, are the children meant to be selected as well? looks like they're all single select right now

**Comment by kat10140** [comment]
![Screen Shot 2020-02-06 at 3 20 27 PM](https://user-images.githubusercontent.com/48069902/73987119-3d8b9780-48f4-11ea-90c5-c9343a3e9b6d.png)
it looks like the filter is showing siblings in this case

**Comment by pr3tori4n** [comment]
@kat10140 I don't believe this was requested. It was requested the parents be selectable, but not that selecting a parent auto-selects the children. If that's desired, I'd suggest we open a new enhancement issue to cover that behavior.

**Comment by kat10140** [comment]
Oh, thats how i interpreted the last bullet of the issue. If that's not the case, we can close this one

**Comment by pr3tori4n** [comment]
@kat10140 no worries. I believe that's meant to describe the hide/show behavior not the selection behavior. Closing.
