### ISSUE TITLE
Bug: height issues with calcite-flow/calcite-flow-item

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#771]
### Summary
If I set height to 100% the blocks inside the panel stretch out.
<img src=https://user-images.githubusercontent.com/44481292/72633154-b65a8d80-390c-11ea-9408-a3d349fbecf6.png width=200/>

If I don't set the height the Close/Cancel buttons are no longer at the bottom of the panel.
<img src=https://user-images.githubusercontent.com/44481292/72633189-ce321180-390c-11ea-8769-bbe7255d5e9b.png width=200/>

@asangma 

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
Looks good now.

**Comment by asangma** [comment]
Thanks!

**Comment by asangma** [comment]
Assigning to @kat10140

**Comment by kat10140** [comment]
ye!
