### ISSUE TITLE
Enhancement: Caclite value list: Can I have toggling effect on calcite list item on multiple click.

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-app-components#778]
### Description
Caclite value list: Can I have toggling effect on calcite list item on multiple click.
### Acceptance Criteria 
Have a selected and deslected on calcite value list
#### Which Component
Calcite Value List

**Comment by pr3tori4n** [comment]
@kat10140 could you help me nail down the requirements for this. I'm not sure what the ask is.

**Comment by kat10140** [comment]
I think what he's saying is he wants a select/deselect all. @kumarGayu ?

**Comment by kumarGayu** [comment]
I have a single select value-list where I want on every click i should toggle the select. Therefore can I have an event on calcite-value-list-item on every click or can i have attribute property toggle selection on multiple clicks.

**Comment by pr3tori4n** [comment]
Does this event do what you're asking? It's available for both pick list and value list items
https://github.com/Esri/calcite-app-components/tree/master/src/components/calcite-pick-list-item#events

**Comment by kumarGayu** [comment]
Yes, but will this work for single select?

**Comment by pr3tori4n** [comment]
@kumarGayu I think so. It's an even that fires off at the item level. It's possible it might not fire off if the parent is deselecting manually an item in a single selection. Try it out and let me know if you have any issues. If it works can we close this issue?

**Comment by kumarGayu** [comment]
Sure (y)

**Comment by kat10140** [comment]
@kumarGayu closing. Let me know if this is still an issue
