### ISSUE TITLE
Enhancement: Calcite-Filter should not query shadowRoot

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#780]
### Description

Enhancement: Calcite-Filter should not query shadowRoot

- [calcite-filter](https://github.com/Esri/calcite-app-components/blob/078682d73524d433bbf5a282ad855f291456fd02/src/components/calcite-filter/calcite-filter.tsx#L100)

```tsx
clear = (): void => {
    this.el.shadowRoot.querySelector("input").value = "";
    this.empty = true;
    this.calciteFilterChange.emit(this.data);
  };
```

@pr3tori4n does this work in Edge?

It would be better if it instead stored the node as a variable to reference it and clear its value.
```tsx
<input type="text" ref={(el) => this.textInput = el as HTMLInputElement} />
```

### Acceptance Criteria 

Shadowroot isn't queried for a node and the node is instead stored as a variable

#### Which Component

CalciteFilter

**Comment by driskull** [comment]
Seems to work in edge. It would still be better to have a reference to the element instead of querying for it.

**Comment by pr3tori4n** [comment]
@driskull please verify.
