### ISSUE TITLE
Bug: CalcitePickList compact mode doesn't render text

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#781]
### Summary

Bug: CalcitePickList compact mode doesn't render text

### Actual Behavior

^

### Expected Behavior

Text and checkbox/radio should be displayed

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/?path=/story/components-calcite-pick-list--basic
2. Toggle compact checkbox
3. Notice that text is no longer displayed and the radio/checkbox isn't either.

**Comment by pr3tori4n** [comment]
@driskull please verify.

**Comment by driskull** [comment]
@pr3tori4n is the checkbox/radio icon supposed to be gone in `compact`? If so, how does a user know which is selected? cc @asangma 

https://esri.github.io/calcite-app-components/?path=/story/components-calcite-pick-list--basic

**Comment by pr3tori4n** [comment]
reassigning to Alan since this is by design I believe.

**Comment by asangma** [comment]
Looks good.
