### ISSUE TITLE
Bug: Calcite-shell-panel remove position relative

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-app-components#782]
### Summary
Adding position relative to shell panel will add position relative to its children.
### Reproduction Steps

1.

**Comment by driskull** [comment]
@kumarGayu we can remove the `position:relative` from the `shell-panel` but it will still exist for slotted `shell-panel`s inside of a `shell` so I'm not sure if it will help at all. The `shell` needs it to put the zindex in.

Also `calcite-panel` has a `position:relative`.

**Comment by kumarGayu** [comment]
@driskull I think this will not solve the problem. if it is for z-index can you guys try visibility-true?

**Comment by kumarGayu** [comment]
inside panel I have series, and on click of series it is still working.

**Comment by driskull** [comment]
> if it is for z-index can you guys try visibility-true?

No, we need to position the panels above the map, we can only do that with positioning.
