### ISSUE TITLE
Enhancement: Create utility method to find out if a slot exists

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#784]
### Description

`this.el.querySelector([slot=${SLOTS.secondaryAction}])` is very common now it seems.

Maybe we should have a utility for this like `hasSlot(el: HTMLElement, slotName:string): boolean;`?

### Acceptance Criteria 

utility method to find out if a slot exists

### Relevant Info 

https://github.com/Esri/calcite-app-components/pull/783#discussion_r370507954

#### Which Component

All

#### Example Use Case

Above

**Comment by jcfranco** [comment]
I would like to propose the following:

```tsx
getSlotted<T extends HTMLElement = HTMLElement>(
  element: HTMLElement, 
  slotName: string, 
  options?: { all: boolean }
): T | NodeListOf<T>;
```

This has the flexibility of getting the slotted element(s) as well as making it easy to check for their existence:

```tsx
const hasSomeSlotted = !!getSlotted(el, SLOTS.some);
const slottedItem = getSlotted(el, SLOTS.item);
const slottedItems = getSlotted(el, SLOTS.item, { all: true });
```

The signature could be simplified by taking a flag instead of options too.

**Comment by jcfranco** [comment]
Installed!

**Comment by jcfranco** [comment]
@driskull I'll create a new refactor issue to start using the util.
