### ISSUE TITLE
Bug: Block with new extra padding!

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#791]
### Summary
Extra padding in Block. 👀 

Seems to be coming from [here](https://github.com/Esri/calcite-app-components/blob/master/src/components/calcite-block/calcite-block.scss#L86).

### Actual Behavior
![Screen Shot 2020-01-28 at 3 46 22 PM](https://user-images.githubusercontent.com/12503298/73315676-93ba5580-41e5-11ea-8356-8d230b516f33.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/12503298/73315770-d54b0080-41e5-11ea-9057-9e40aee749c2.png)

### Reproduction Steps

1. Blocks!

### Relevant Info 
@jcfranco Looks like this was a fix for something in Edge? I'm not able to easily test in Edge. :(

**Comment by asangma** [comment]
Not this is nice for stuff in `.content` but seems to be getting applied to stuff in the `.header-container`.

**Comment by asangma** [comment]
@jcfranco I'm also seeing some updates to the header that seem to be causing issues when the `heading` gets long.

![image](https://user-images.githubusercontent.com/12503298/73371443-8e531e80-426a-11ea-997f-f404d46ff30c.png)

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
>  I'm also seeing some updates to the header that seem to be causing issues when the heading gets long.

@asangma I'll create a separate issue for this one.

**Comment by asangma** [comment]
Verified on demos and in MVB locally.
