### ISSUE TITLE
Enhancement: Deprecate "compact" property in Action

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#794]
### Description
Deprecate the "compact" prop.
re: #759

### Acceptance Criteria 
It's deprecated.

### Relevant Info 
See [this comment](https://github.com/Esri/calcite-app-components/pull/792#pullrequestreview-350291565).

#### Which Component
Action

#### Example Use Case
Li'l action.

**Comment by asangma** [comment]
@driskull I'm realizing we use this for when action is used as a button for a Block section, i.e. we reduce the side padding.

Right now, the button is getting padding inside of `calcite-action`'s shadow DOM, so we were using this property to tighten up the side padding to make it align nicely.

Suggest:
- keeping this prop
- keeping the behavior but renaming the prop to be more explicit
- something else?

**Comment by driskull** [comment]
Do you have any idea of what a better name would be? We just don't want to confuse this prop with sizing (scale).

Maybe we just close this and leave it as is.

**Comment by asangma** [comment]
I'm cool with that. We can nix `compact` from the doc and from the Storyboook too...I nixed it from Storybook already..
