### ISSUE TITLE
Bug: [Block] Layout issues in header with long headings

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#804]
### Summary

> I'm also seeing some updates to the header that seem to be causing issues when the `heading` gets long.
 > 
> ![image](https://user-images.githubusercontent.com/12503298/73371443-8e531e80-426a-11ea-997f-f404d46ff30c.png)

Reported in https://github.com/Esri/calcite-app-components/issues/791#issuecomment-579819261

### Actual Behavior

☝️ 

### Expected Behavior

Block layout to not overflow.

### Reproduction Steps

1.

**Comment by jcfranco** [comment]
@asangma Could you help fill in the repro steps in the description? 🙇

**Comment by asangma** [comment]
Urm...it's apparently fixed now. 🤘🏽
