### ISSUE TITLE
Research: getElementDir(el) - can it look past the Shadow?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#806]
### Background 
A Panel inside a FlowItem can't seem to see any `dir="rtl"`, and FlowItem can't add `calcite--rtl` down in a way that Panel can see it. For now, FlowItem can just pass its `dir` value down and let Panel handle it using the `getElementDir` method.

Should `getElementDir` be able to punch through the shadow ceiling?

### Desired Outcome 
Elegance.

**Comment by driskull** [comment]
@jcfranco what do you think? Seems like when we're nesting components, the RTL information gets lost unless we pass it by setting an attribute.

**Comment by driskull** [comment]
Seems like setting the `dir` on the nested component is the best we can do for now.

**Comment by driskull** [comment]
Added wiki discussion for this.
