### ISSUE TITLE
Bug: FlowItem header layout is weird

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#807]
### Summary
The header layout is weird.

### Actual Behavior
👎 
![image](https://user-images.githubusercontent.com/12503298/73871094-13f24380-4802-11ea-82ce-992525071616.png)

### Expected Behavior
👍 
![image](https://user-images.githubusercontent.com/12503298/73871139-29676d80-4802-11ea-812c-2a3f0aa9f11a.png)

### Reproduction Steps

1.

**Comment by asangma** [comment]
@kat10140 Lemme know if you need any background or help on verfeeing this one.

**Comment by kat10140** [comment]
verf!!
