### ISSUE TITLE
Question: Fabulous FAB?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#815]
### Question
Should we make an actual FAB that wraps the `calcite-button` and positions it...or maybe add a FAB option to stuff like `panel`?

### Helpful Details 
There are a number of cases already that would have to do basically [this](https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/pull/1270), and having a consistent FAB experience would be a good thing.

**Comment by driskull** [comment]
> Should we make an actual FAB that wraps the calcite-button and positions it.

Would it be the button or the action?

> add a FAB option to stuff like panel?

A slot would make sense.

**Comment by driskull** [comment]
@asangma want me to take this one?

**Comment by asangma** [comment]
Hey @driskull Yeah....would be cool if you took it. I think it'd be worth discussing some of the cases that can come from nesting and how that affects where the node is placed.

It would probably be good to use `calcite-button` and utilize its props for `round` and `floating`.

**Comment by driskull** [comment]
Yep. Makes sense.

It will also be dependent on this: https://github.com/Esri/calcite-components/issues/334

**Comment by driskull** [comment]
@asangma would we need to accept the following for the FAB?

- color
- appearance
- scale

Or would it always be solid blue medium?

**Comment by driskull** [comment]
@asangma would we want the fab on the Flow & panel? anything else?

**Comment by asangma** [comment]
@driskull 
> would we want the fab on the Flow & panel? anything else?

For now, that should take care of our use cases.

**Comment by asangma** [comment]
re: 
- color
- appearance
- scale

I'm reluctant to do this. I think for now, we set those internally on the calcite-button until we have requests to expose those. In any case, seems like panel/flow-item would have a `fab` slot that we would use and that users could use if they wanna put something custom yeah?

**Comment by asangma** [comment]
Look a gud!
