### ISSUE TITLE
Enhancement: Rename text props we provide a default for to have `intl-` prefix

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#818]
### Description

Enhancement: Rename text props we provide a default for to have `intl-` prefix

### Acceptance Criteria 

All properties that we provide default text in English be prefixed with `intl-` so that we can document the purpose of these properties and have them named consistently.

### Relevant Info 

Also consider having a bundle file where we can reuse some of the common English strings for the defaults.

#### Which Component

All

#### Example Use Case

- `text-close` => `intl-close`
- `text-back` => `intl-back`

### calcite-action-bar

- [x]  textExpand => intlExpand
- [x]  textCollapse => intlCollapse

### calcite-action-pad

- [x]  textExpand => intlExpand
- [x]  textCollapse => intlCollapse

### calcite-block

- [x]  textExpand => intlExpand
- [x]  textCollapse => intlCollapse

### calcite-block-section

- [x]  textExpand => intlExpand
- [x]  textCollapse => intlCollapse

### calcite-filter

- [x]  textLabel => label
- [x]  textPlaceholder => placeholder

### calcite-flow-item

- [x]  textBack => intlBack
- [x]  textClose => intlClose
- [x]  textOpen => intlOpen

### calcite-panel

- [x]  textClose => intlClose

### calcite-tip

- [x]  textClose => intlClose

### calcite-tip-manager

- [x]  textClose => intlClose
- [x]  textNext => intlNext
- [x]  textPrevious => intlPrevious

**Comment by driskull** [comment]
@jcfranco @asangma do we want to do this as a breaking change or as deprecations?

**Comment by jcfranco** [comment]
I vote to deprecate and remove later.

**Comment by driskull** [comment]
## Props to change

### calcite-action-bar

- textExpand => localeExpand
- textCollapse => localeCollapse

### calcite-action-pad

- textExpand => localeExpand
- textCollapse => localeCollapse

### calcite-block

- textExpand => localeExpand
- textCollapse => localeCollapse

### calcite-block-section

- textExpand => localeExpand
- textCollapse => localeCollapse

### calcite-filter

- textLabel => label
- textPlaceholder => placeholder

### calcite-flow-item

- textBack => localeBack
- textClose => localeClose
- textOpen => localeOpen

### calcite-panel

- textClose => localeClose

### calcite-tip

- textClose => localeClose

### calcite-tip-manager

- textClose => localeClose
- textNext => localeNext
- textPrevious => localePrevious


## Bundle

const localeBundle = {
  back: "Back",
  close: "Close",
  open: "Open",
  expand: "Expand",
  collapse: "Collapse",
  next: "Next",
  previous: "Previous"
};

**Comment by driskull** [comment]
@jcfranco do you think you could take the block and filter?

**Comment by jcfranco** [comment]
@driskull Sure thing.

**Comment by kat10140** [comment]
looks good. any reason we don't have intlPlaceholder for filter? closing

**Comment by driskull** [comment]
> any reason we don't have intlPlaceholder for filter? closing

Because we don't supply a default value for it.
