### ISSUE TITLE
Doc: URLs from Storybook notes are broken

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#828]
This is mainly because the notes inject the component `readme.md`s directly and don't adjust the relative URLs.

**Comment by jcfranco** [comment]
Installed. 

Links should be fixed after the next doc update.

**Comment by kat10140** [comment]
@jcfranco there are some that link to other components that don't have their own storybook (eg block-section, flow-item, smaller comps) and so just go to the overview storybook page for our components. I don't think this is a great experience. Do you think it would be worth linking back to the readme's for those smaller non-storybook-doc'd components?

**Comment by jcfranco** [comment]
@kat10140 ☝️ should be fixed now. 😄

**Comment by kat10140** [comment]
yay! verf
