### ISSUE TITLE
Enhancement: Add a convenience for adding calcite-tooltip to Action

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#845]
### Description
Add an easy way for users to "turn on" and hydrate a **CalciteTooltip** in **Action**.

### Acceptance Criteria 
Make it soops easy.

### Relevant Info 
The word "impossible" has dropped in usage by 50% over the last hundred years.

#### Which Component
Action
Maybe add this to more components later as the need arises.

#### Example Use Case
All the Actions in a typical ActionBar.

@kat10140 I assigned a priority, but feel free to update as you see fit.

**Comment by driskull** [comment]
@asangma after thinking about this, I'm not sure its a good idea.

I don't think we want to have a tooltip tied to an action so closely. We want users to be able to place the tooltip and set its content independently of the action. 

We will create a utility in the calcite-components to more easily be able to setup tooltip events though.
