### ISSUE TITLE
Refactor: Add styles to calcite-panel for 'start' and 'end'

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#846]
### Description
Our `calcite-panel` styles are still linked to `leading` and `trailing` properties on the component. After our meeting with the calcite-components team, we've decided to go with `start` and `end` for our props to keep it consistent across the board.  We need to adjust our styles to fit.

Note: for now we are KEEPING leading and trailing until they are fully removed. 

Move Alan magick ovuh to make werk agin!

#### Which Component
calcite-panel

**Comment by asangma** [comment]
Yeyer! Looks like the start and end styles are in there, and I'll need to add the deprecated leading and trailing (back) in.

**Comment by kat10140** [comment]
🤙🏼

**Comment by asangma** [comment]
@kat10140 MURGLED.

**Comment by kat10140** [comment]
@asangma i see leading and trailing but no start end?

**Comment by asangma** [comment]
VERFEED
