### ISSUE TITLE
Bug: [Block] control slot layout issues

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#849]
### Summary

The control slot is positioned absolutely to avoid having it in the button element (prevent it from receiving keyboard mouse events), leading to odd layout when the block width is smaller than the control.

<img width="213" alt="Screen Shot 2020-02-25 at 2 33 31 PM" src="https://user-images.githubusercontent.com/197440/75293848-ecc4db80-57db-11ea-8c76-a925df17fe82.png">

https://github.com/Esri/calcite-app-components/pull/762 introduced this change (mainly to address [this comment](https://github.com/Esri/calcite-app-components/pull/752#discussion_r366544260)).

### Actual Behavior

The slot content is not part of the block layout.

### Expected Behavior

!:point_up:

### Reproduction Steps

This can be seen in https://esri.github.io/calcite-app-components/?path=/story/components-calcite-block--with-header-control.

**Comment by asangma** [comment]
Block likes to use its container for its width. I think the example in the storybook creates a case that is unlikely in the wild. Setting width on the container shows what would more likely happen in an app.
<img width="811" alt="Screen Shot 2020-03-19 at 9 52 32 AM" src="https://user-images.githubusercontent.com/12503298/77093043-ad973e00-69c7-11ea-8296-28f86594338b.png">

As such I'm reluctant to do something like put a min-width on Block, but let me know if you think that's preferable.

**Comment by jcfranco** [comment]
Agreed 💯%!

In that case, should we just update the story to make it more realistic?

**Comment by asangma** [comment]
Ya.

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@kat10140 Can you help verify this one?

**Comment by kat10140** [comment]
verified!
