### ISSUE TITLE
Bug: border width not consistent witih calcite-block-section toggle mode

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#862]
### Description
Per Bjorn: 

Minor, but looks a little sloppy:
![cd19e880-597e-11ea-8ecb-b16e3d8341e3](https://user-images.githubusercontent.com/48069902/75579578-03a54100-5a1b-11ea-9fdd-4ca133f2bc92.png)

### Repro Steps

* https://qa-testing.mapsqa.arcgis.com/apps/mapviewer/index.html?webmap=bc20b4b7c7724365b09addf472d208d2
* click a layer
* Click Style options

### Relevant Info (e.g. Browser, OS, Version, Regression)

* Only tested in Chrome Canary

Original issue:
https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1319

**Comment by jcfranco** [comment]
Installed. @kat10140 plz verrrfeeee. 🙇 🎳 :bowtie:

**Comment by kat10140** [comment]
Verified!
