### ISSUE TITLE
Bug: border width not consistent on action button focus style

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#866]
Similar to #862 

Actions, collapsed and expanded have inconsistent border on focus:

![930a1000-5999-11ea-921f-7e9f5f52b450](https://user-images.githubusercontent.com/48069902/75705480-4ca20300-5c70-11ea-89f2-f8728afdea27.png)
![Screen Shot 2020-03-02 at 10 26 16 AM](https://user-images.githubusercontent.com/48069902/75705481-4e6bc680-5c70-11ea-9d8e-7cbc4a7c9912.png)

I am able to see this on Chrome // windows

**Comment by asangma** [comment]
@kat10140 I'm unable to reproduce.

**Comment by asangma** [comment]
Oh...windows eh?

**Comment by kat10140** [comment]
this is fixed in alan's pr for fixing focus mixin. closing

**Comment by asangma** [comment]
Yeyer! @kat10140
