### ISSUE TITLE
Question: Should <calcite-block-section> be its own component?

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#87]
### Question

Should `<calcite-block-section>` be its own component? Currently, it's block-specific, but would there be use cases where the same design would apply in a non-block context?

### Helpful Details

**Topic:** Possible new component.

**Context:** Stemmed from Block PR: https://github.com/ArcGIS/calcite-app-components/pull/78#discussion_r305558525

cc @pr3tori4n

**Comment by kat10140** [comment]
closing! we don't want to do this bc would encourage bad practices

**Comment by jcfranco** [comment]
*bad practices => blockception 😂
