### ISSUE TITLE
Enhancement: When using tooltips with an action, browsers title popup shows up

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#871]
### Description

When using tooltips bound to an action, we dont want to see the default browser title show up, to do that now I set the "label" property of an action to an empty string but then in some  browsers we still see the browsers title popup appear empty, would be good if there was a way to signal the action to not add a "title" to the element

cc: @driskull 

https://github.com/Esri/calcite-app-components/blob/master/src/components/calcite-action/calcite-action.tsx#L157

**Comment by kat10140** [comment]
@kevindoshier

**Comment by kevindoshier** [comment]
Looks good
