### ISSUE TITLE
Enhancement: calcite-pick-list and calcite-value-list with down/up arrow support

### ISSUE THREAD

**Issue by jenn0003** [Esri/calcite-app-components#873]
### Description
Currently on dev: String + "is" returns strings with a radio button. User does not see the button until they click on an option. 

Once clicked, the radio button appears. If the user clicks the down arrow, the scroll bar moves down. The expectation, and currently on production, is that the down arrow moves the radio selection to the next string.

Currently on dev, the user clicks the first string, then clicks TAB to go to the next string then SPACE BAR to select it. 

It would also be nice to auto scroll the main filter scroll to the bottom of each expression. For example, add one expression then add a second expression. Select a string field, then IS, and now a longer selection of strings appear. At this moment, it would be convenient for the user if the filter scroll automatically scrolled down to the bottom so that the list and the "add expression" button is shown.
### Acceptance Criteria 
1. Radio selection is activated by down arrow for Filter "IS" and "IS NOT"
2. Button appears for all strings. Right now it is all blank so there is no indication that that is an option.
3. Auto-scroll down when multiple expressions are added.

### Relevant Info 
![image](https://user-images.githubusercontent.com/10080810/75923303-a09c1b80-5e19-11ea-884d-07e1ea5ffe45.png)

#### Which Component
Filter

#### Example Use Case
Any layer with domains set. Here is a [public schools layer](https://urbanobservatory.maps.arcgis.com/home/item.html?id=22b7807fc3dc4d089020ba269f7dc766&view=table#data) that has the State field domains that works well with the "is" and "is not" filter. Will need to bring into dev to test the above scenario.

**Comment by AdelheidF** [comment]
created a separate issue for the scrolling: https://devtopia.esri.com/WebGIS/arcgis-components/issues/650

**Comment by driskull** [comment]
@jcfranco is taking this.

**Comment by jcfranco** [comment]
Installed. @jenn0003 @AdelheidF Could you help verify this when released?

**Comment by jenn0003** [comment]
@jcfranco sure thing.  To clarify, we'll test the up and down arrow on the filter after the release?

**Comment by jcfranco** [comment]
Yes to the testing part. Not sure if this is targeted for beta 5 or after.

**Comment by jcfranco** [comment]
@jenn0003 This is on devext now. Would you mind testing it out? Thanks!

**Comment by jenn0003** [comment]
The up/down arrow option for filtering works well on dev. Looks great!

**Comment by jcfranco** [comment]
Awesome, thanks for verifying @jenn0003!
