### ISSUE TITLE
Enhancement: Simplify typographic hierarchy

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#886]
### Description
Use a more reductive approach to our typography. Rely less on sizes and weights.

### Acceptance Criteria 
Better typography.

### Relevant Info 
Map Viewer Beta UI is starting to look pretty chunky.

#### Which Component
All.

#### Example Use Case
Map Viewer Beta

Note: would be good to test this out fully in a fully fledged app.

**Comment by asangma** [comment]
Preliminary look
![calcite-app-components-TYPOGRAPHY-UPDATE](https://user-images.githubusercontent.com/12503298/77109123-9fa1e700-69e0-11ea-81e5-a899456b6217.jpg)

**Comment by asangma** [comment]
Facsimile in an app
![calcite-app-components-TYPOGRAPHY-UPDATE-MVB](https://user-images.githubusercontent.com/12503298/77109379-07f0c880-69e1-11ea-8e84-f3d697e87f24.jpg)

**Comment by asangma** [comment]
Moving this to LSP for Beta 6.

![lsp](https://media.giphy.com/media/8tDnmyXB7YqEU/source.gif)

**Comment by kat10140** [comment]
This looks good on my local demos and storybook!
