### ISSUE TITLE
Enhancement: Block - add a menu-actions slot like FlowItem

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#894]
### Description
Wiring up the same UX in Block is hard and often sees devs using calcite-dropdown and looks like this.
<img width="322" alt="Screen Shot 2020-03-25 at 2 22 01 PM" src="https://user-images.githubusercontent.com/12503298/77587035-6536bf00-6ea4-11ea-9e06-5ea101c7e07e.png">

Would be nice if Block could do what FlowItem does using the same pattern.
<img width="286" alt="Screen Shot 2020-03-25 at 2 23 26 PM" src="https://user-images.githubusercontent.com/12503298/77587091-7da6d980-6ea4-11ea-802b-8475acae3ef3.png">

### Acceptance Criteria 

- don't break the control slot?
- use same pattern as FlowItem's `menu-actions`

#### Which Component
Block

#### Example Use Case
Any time we need actions coming out of a `...` menu.

**Comment by jcfranco** [comment]
> don't break the control slot?

@asangma Regarding ☝️, would we want to make the control and menu mutually exclusive? I'm not sure if displaying both would be a valid use case.

**Comment by kat10140** [comment]
https://github.com/Esri/calcite-components/issues/963
