### ISSUE TITLE
Component: PickList and PickListItem components

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#9]
A Picker component that allows for the following:

- Multiple selection
- Drag and drop reordering
- A separate "Filter" input component to allow filtering the list

Derived from: https://devtopia.esri.com/WebGIS/ui-components-js/issues/6

#### User Stories
User wants to use this multiple select item and receive all that items as an event call back.

### Acceptance Criteria <small>(a.k.a. Requirements)</small>

note: These modes are tentative. @asangma needs to confirm with design
"Selection mode" means that
- select state is show using a checkbox or radio button.
- no drag-n-drop reordering
- no "edit" mode

"Configuration mode" means that
- select state is shown using the border
- drag-n-drop reordering is available
- "edit" mode is available.

#### Desired Behavior : end user
In "selection mode" user should be able to
- view a list of items
- view multiple lists of items
  - revealed as "groups" with headings
- select one or many items
  - CTRL / SHFT?
- deselect one or many items
  - CTRL / SHFT?
- know what items are selected
- know whether she can select one or many items
- have access to either a secondary action or additional visual distinction (i.e. icon/graphic)
  - e.g. "more info about this item"
  - icon
  - some graphic

In "configure mode" user should be able to
- toggle one or many items
- know what items are toggled
- have access to either a secondary action or additional visual distinction (i.e. icon/graphic)
  - e.g. "more info about this item"
  - icon
  - some graphic
- remove items
- _reorder items via drag and drop (nice to have)_

#### Desired Behavior : developer
Developer should be able to
- get a return of selected items
- apply selected state to items
- allow user to toggle selection on one or many items
- update what items are in a list
- set list to be multi or single select
- set list to be in "configuration" or "selection" mode

#### calcite-picker

**Interface**

```ts
interface CalcitePicker {

  @Prop({ reflect: true }) textHeading: string;

  @Prop({ reflect: true }) mode: "selection" | "configuration" = "selection";

  @Prop({ reflect: true }) multiple = false;

  @Prop({ reflect: true }) dragEnabled = false; /* ignored unless mode is configuration */

  @Prop({ reflect: true }) editEnabled = false; /* ignored unless mode is configuration */

  @Prop({ reflect: false }) data = [];

  @Event() calcitePickerSelectionChanged: EventEmitter;

  @Method() getSelectedRows()
}
```

```html
<calcite-picker mode="configuration" multiple="true" dragEnabled="true">
  <!-- rows -->
</calcite-picker>
```

#### calcite-picker-group

```ts
interface CalcitePickerGroup {
  @Prop({ reflect: true }) textGroupTitle: string;
}
```

#### calcite-picker-row

```ts
interface CalcitePickerRow {
  @Prop() heading: string;

  @Prop() description: string;

  @Prop() value: string;

  @Prop() selected = false;

  @Prop({ reflect: true }) icon: "square" | "circle" | "grip" | null = null;
}
```

```html
<calcite-picker-row heading="hello world" description="hi" selected value="helloWorld">
  <calcite-action slot="secondaryAction"></calcite-action>
  <calcite-action slot="editAction"></calcite-action>
</calcite-picker-row>
```

#### calcite-filter-input

```ts
interface CalciteFilterInput {
  @Prop() heading: string;

  @Prop() data: Array<Object>;

  @Event() calciteFilterChange: EventEmitter;
}
```

```html
<calcite-filter-input heading="search" onCalciteFilterChange="">
</calcite-filter-input>
```

**Comment by driskull** [comment]
I think more requirements gathering is needed for filter. Looking at the issue, there are not any requirements listed for the filter component.

Filter questions: @asangma @jcfranco @pr3tori4n 

- Should the filter accept a dataset as a property or a nodeList (elements) as child content?
  - Related: Should the filter return a modified dataset or should the filter result in a custom property change on child elements? (the former leaves it up to the dev to do the dom manipulation and the latter handles the dom manipulation)
- Should the filter be tied to an input or should it be up to the user to bind the filter to an input or whatever should cause the filter to happen? 
- Should there be a defined schema for filtering or should it just lookup information from the data/child nodes? For example, how would a filter of category "webmap" happen? Wouldn't want to match an item that has text "webmap" but isn't a category of "webmap". This gets into how we would define filtering options for when to use exact matching, like matching, or vs and, etc.

**Comment by pr3tori4n** [comment]
@asangma There's some discussion around the best way to house the list of selectedRows. Originally I was using a Set since it eliminated dupes for me, but now i'm using a plain object, so I can get key:value pairs. A plain object doesn't keep track of the order items are added to it. Is that a requirement? If so we'll probably switch to using a Map. The downside of a Map is it doesn't support dot notation, so we'd have to doc that so users know to use the `get(<key>)` method to retrieve an item from the collection.

**Comment by asangma** [comment]
@pr3tori4n I'm good with whatever as long as a configuration list can receive items in the same order in which they were selected in the selection list.

E.g.
Browse/selection list contains
- A
- B
- C

User wants to add C and A to another configuration list. User clicks C then A.

Configuration list should look like
- C
- A

Hope that helps.

**Comment by pr3tori4n** [comment]
@asangma  please verify.

**Comment by asangma** [comment]
Looks good. Are we doing a separate issue for styling?

**Comment by pr3tori4n** [comment]
@asangma separate branch for sure. We can use this same issue if that's easiest.

**Comment by asangma** [comment]
Mind creating an issue to style this thang? You or @kat10140? :)

**Comment by pr3tori4n** [comment]
@kat10140 @asangma 
https://github.com/Esri/calcite-app-components/issues/268

**Comment by asangma** [comment]
is this still a thing?

**Comment by pr3tori4n** [comment]
@kat10140 can you verify this?

**Comment by kat10140** [comment]
Verified

**Comment by driskull** [comment]
Moving wiki

---

## ListBrowser
This component enables finding and selecting one or many items as part of a workflow. The ListItems in the list should update based on the type of selection to be done (direct, single, multiple) without requiring the developer to tell the item to use e.g. a radio or checkbox.

Long term goal would be to build the ItemBrowser and similar workflows using this component.

## ListBrowser Requirements
- show list of things
- single and multiple selection
- reordering (drag and drop)
  - possibly action to send to a specific spot, e.g. move to top/bottom
- enable text filtering (search like)
- enable deleting things from the list?

## ListItem Requirements
- indicate selection
  - allow explicit indicator (check/radio)
  - allow implicit indicator (border)
- display title
- display description (optional)
- secondary affordance
  - action | graphic | HTML
- indicate delete action
- indicate drag functionality

## Not a select
[calcite-components super-select](https://github.com/ArcGIS/calcite-components/issues/61)<br/>
This component would not be tied to a `select` input. While it might update the value of a select, its main goal is to provide a rich but compact browsing experience for adding elements to another list. For instance, adding popup elements during popup configuration or when selecting a field.

Also, unlike a `select`, this component will provide an area for additional information per list item in the form of a description. Developers will also be provided with an area for one of these: icon, graphic, or action. In addition, this list will provide drag-and-drop reordering.

Design hopes include offering more designed list views such as 2-up cards and the like.

### Related example
Here is an example from YouTube Studio beta: [⬇️ DOWNLOAD](/ArcGIS/calcite-app-components/wiki/video/ListBrowser-YouTube-Studio.mp4)

<figure class="video_container">
  <video controls="true" allowfullscreen="true" >
    <source src="/ArcGIS/calcite-app-components/wiki/video/ListBrowser-YouTube-Studio.mp4" type="video/mp4">
  </video>
</figure>


### Has
* Header
  - Heading
  - [ Filter input | null ]
* Content
  - ~New ListItem action~
  - Edit mode toggle
  - ListGroup or multiple Lists
    - heading
    - ListItems

### Options
* list style: [ card | compact ]
* selectionMode: [ single | multiple | toggle ]
* dragAndDropEnabled: BOOL
* editEnabled: BOOL

### States
* isEditing
  - updates ListItems to be in edit mode
* isDragging

## ListItem
The whole thing is a button that results in the primary action. Generally this would be to select and possibly input the thing into some other part of the interface, e.g. selecting fields to show in the Popup.
### Has
* Heading
* Description
* [ Action | graphic | HTML ] Secondary (because Primary is the item itself)

### Options
* item style [ card | compact ]
* selection: [ single | multiple | toggle ]
* dragAndDropEnabled: BOOL
  - when enabled, item shows dnd handle
  - offer option to override the default handle graphic

### States
* idle
* hover
* current
* selected
* editing
  - disable actions
  - replace end side action with trashcan to allow removing item
* dragging


---
[[/images/List-and-ListItem/List-UI.png]]
[[/images/List-and-ListItem/List-skeleton.png]]
[[/images/List-and-ListItem/ListItem-selection-skeleton.png]]
[[/images/List-and-ListItem/ListItem-config-skeleton.png]]


---

## Project Team Roles
- PE - Katy
- UI Designer - Alan
- Developer - Harry
- UX Architect - Tao (?)

## Tasks to be assigned:
- Comparative Research [PE & UI]
- Research user stories [PE & UI]
- Write user stories : [PE & UI] meeting
- Document requirements and user stories in planning issue [PE]
- Gather any additional requirements and add to planning issue. [PE]
- Any necessary dev Research [DEV]
- Create new issues [PE]
- A TypeScript interface rough draft should be produced. [DEV]
- Produce preliminary wireframes/designs [UI]
- Designs should approach a broader epic story (which may not yet be defined) and should also be modular enough to accommodate release planning

## 7/2 Kickoff/Wireframe Review Meeting Notes
- difference between icon select and border select
- prioritize v1 vs v2 
- drag and drop and the checkbox & radio button select are mutually exclusive 
- update issue with relevant details
- consider custom list item v2 at best
- research issue for drag and drop 
- attach wireframes to issue 
- drag and drop for v2?? or nice to have 
- sync on Friday

---

Reference designs and wireframes
---
[[/images/List-and-ListItem/List-UI.png]]
[[/images/List-and-ListItem/List-skeleton.png]]
[[/images/List-and-ListItem/ListItem-selection-skeleton.png]]
[[/images/List-and-ListItem/ListItem-config-skeleton.png]]
