### ISSUE TITLE
Bug: flow-item & pick-list/value-list icons are not rendering

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#902]
### Summary

The latest release of [`calcite-components`](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#v100-beta21---mar-31st-2020) dropped `calcite-icon`'s `filled` attribute and prevents rendering of the icon.

### Actual Behavior

`flow-item`'s back button & `pick-list-item`'s checked status icons are not rendering.

### Expected Behavior

!:point_up:

### Reproduction Steps

1. Load the `calcite-flow` & `calcite-pick-list`/`calcite-value-list` sample page with the latest.

**Comment by jcfranco** [comment]
Installed.

**Comment by kat10140** [comment]
verified!
