### ISSUE TITLE
Enhancement: Add tooltip knob to stories for action-bar & action-pad

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#910]
### Description

Add a storybook knob that accepts a dom node for the `tooltipExpand` property on the `calcite-action-bar` and `calcite-action-pad`.

https://github.com/Esri/calcite-app-components/pull/904/#pullrequestreview-386584312

#### Which Component

`calcite-action-bar` and `calcite-action-pad`.

**Comment by jcfranco** [comment]
@kat10140 Can you help verify once the doc updates (next release)? 🙇‍♂️

**Comment by kat10140** [comment]
yap! 😀

**Comment by kat10140** [comment]
verf!
