### ISSUE TITLE
Docs: document supported browsers

### ISSUE THREAD

**Issue by bsvensson** [Esri/calcite-app-components#924]
### Description

I couldn't find any info about supported browsers. It would be nice to have that clearly documented like https://github.com/Esri/calcite-components/#browser-support

### Which Component

README.md

**Comment by bsvensson** [comment]
Thanks @driskull 

https://github.com/Esri/calcite-app-components#browser-support looks good, but what about IE11? If it doesn't support it, should it say so?  The current write-up leaves me wondering... :)

**Comment by driskull** [comment]
@bsvensson should list every browser or just go with if its not on the list then its not supported?

I think its ok that if its not on the list then its not supported. Do we really need to list Opera, opera mini? etc.

**Comment by bsvensson** [comment]
Fine with me :)

Closing.
