### ISSUE TITLE
Tooling: previewChangelog enhancements

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#936]
## Summary 

The `previewChangelog` NPM script requires all tags to be fetched for it to generate the changelog accordingly. 

cc @kat10140 

## Measure of Success 

1. Tags are fetched automatically before generation.
2. Only the most recent changes should be output to minimize noise.

**Comment by jcfranco** [comment]
Added new script to preview the changelog since last release (`previewChangelog:latest`)!

**Comment by kat10140** [comment]
@jcfranco This is erroring out for me on master :/ i have pulled and `npm i`.... 
saying git touch isn't a command

**Comment by jcfranco** [comment]
Whoops! That's from a plugin I have installed. Assigning back to me. Sorry about that. 😅

**Comment by jcfranco** [comment]
Installed. @kat10140 Can you test again?

**Comment by kat10140** [comment]
yay lookin good!! verf.
