### ISSUE TITLE
Enhancement: list with check and sorting

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#937]
### Description

For the table in map viewer Beta. A way to sort and hide/show fields in one list. Maybe we could just enhance calcite-pick-list.

![image](https://user-images.githubusercontent.com/44481292/79907274-2fff8d00-83ce-11ea-89e7-ba6257ae6ef7.png)

**Comment by asangma** [comment]
@AdelheidF Is the sorting for ordering the field columns in the FeatureTable? I believe Jon said this could be done directly in the table, i.e. without needing to use a separate UI.

**Comment by AdelheidF** [comment]
> Is the sorting for ordering the field columns in the FeatureTable?

Yes
