### ISSUE TITLE
Enhancement: Storybook and demo fix for picklist and valuelist

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#940]
### Description
In PickList and ValueList demos, the circle icon is often mistaken for a radio button.

### Acceptance Criteria 
Kill the radio star.

#### Which Component
Pick and Value List demos.

**Comment by asangma** [comment]
![Screen Shot 2020-04-23 at 4 23 22 PM](https://user-images.githubusercontent.com/12503298/80159197-3c771780-857f-11ea-9f65-dd7cf45e3fca.png)

**Comment by asangma** [comment]
![Screen Shot 2020-04-23 at 4 27 47 PM](https://user-images.githubusercontent.com/12503298/80159296-7b0cd200-857f-11ea-98f4-3d612b888a08.png)
![Screen Shot 2020-04-23 at 4 28 07 PM](https://user-images.githubusercontent.com/12503298/80159304-7ea05900-857f-11ea-9f04-b80d26380bbc.png)

**Comment by asangma** [comment]
But maybe not banana.

**Comment by kat10140** [comment]
lewks gewd

**Comment by asangma** [comment]
Thanks @kat10140 !
