### ISSUE TITLE
Bug: loading state on block header all funky

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#941]
### Summary
loading state is all off the the side now:
<img width="246" alt="Screen Shot 2020-04-23 at 4 30 20 PM" src="https://user-images.githubusercontent.com/48069902/80159501-fe2e2800-857f-11ea-858d-3ebcdc9e8135.png">

### Actual Behavior
off center

### Expected Behavior
center

This may have been an effect of the refactor to use grid

**Comment by kat10140** [comment]
<img width="234" alt="Screen Shot 2020-05-07 at 1 18 55 PM" src="https://user-images.githubusercontent.com/48069902/81340827-5af00f00-9065-11ea-8f1d-e833b72beb1e.png">
 is this. meant to be on the side? @asangma

**Comment by asangma** [comment]
Ya.

**Comment by kat10140** [comment]
okee verfee
