### ISSUE TITLE
Enhancement: Implement focus mixin to match calcite-components

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#945]
### Description
calcite-components has standardized :focus styles and animations. Update relevant styles to match.

### Acceptance Criteria 
Aligned styles.

#### Which Component
Probably all.

**Comment by asangma** [comment]
I believe the PR handled #866 as well.

**Comment by kat10140** [comment]
![Screen Shot 2020-04-28 at 4 08 50 PM](https://user-images.githubusercontent.com/48069902/80546547-c69df200-896a-11ea-9ba1-1759eefadf52.png)
Tip manager is the only one that looks kinda weird
@asangma

**Comment by asangma** [comment]
Cool. I'll have a look.

**Comment by kat10140** [comment]
yew!
