### ISSUE TITLE
Bug: Trailing letter gets wrapped when using calcite-value-list in safari browser

### ISSUE THREAD

**Issue by subgan82** [Esri/calcite-app-components#949]
### Summary

This looks like  a styling issue coming from `calcite-value-list-item`.

https://github.com/Esri/calcite-app-components/blob/master/src/components/calcite-pick-list-item/calcite-pick-list-item.scss#L54

https://github.com/Esri/calcite-app-components/blob/master/src/scss/mixins/_utilities.scss#L21

**Code**
![1](https://user-images.githubusercontent.com/1017712/80609606-ea5e4800-89fd-11ea-85df-1c82feda437a.png)

### Actual Behavior

**CSS**

![2](https://user-images.githubusercontent.com/1017712/80609628-f0ecbf80-89fd-11ea-99ec-b4a73d164472.png)
![3](https://user-images.githubusercontent.com/1017712/80609636-f2b68300-89fd-11ea-94fe-001893e2975b.png)

### Expected Behavior

**removing break-all**

![4](https://user-images.githubusercontent.com/1017712/80609658-fb0ebe00-89fd-11ea-94b4-e13bfce4e530.png)

![5](https://user-images.githubusercontent.com/1017712/80609711-0e218e00-89fe-11ea-945e-5f1cdf7aece1.png)

### Reproduction Steps

_Originally posted by @gane5688 in https://devtopia.esri.com/WebGIS/arcgis-charts/issues/971#issuecomment-2203311_

https://devtopia.esri.com/WebGIS/arcgis-charts/issues/971?

### Relevant Info 

1. Observed in Safari Browser.

**Comment by asangma** [comment]
@subgan82 Let me know if you're still seeing this issue.

**Comment by subgan82** [comment]
Thanks @asangma will test it .

**Comment by subgan82** [comment]
Tested with `@next` version the issue is fixed
![2020-06-17_19-43-12](https://user-images.githubusercontent.com/1017712/84964842-d2887380-b0d2-11ea-8ede-58e13f61526c.png)

**Comment by jcfranco** [comment]
Per ☝, closing as verified.
