### ISSUE TITLE
Enhancement: FAB sticky in panel container with h-scroll

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#952]
### Description
When using the `fab` slot in Panel and there is horizontally scrolling content, the fab gets scrolled away. 

We'll probs see this in the new CalciteShellCenterRow component.

BAD
![fab-issue](https://user-images.githubusercontent.com/12503298/80844000-803ed200-8bba-11ea-86dd-457acbc46bc4.gif)

GOOD
![fab-good](https://user-images.githubusercontent.com/12503298/80844015-892fa380-8bba-11ea-8145-c70b2a6d1874.gif)

#### Which Component
Panel

cc @kat10140

**Comment by asangma** [comment]
@kat10140 Pease see the `shell/demo-app-advanced-center-row.html` demo to test this.

**Comment by kat10140** [comment]
yay! vurf
