### ISSUE TITLE
Enhancement: shell-center-row. Move bg-color and border styles from .content to :host

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#955]
### Description
A couple styles are in this components shadow DOM.
I think it'd be good to move those styles to the `host` so that app devs can have little more control over ShellCenterRow in case they want to something like this:
![image](https://user-images.githubusercontent.com/12503298/81080793-03577500-8ea6-11ea-815d-eccaf67c7736.png)

I'm open to discussing whether this is a good pattern or not.

### Acceptance Criteria 

- more readily available base styles

#### Which Component
CalciteShellCenterRow

#### Example Use Case
Charts.

**Comment by asangma** [comment]
Mind you...I'm not stoked on that xp 👆🏽but I think it'd be good to be able to reset the bg-color and border if need be.

**Comment by driskull** [comment]
@asangma can't we just flexbox the slotted `calcite-shell-center-row` components so that they take up the space available?

**Comment by asangma** [comment]
We could. I think if someone wants add columns inside the row component, they can style a div to do that and put it into the default slot.

I am thinking though that maybe we set the bg-color to transparent as you suggested in a related conversation. We could also want to nix the border on center-row. Would need to nix the border from shell-panel to match.

**Comment by driskull** [comment]
I'm ok with that. As long as we're consistent

**Comment by asangma** [comment]
Cool.

**Comment by asangma** [comment]
Verfee please.

**Comment by kat10140** [comment]
ferf!!
