### ISSUE TITLE
Enhancement: FlowItem should give access to Panel's header-leading-content slot

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#958]
### Description
Right now, in **FlowItem**, we are taking over **Panel’s** 'header-leading-content' slot with the back button when there are more than 1 FlowItem’s in a Flow.

What do y’all think about retaining access to **Panel**’s `header-leading-content` slot available in **FlowItem**? We’d add the back-button as it’s own thing (i.e. not using a slot) or just “overload” the `header-leading-content` slot in **Panel**.

### Acceptance Criteria 
No breaking changes.

### Relevant Info 
LayerSwitcher and future possibilities.

#### Which Component
FlowItem and Panel

#### Example Use Case
re: LayerSwitcher
Right now, Kevin will be using FlowItem’s `menu-actions` slot to add an **Action** to invoke the "layer switcher". This will work, but there might be design advantages to having the trigger on in the leading area:

* There may be cases where both the back button and a leading action might be needed
* The trigger can be a bit far from the title if the title is short.
* Other things...

**Comment by driskull** [comment]
> There may be cases where both the back button and a leading action might be needed

I would say just use the center slot `header-content`

**Comment by asangma** [comment]
Can they do that in FlowItem?

**Comment by driskull** [comment]
> Can they do that in FlowItem?

Not currently, we only allow a string for that right now. We could add another slot.

**Comment by asangma** [comment]
I'll add a bullet to our sync.

**Comment by asangma** [comment]
@kat10140 Easiest way to test this one is to inspect "Item Three" and "Item Two" in `demos/flow/basic.html`.
![image](https://user-images.githubusercontent.com/12503298/81714286-c4886880-942b-11ea-9544-5750422e7e20.png)
Bill helps.

**Comment by kat10140** [comment]
Looks like the back button (calcite-action) is using that slot, if that's what i'm looking for?

**Comment by kat10140** [comment]
VURF!
