### ISSUE TITLE
Bug: calcite-pick-list: two issues with RTL

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#959]
### Summary
2 issues
1.) open menu not fully visible in RTL
2.) search magnifying icon on wrong side in RTL

LTR:
<img src=https://user-images.githubusercontent.com/44481292/81216645-1b0b2800-8f90-11ea-8520-8fd535de3069.png width=200/>

RTL:
<img src=https://user-images.githubusercontent.com/44481292/81216692-2c543480-8f90-11ea-9312-43820cd1ac20.png width=200/>

```
<calcite-dropdown slot="menu-actions" alignment="end">
        <calcite-action
          key="attribute-selector-sort"
          slot="dropdown-trigger"
          label={i18n.ui.sortFields}
          aria-label={i18n.ui.sortFields}
        >
          <calcite-icon scale="s" icon="sortDescending"></calcite-icon>
        </calcite-action>
        <calcite-dropdown-group grouptitle={i18n.ui.sortBy}>
          <calcite-dropdown-item ... >
            {i18n.ui.sortByDisplayName}
          </calcite-dropdown-item>
          ...
        </calcite-dropdown-group>
      </calcite-dropdown>
```
### Reproduction Steps

1.

**Comment by asangma** [comment]
@AdelheidF Looks like it's a calcite-components issue. I posted an issue there.

**Comment by asangma** [comment]
Correction, the DropDown issue appears to be calcite-app-components. I'll look at the search icon.

**Comment by asangma** [comment]
@jcfranco It looks for the search icon in calcite-filter, the styles are there to place it correctly in RTL but calcite-filter isn't checking for RTL. ¯\_(ツ)_/¯

**Comment by asangma** [comment]
Assigning back to me.

**Comment by asangma** [comment]
@kat10140 VERFS!

**Comment by kat10140** [comment]
ferfs!!!
