### ISSUE TITLE
Enhancement: ActionPad. Add horizontal orientation

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#967]
### Description
Add a property that will allow users to set the orientation of the ActionPad to horizontal.

### Acceptance Criteria 
![image](https://user-images.githubusercontent.com/12503298/81356310-bf22cb00-9085-11ea-93c9-850985db2584.png)
![image](https://user-images.githubusercontent.com/12503298/81356316-c34ee880-9085-11ea-9686-96f4f2022201.png)

### Relevant Info 
| vs –

#### Which Component
ActionPad and ActionGroup

#### Example Use Case
Toolbars for table editing or chart configuring.

cc @driskull

**Comment by driskull** [comment]
Would this ever make it to the `action-bar`?

**Comment by driskull** [comment]
@asangma @jcfranco can you help name this property?

We could go with:

- `layout` of `horizontal/vertical` but we already have a deprecated layout property so this would be a breaking change.
- `orientation` of `portrait/landscape` or `horizontal/vertical`?
- `direction` of `row/column` or `horizontal/vertical`. May sound too similar to `dir` attribute?

My vote would be toward `layout` or `direction`

layout is used here: https://github.com/Esri/calcite-components/blob/ad9ca1559f54326e66d47619cb78f3f9f4174547/src/components/calcite-radio-group/calcite-radio-group.tsx#L87

**Comment by jcfranco** [comment]
I like `layout` and it's also the consistent option.

**Comment by driskull** [comment]
Ok cool. We can talk about it at the next meeting. I could remove all deprecated things and we would be at V 6.0

**Comment by driskull** [comment]
Decision was to use `layout` and remove all deprecations and do a major release.

**Comment by kat10140** [comment]
verf!
