### ISSUE TITLE
Research: Use storyshots to automate a11y testing

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-app-components#973]
### Background 

https://github.com/Esri/calcite-app-components/pull/963 enabled a tab to show a11y results that can be used to surface issues across use cases and different knob combinations. This relies on manually testing at the moment, but maybe https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-puppeteer#axetest could be used to do automated a11y testing.

### Desired Outcome 

Use component stories and knob combinations to automatically run a11y testing.

**Comment by kat10140** [comment]
https://github.com/Esri/calcite-components/issues/964
