### ISSUE TITLE
Enhancement : PickList & PickListItem. Add "appearance" prop with "clear" as available option.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#978]
### Description
Update PickList and PickListItem to have a transparent bg-color.
<img width="240" alt="Screen Shot 2020-05-12 at 2 24 28 PM" src="https://user-images.githubusercontent.com/12503298/81747146-70e24300-945c-11ea-9d42-2bb6748fa116.png">

#### User Stories
User wants to create a PickList that is visually distinct from other PickLists such as for a list of options that will trigger a drill in using something like FlowItems.

### Acceptance Criteria 
* It should work with flow & flow-items.
* don't break stuff
* ~Clicking/tapping a FlowMenuItem would trigger a Flow animation into a new FlowItem~

### Helpful Details

CC ISSUE https://github.com/Esri/calcite-components/issues/970

**Comment by asangma** [comment]
@driskull @jcfranco @kat10140 Could use some discussion on how this thing would work. Like would it wrap PickList and PickListItem like ValueList does?

And does it and Flow need to know anything about each other?

**Comment by driskull** [comment]
@asangma why does this need to be a new component? 

Couldn't the pick-list just handle this without needing to integrate with a flow-item? It can just control a flow item when clicked, right?

**Comment by asangma** [comment]
@driskull yeah...def would like to meet to discuss.

**Comment by driskull** [comment]
![deal](https://media.giphy.com/media/Xoc3XpBrElaYo/giphy.gif)

**Comment by asangma** [comment]
Updated first comment.

**Comment by asangma** [comment]
@driskull We should discuss how a user would turn off the icon. Also, I'm starting to think about a wrapper thing again.

**Comment by driskull** [comment]
Let's talk about it at this weeks meeting. We can come up with the best solution.

**Comment by asangma** [comment]
![i like it](https://media.giphy.com/media/mFBIHvRrntt2JJLkrp/giphy-downsized.gif)

**Comment by jcfranco** [comment]
Moved to Esri/calcite-components#970
