### ISSUE TITLE
Bug: calcite-block-section - no space between label and toggle button

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#993]
### Summary
5.7.3
<img src=https://user-images.githubusercontent.com/44481292/82508091-d9629d00-9ab8-11ea-91f9-34983ef39e0e.png width=200/>

6.0.0
<img src=https://user-images.githubusercontent.com/44481292/82508078-cfd93500-9ab8-11ea-8fc8-48ef121795b3.png width=200/>
<img src=https://user-images.githubusercontent.com/44481292/82508182-2181bf80-9ab9-11ea-938f-d6aae418dde1.png width=200/>

### Reproduction Steps

1.

**Comment by asangma** [comment]
Thanks @AdelheidF. Looks like a RTL class is getting triggered incorrectly. I'll put in a PR.

**Comment by asangma** [comment]
@kat10140 VERF!

**Comment by kat10140** [comment]
VURF
