### ISSUE TITLE
Enhancement: Use word-break instead of break-all

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#996]
### Description
We are using break-all as part of [a CSS hack](https://github.com/Esri/calcite-app-components/blob/master/src/scss/mixins/_utilities.scss#L11) to enable truncation after two lines of text.

This hack lets us truncate after two lines of text but requires the use of break-all. Not ideal.

It may be better to allow for unlimited lines of wrapping in exchange for better word breaks. Such as this:

```
  word-wrap: break-word;
  word-break: break-word;
```

Words will break only if there is not a readily available option.

@AdelheidF Would like to get your thoughts on this since it would remove the 2-line limitation.

### Acceptance Criteria 
More readable strings.

#### Which Component
PickListItem and ValueListItem by extension.

#### Example Use Case
![image](https://user-images.githubusercontent.com/12503298/82841393-ba825300-9e8a-11ea-9bd1-dc763441e104.png)

**Comment by asangma** [comment]
@kat10140 VERF. 🙏

**Comment by kat10140** [comment]
verf!
